<?php
/**
 * This file is part of the Omnity project.
 *
 * Copyright (c) 2020 Eki Prathama Ramdhani <eq.petrucci@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author Eki Prathama Ramdhani <eq.petrucci@gmail.com>
 * @file   menu.php
 * @date   17/09/2020 02.02
 */

return array(
	array(
		'name'      => 'dashboard',
		'parent_id' => 'NULL',
		'title'     => 'Dashboard',
		'route'     => 'home',
		'attrs'     => '{"icon": "fad fa-chart-pie"}',
		'level'     => '1',
		'role_id'   => '8',
		'divider'   => '0',
		'enabled'   => '1',
	),
	array(
		'name'      => NULL,
		'parent_id' => NULL,
		'title'     => NULL,
		'route'     => NULL,
		'attrs'     => NULL,
		'level'     => '2',
		'role_id'   => '8',
		'divider'   => '1',
		'enabled'   => '1',
	),
	array(
		'name'      => 'user-profile',
		'parent_id' => NULL,
		'title'     => 'Profile',
		'route'     => NULL,
		'attrs'     => '{"icon": "fad fa-user-circle"}',
		'level'     => '3',
		'role_id'   => '8',
		'divider'   => '0',
		'enabled'   => '1',
	),
	array(
		'name'      => NULL,
		'parent_id' => NULL,
		'title'     => NULL,
		'route'     => NULL,
		'attrs'     => NULL,
		'level'     => '4',
		'role_id'   => '8',
		'divider'   => '1',
		'enabled'   => '1',
	),
	array(
		'name'      => 'attendance',
		'parent_id' => NULL,
		'title'     => 'Attendance',
		'route'     => 'attendance.index',
		'attrs'     => '{"icon": "fad fa-calendar-check"}',
		'level'     => '5',
		'role_id'   => '8',
		'divider'   => '0',
		'enabled'   => '1',
	),
	array(
		'name'      => 'employee',
		'parent_id' => NULL,
		'title'     => 'Employees',
		'route'     => 'employee.index',
		'attrs'     => '{"icon": "fad fa-user-hard-hat"}',
		'level'     => '6',
		'role_id'   => '8',
		'divider'   => '0',
		'enabled'   => '1',
	),
	array(
		'name'      => NULL,
		'parent_id' => NULL,
		'title'     => NULL,
		'route'     => NULL,
		'attrs'     => NULL,
		'level'     => '7',
		'role_id'   => '8',
		'divider'   => '1',
		'enabled'   => '1',
	),
	array(
		'name'      => 'tasks',
		'parent_id' => NULL,
		'title'     => 'Tasks',
		'route'     => 'task.index',
		'attrs'     => '{"icon": "fad fa-tasks"}',
		'level'     => '8',
		'role_id'   => '8',
		'divider'   => '0',
		'enabled'   => '1',
	),
	array(
		'name'      => 'assignments',
		'parent_id' => NULL,
		'title'     => 'Assignments',
		'route'     => 'assignment.index',
		'attrs'     => '{"icon": "fad fa-briefcase"}',
		'level'     => '9',
		'role_id'   => '8',
		'divider'   => '0',
		'enabled'   => '1',
	),
	array(
		'name'      => 'trackers',
		'parent_id' => NULL,
		'title'     => 'Trackers',
		'route'     => NULL,
		'attrs'     => '{"icon": "fad fa-location-arrow"}',
		'level'     => '10',
		'role_id'   => '8',
		'divider'   => '0',
		'enabled'   => '1',
	),
	array(
		'name'      => NULL,
		'parent_id' => NULL,
		'title'     => NULL,
		'route'     => NULL,
		'attrs'     => NULL,
		'level'     => '11',
		'role_id'   => '8',
		'divider'   => '1',
		'enabled'   => '1',
	),
	array(
		'name'      => 'customers',
		'parent_id' => NULL,
		'title'     => 'Customers',
		'route'     => 'customer.index',
		'attrs'     => '{"icon": "fad fa-address-book"}',
		'level'     => '12',
		'role_id'   => '8',
		'divider'   => '0',
		'enabled'   => '1',
	),
	array(
		'name'      => NULL,
		'parent_id' => NULL,
		'title'     => NULL,
		'route'     => NULL,
		'attrs'     => NULL,
		'level'     => '13',
		'role_id'   => '8',
		'divider'   => '1',
		'enabled'   => '1',
	),
	array(
		'name'      => 'vehicles',
		'parent_id' => NULL,
		'title'     => 'Vehicles',
		'route'     => 'vehicle.index',
		'attrs'     => '{"icon": "fad fa-cars"}',
		'level'     => '14',
		'role_id'   => '8',
		'divider'   => '0',
		'enabled'   => '1',
	),
	array(
		'name'      => 'machines',
		'parent_id' => NULL,
		'title'     => 'Machines',
		'route'     => 'machine.index',
		'attrs'     => '{"icon": "fad fa-robot"}',
		'level'     => '15',
		'role_id'   => '8',
		'divider'   => '0',
		'enabled'   => '1',
	),
	array(
		'name'      => NULL,
		'parent_id' => NULL,
		'title'     => NULL,
		'route'     => NULL,
		'attrs'     => NULL,
		'level'     => '16',
		'role_id'   => '8',
		'divider'   => '1',
		'enabled'   => '1',
	),
	array(
		'name'      => 'reports',
		'parent_id' => NULL,
		'title'     => 'Reports',
		'route'     => NULL,
		'attrs'     => '{"icon": "fad fa-file-chart-line"}',
		'level'     => '17',
		'role_id'   => '8',
		'divider'   => '0',
		'enabled'   => '1',
		'children'  => [
			array(
				'name'      => 'attendance-report',
				'parent_id' => NULL,
				'title'     => 'Attendance',
				'route'     => 'report.attendance',
				'attrs'     => '{"icon": "fad fa-calendar-check"}',
				'level'     => '1',
				'role_id'   => '8',
				'divider'   => '0',
				'enabled'   => '1',
			),
			array(
				'name'      => 'sales-report',
				'parent_id' => NULL,
				'title'     => 'Sales',
				'route'     => NULL,
				'attrs'     => '{"icon": "fad fa-file-signature"}',
				'level'     => '1',
				'role_id'   => '8',
				'divider'   => '0',
				'enabled'   => '1',
			),
			array(
				'name'      => 'service-report',
				'parent_id' => NULL,
				'title'     => 'Services',
				'route'     => NULL,
				'attrs'     => '{"icon": "fad fa-file-check"}',
				'level'     => '2',
				'role_id'   => '8',
				'divider'   => '0',
				'enabled'   => '1',
			),
			array(
				'name'      => 'salary',
				'parent_id' => NULL,
				'title'     => 'Salaries',
				'route'     => 'report.salary',
				'attrs'     => '{"icon": "fad fa-money-check-alt"}',
				'level'     => '2',
				'role_id'   => '8',
				'divider'   => '0',
				'enabled'   => '1',
			),
		],
	),
	array(
		'name'      => NULL,
		'parent_id' => NULL,
		'title'     => NULL,
		'route'     => NULL,
		'attrs'     => NULL,
		'level'     => '18',
		'role_id'   => '8',
		'divider'   => '1',
		'enabled'   => '1',
	),
	array(
		'name'      => 'audit-trail',
		'parent_id' => NULL,
		'title'     => 'Audit Trail',
		'route'     => 'audit.index',
		'attrs'     => '{"icon": "fad fa-history"}',
		'level'     => '19',
		'role_id'   => '8',
		'divider'   => '0',
		'enabled'   => '1',
	),
	array(
		'name'      => NULL,
		'parent_id' => NULL,
		'title'     => NULL,
		'route'     => NULL,
		'attrs'     => NULL,
		'level'     => '20',
		'role_id'   => '8',
		'divider'   => '1',
		'enabled'   => '1',
	),
	array(
		'name'      => 'users',
		'parent_id' => NULL,
		'title'     => 'Users',
		'route'     => 'user.index',
		'attrs'     => '{"icon": "fad fa-users"}',
		'level'     => '21',
		'role_id'   => '8',
		'divider'   => '0',
		'enabled'   => '1',
	),
	array(
		'name'      => NULL,
		'parent_id' => NULL,
		'title'     => NULL,
		'route'     => NULL,
		'attrs'     => NULL,
		'level'     => '22',
		'role_id'   => '8',
		'divider'   => '1',
		'enabled'   => '1',
	),
	array(
		'name'      => 'settings',
		'parent_id' => NULL,
		'title'     => 'Settings',
		'route'     => NULL,
		'attrs'     => '{"icon": "fad fa-cogs"}',
		'level'     => '23',
		'role_id'   => '2',
		'divider'   => '0',
		'enabled'   => '1',
		'children'  => [
			array(
				'name'      => 'calendar',
				'parent_id' => NULL,
				'title'     => 'Calendar',
				'route'     => 'settings.calendar.index',
				'attrs'     => '{"icon": "fad fa-calendar-alt"}',
				'level'     => '1',
				'role_id'   => '8',
				'divider'   => '0',
				'enabled'   => '1',
			),
			array(
				'name'      => 'job-title',
				'parent_id' => NULL,
				'title'     => 'Job Titles',
				'route'     => NULL,
				'attrs'     => '{"icon": "fad fa-id-card"}',
				'level'     => '2',
				'role_id'   => '8',
				'divider'   => '0',
				'enabled'   => '1',
			),
			array(
				'name'      => 'working-shift',
				'parent_id' => NULL,
				'title'     => 'Working Shift',
				'route'     => 'workingshift.index',
				'attrs'     => '{"icon": "fad fa-id-card"}',
				'level'     => '3',
				'role_id'   => '8',
				'divider'   => '0',
				'enabled'   => '1',
			),
			array(
				'name'      => 'att-device',
				'parent_id' => NULL,
				'title'     => 'Attendance',
				'route'     => 'settings.attendance.show',
				'attrs'     => '{"icon": "fad fa-id-badge"}',
				'level'     => '4',
				'role_id'   => '8',
				'divider'   => '0',
				'enabled'   => '1',
			),
			array(
				'name'     => 'locations',
				'title'    => 'Locations',
				'route'    => NULL,
				'attrs'    => '{"icon": "fad fa-atlas"}',
				'level'    => '5',
				'role_id'  => '8',
				'divider'  => '0',
				'enabled'  => '1',
				'children' => [
					array(
						'name'    => 'countries',
						'title'   => 'Countries',
						'route'   => NULL,
						'attrs'   => '{"icon": "fad fa-flag-alt"}',
						'level'   => '1',
						'role_id' => '8',
						'divider' => '0',
						'enabled' => '1',
					),
					array(
						'name'    => 'provinces',
						'title'   => 'Provinces',
						'route'   => NULL,
						'attrs'   => NULL,
						'level'   => '2',
						'role_id' => '8',
						'divider' => '0',
						'enabled' => '1',
					),
					array(
						'name'    => 'cities',
						'title'   => 'Cities',
						'route'   => NULL,
						'attrs'   => NULL,
						'level'   => '3',
						'role_id' => '8',
						'divider' => '0',
						'enabled' => '1',
					),
					array(
						'name'    => 'districts',
						'title'   => 'Districts',
						'route'   => NULL,
						'attrs'   => NULL,
						'level'   => '4',
						'role_id' => '8',
						'divider' => '0',
						'enabled' => '1',
					),
					array(
						'name'    => 'villages',
						'title'   => 'Villages',
						'route'   => NULL,
						'attrs'   => NULL,
						'level'   => '5',
						'role_id' => '8',
						'divider' => '0',
						'enabled' => '1',
					),
				],
			),
            array(
                'name'      => 'fingerprintdevice',
                'title'     => 'Fingerprint Devices',
                'route'     => 'fingerprintdevice.index',
                'attrs'     => '{"icon": "fad fa-fingerprint"}',
                'level'     => '1',
                'role_id'   => '2',
                'divider'   => '0',
                'enabled'   => '1'
            )
		],
	),
);
