@extends('falcon::layouts.base')

@section('content')
	<x-bootstrap::row>
		<x-bootstrap::column>
			<x-bootstrap::card>
				<x-bootstrap::card.header>
					<x-bootstrap::row class="align-items-baseline justify-content-between">
						<x-bootstrap::column class="d-flex flex-column align-items-baseline">
							<h5 class="fs-2 font-weight-semi-bold mb-0 text-nunito py-2 py-xl-0 text-truncate w-100 text-truncate">
								{{ $model->type()->getShortname() }}<br />
								<small class="fs-0 text-muted d-block">Audit</small>
							</h5>
						</x-bootstrap::column>
					</x-bootstrap::row>
				</x-bootstrap::card.header>
				<x-bootstrap::card.body class="bg-light">
					<x-bootstrap::row class="mb-4">
						<x-bootstrap::column breakpoint="MEDIUM|8">
							<div class="row-info">
								<x-bootstrap::media header-size="0" title="Responsible" />
								<x-bootstrap::row>
									<x-bootstrap::column breakpoint="MEDIUM|3" class="col-label"><span id="name" class="form-control-plaintext">User</span></x-bootstrap::column>
									<x-bootstrap::column>
										<span id="name" class="form-control-plaintext text-1000 fs-0">
											@if($model->user_id)
											<a href="{{ route('user.show', ['user' => safe_call($model, 'getUser.username')]) }}">{{ safe_call($model, 'getUser.username') }}</a>
											@else
											<span class="text-success">Generated by system</span>
											@endif
										</span>
									</x-bootstrap::column>
								</x-bootstrap::row>
								<x-bootstrap::row>
									<x-bootstrap::column breakpoint="MEDIUM|3" class="col-label"><span id="name" class="form-control-plaintext">Roles</span></x-bootstrap::column>
									<x-bootstrap::column>
										<span id="name" class="form-control-plaintext text-1000 fs-0">{{ $model->getUser()?->getRoleNames()->join(', ') }}</span>
									</x-bootstrap::column>
								</x-bootstrap::row>
								<x-bootstrap::row>
									<x-bootstrap::column breakpoint="MEDIUM|3" class="col-label"><span id="name" class="form-control-plaintext">Event</span></x-bootstrap::column>
									<x-bootstrap::column><span id="name" class="form-control-plaintext text-1000 fs-0">{{ $model->event }}</span></x-bootstrap::column>
								</x-bootstrap::row>
								<x-bootstrap::row>
									<x-bootstrap::column breakpoint="MEDIUM|3" class="col-label"><span id="name" class="form-control-plaintext">Model</span></x-bootstrap::column>
									@php
										$type = new ReflectionClass($model->auditable_type);
									@endphp
									<x-bootstrap::column><span id="name" class="form-control-plaintext text-1000 fs-0">{{ $type->getShortName() }}</span></x-bootstrap::column>
								</x-bootstrap::row>
								<x-bootstrap::row>
									<x-bootstrap::column breakpoint="MEDIUM|3" class="col-label"><span id="name" class="form-control-plaintext">At</span></x-bootstrap::column>
									<x-bootstrap::column><span id="name" class="form-control-plaintext text-1000 fs-0">{{ \App\Libraries\PrettyDateTime::parseString($model->created_at) }}</span></x-bootstrap::column>
								</x-bootstrap::row>
							</div>
						</x-bootstrap::column>
					</x-bootstrap::row>
					<x-bootstrap::media header-size="0" title="Fields" class="mb-4 mt-5" />
					<x-bootstrap::row>
						<x-bootstrap::column>
							@php
								$fields = collect([]);
								$model->old_values->__toCollection()->each(function($value, $key) use(&$fields) {
									if ($fields->search($key) === false) {
										$fields->add($key);
									}
								});
								$model->new_values->__toCollection()->each(function($value, $key) use(&$fields) {
									if ($fields->search($key) === false) {
										$fields->add($key);
									}
								});
							@endphp
							<table class="table table-hover bg-white table-striped">
								<thead class="thead-dark">
								<tr>
									<th class="va-baseline text-center fs-0" style="width: 100px">No.</th>
									<th class="va-baseline fs-0">Field</th>
									<th class="va-baseline fs-0">Old Value</th>
									<th class="va-baseline fs-0">New Value</th>
								</tr>
								</thead>
								<tbody>
								@foreach($fields->toArray() as $field)
									<tr>
										<td class="va-baseline text-center fs-0" style="width: 100px">{{ $loop->index + 1 }}</td>
										<td class="va-baseline fs-0">{{ $field }}</td>
										<td class="va-baseline fs-0">
											@if(Str::contains($field, ['password', 'passwd', 'pass', 'token', 'secret']))
												<span class="text-muted">&mdash; This value is hidden &mdash;</span>
											@else
												{{ $model->old_values->__toCollection()->get($field) }}
											@endif
										</td>
										<td class="va-baseline fs-0">
											@if(Str::contains($field, ['password', 'passwd', 'pass', 'token', 'secret']))
												<span class="text-muted">&mdash; This value is hidden &mdash;</span>
											@else
												{{ $model->new_values->__toCollection()->get($field) }}
											@endif
										</td>
									</tr>
								@endforeach
								</tbody>
							</table>
						</x-bootstrap::column>
					</x-bootstrap::row>
				</x-bootstrap::card.body>
			</x-bootstrap::card>
		</x-bootstrap::column>
	</x-bootstrap::row>
@endsection
