<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.0.2
 */

/**
 * Database `IndonesiaAdministrative`
 */

/* `IndonesiaAdministrative`.`administrative_2` */
return array(
  array('id' => '1','code' => 'ID1101','name' => 'Simeulue','country_id' => 'ID','state_code' => 'AC','adm1_code' => 'ID11','adm1_id' => '1'),
  array('id' => '2','code' => 'ID1102','name' => 'Aceh Singkil','country_id' => 'ID','state_code' => 'AC','adm1_code' => 'ID11','adm1_id' => '1'),
  array('id' => '3','code' => 'ID1103','name' => 'Aceh Selatan','country_id' => 'ID','state_code' => 'AC','adm1_code' => 'ID11','adm1_id' => '1'),
  array('id' => '4','code' => 'ID1104','name' => 'Aceh Tenggara','country_id' => 'ID','state_code' => 'AC','adm1_code' => 'ID11','adm1_id' => '1'),
  array('id' => '5','code' => 'ID1105','name' => 'Aceh Timur','country_id' => 'ID','state_code' => 'AC','adm1_code' => 'ID11','adm1_id' => '1'),
  array('id' => '6','code' => 'ID1106','name' => 'Aceh Tengah','country_id' => 'ID','state_code' => 'AC','adm1_code' => 'ID11','adm1_id' => '1'),
  array('id' => '7','code' => 'ID1107','name' => 'Aceh Barat','country_id' => 'ID','state_code' => 'AC','adm1_code' => 'ID11','adm1_id' => '1'),
  array('id' => '8','code' => 'ID1108','name' => 'Aceh Besar','country_id' => 'ID','state_code' => 'AC','adm1_code' => 'ID11','adm1_id' => '1'),
  array('id' => '9','code' => 'ID1109','name' => 'Pidie','country_id' => 'ID','state_code' => 'AC','adm1_code' => 'ID11','adm1_id' => '1'),
  array('id' => '10','code' => 'ID1110','name' => 'Bireuen','country_id' => 'ID','state_code' => 'AC','adm1_code' => 'ID11','adm1_id' => '1'),
  array('id' => '11','code' => 'ID1111','name' => 'Aceh Utara','country_id' => 'ID','state_code' => 'AC','adm1_code' => 'ID11','adm1_id' => '1'),
  array('id' => '12','code' => 'ID1112','name' => 'Aceh Barat Daya','country_id' => 'ID','state_code' => 'AC','adm1_code' => 'ID11','adm1_id' => '1'),
  array('id' => '13','code' => 'ID1113','name' => 'Gayo Lues','country_id' => 'ID','state_code' => 'AC','adm1_code' => 'ID11','adm1_id' => '1'),
  array('id' => '14','code' => 'ID1114','name' => 'Aceh Tamiang','country_id' => 'ID','state_code' => 'AC','adm1_code' => 'ID11','adm1_id' => '1'),
  array('id' => '15','code' => 'ID1115','name' => 'Nagan Raya','country_id' => 'ID','state_code' => 'AC','adm1_code' => 'ID11','adm1_id' => '1'),
  array('id' => '16','code' => 'ID1116','name' => 'Aceh Jaya','country_id' => 'ID','state_code' => 'AC','adm1_code' => 'ID11','adm1_id' => '1'),
  array('id' => '17','code' => 'ID1117','name' => 'Bener Meriah','country_id' => 'ID','state_code' => 'AC','adm1_code' => 'ID11','adm1_id' => '1'),
  array('id' => '18','code' => 'ID1118','name' => 'Pidie Jaya','country_id' => 'ID','state_code' => 'AC','adm1_code' => 'ID11','adm1_id' => '1'),
  array('id' => '19','code' => 'ID1171','name' => 'Kota Banda Aceh','country_id' => 'ID','state_code' => 'AC','adm1_code' => 'ID11','adm1_id' => '1'),
  array('id' => '20','code' => 'ID1172','name' => 'Kota Sabang','country_id' => 'ID','state_code' => 'AC','adm1_code' => 'ID11','adm1_id' => '1'),
  array('id' => '21','code' => 'ID1173','name' => 'Kota Langsa','country_id' => 'ID','state_code' => 'AC','adm1_code' => 'ID11','adm1_id' => '1'),
  array('id' => '22','code' => 'ID1174','name' => 'Kota Lhokseumawe','country_id' => 'ID','state_code' => 'AC','adm1_code' => 'ID11','adm1_id' => '1'),
  array('id' => '23','code' => 'ID1175','name' => 'Kota Subulussalam','country_id' => 'ID','state_code' => 'AC','adm1_code' => 'ID11','adm1_id' => '1'),
  array('id' => '24','code' => 'ID1201','name' => 'Nias','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '25','code' => 'ID1202','name' => 'Mandailing Natal','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '26','code' => 'ID1203','name' => 'Tapanuli Selatan','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '27','code' => 'ID1204','name' => 'Tapanuli Tengah','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '28','code' => 'ID1205','name' => 'Tapanuli Utara','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '29','code' => 'ID1206','name' => 'Toba Samosir','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '30','code' => 'ID1207','name' => 'Labuhan Batu','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '31','code' => 'ID1208','name' => 'Asahan','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '32','code' => 'ID1209','name' => 'Simalungun','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '33','code' => 'ID1210','name' => 'Dairi','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '34','code' => 'ID1211','name' => 'Karo','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '35','code' => 'ID1212','name' => 'Deli Serdang','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '36','code' => 'ID1213','name' => 'Langkat','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '37','code' => 'ID1214','name' => 'Nias Selatan','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '38','code' => 'ID1215','name' => 'Humbang Hasundutan','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '39','code' => 'ID1216','name' => 'Pakpak Bharat','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '40','code' => 'ID1217','name' => 'Samosir','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '41','code' => 'ID1218','name' => 'Serdang Bedagai','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '42','code' => 'ID1219','name' => 'Batu Bara','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '43','code' => 'ID1220','name' => 'Padang Lawas Utara','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '44','code' => 'ID1221','name' => 'Padang Lawas','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '45','code' => 'ID1222','name' => 'Labuhan Batu Selatan','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '46','code' => 'ID1223','name' => 'Labuhan Batu Utara','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '47','code' => 'ID1224','name' => 'Nias Utara','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '48','code' => 'ID1225','name' => 'Nias Barat','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '49','code' => 'ID1271','name' => 'Kota Sibolga','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '50','code' => 'ID1272','name' => 'Kota Tanjung Balai','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '51','code' => 'ID1273','name' => 'Kota Pematang Siantar','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '52','code' => 'ID1274','name' => 'Kota Tebing Tinggi','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '53','code' => 'ID1275','name' => 'Kota Medan','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '54','code' => 'ID1276','name' => 'Kota Binjai','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '55','code' => 'ID1277','name' => 'Kota Padangsidimpuan','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '56','code' => 'ID1278','name' => 'Kota Gunungsitoli','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '57','code' => 'ID1288','name' => 'Danau Toba','country_id' => 'ID','state_code' => 'SU','adm1_code' => 'ID12','adm1_id' => '2'),
  array('id' => '58','code' => 'ID1301','name' => 'Kepulauan Mentawai','country_id' => 'ID','state_code' => 'SB','adm1_code' => 'ID13','adm1_id' => '3'),
  array('id' => '59','code' => 'ID1302','name' => 'Pesisir Selatan','country_id' => 'ID','state_code' => 'SB','adm1_code' => 'ID13','adm1_id' => '3'),
  array('id' => '60','code' => 'ID1303','name' => 'Solok','country_id' => 'ID','state_code' => 'SB','adm1_code' => 'ID13','adm1_id' => '3'),
  array('id' => '61','code' => 'ID1304','name' => 'Sijunjung','country_id' => 'ID','state_code' => 'SB','adm1_code' => 'ID13','adm1_id' => '3'),
  array('id' => '62','code' => 'ID1305','name' => 'Tanah Datar','country_id' => 'ID','state_code' => 'SB','adm1_code' => 'ID13','adm1_id' => '3'),
  array('id' => '63','code' => 'ID1306','name' => 'Padang Pariaman','country_id' => 'ID','state_code' => 'SB','adm1_code' => 'ID13','adm1_id' => '3'),
  array('id' => '64','code' => 'ID1307','name' => 'Agam','country_id' => 'ID','state_code' => 'SB','adm1_code' => 'ID13','adm1_id' => '3'),
  array('id' => '65','code' => 'ID1308','name' => 'Lima Puluh Kota','country_id' => 'ID','state_code' => 'SB','adm1_code' => 'ID13','adm1_id' => '3'),
  array('id' => '66','code' => 'ID1309','name' => 'Pasaman','country_id' => 'ID','state_code' => 'SB','adm1_code' => 'ID13','adm1_id' => '3'),
  array('id' => '67','code' => 'ID1310','name' => 'Solok Selatan','country_id' => 'ID','state_code' => 'SB','adm1_code' => 'ID13','adm1_id' => '3'),
  array('id' => '68','code' => 'ID1311','name' => 'Dharmasraya','country_id' => 'ID','state_code' => 'SB','adm1_code' => 'ID13','adm1_id' => '3'),
  array('id' => '69','code' => 'ID1312','name' => 'Pasaman Barat','country_id' => 'ID','state_code' => 'SB','adm1_code' => 'ID13','adm1_id' => '3'),
  array('id' => '70','code' => 'ID1371','name' => 'Kota Padang','country_id' => 'ID','state_code' => 'SB','adm1_code' => 'ID13','adm1_id' => '3'),
  array('id' => '71','code' => 'ID1372','name' => 'Kota Solok','country_id' => 'ID','state_code' => 'SB','adm1_code' => 'ID13','adm1_id' => '3'),
  array('id' => '72','code' => 'ID1373','name' => 'Kota Sawah Lunto','country_id' => 'ID','state_code' => 'SB','adm1_code' => 'ID13','adm1_id' => '3'),
  array('id' => '73','code' => 'ID1374','name' => 'Kota Padang Panjang','country_id' => 'ID','state_code' => 'SB','adm1_code' => 'ID13','adm1_id' => '3'),
  array('id' => '74','code' => 'ID1375','name' => 'Kota Bukittinggi','country_id' => 'ID','state_code' => 'SB','adm1_code' => 'ID13','adm1_id' => '3'),
  array('id' => '75','code' => 'ID1376','name' => 'Kota Payakumbuh','country_id' => 'ID','state_code' => 'SB','adm1_code' => 'ID13','adm1_id' => '3'),
  array('id' => '76','code' => 'ID1377','name' => 'Kota Pariaman','country_id' => 'ID','state_code' => 'SB','adm1_code' => 'ID13','adm1_id' => '3'),
  array('id' => '77','code' => 'ID1388','name' => 'Danau','country_id' => 'ID','state_code' => 'SB','adm1_code' => 'ID13','adm1_id' => '3'),
  array('id' => '78','code' => 'ID1401','name' => 'Kuantan Singingi','country_id' => 'ID','state_code' => 'RI','adm1_code' => 'ID14','adm1_id' => '4'),
  array('id' => '79','code' => 'ID1402','name' => 'Indragiri Hulu','country_id' => 'ID','state_code' => 'RI','adm1_code' => 'ID14','adm1_id' => '4'),
  array('id' => '80','code' => 'ID1403','name' => 'Indragiri Hilir','country_id' => 'ID','state_code' => 'RI','adm1_code' => 'ID14','adm1_id' => '4'),
  array('id' => '81','code' => 'ID1404','name' => 'Pelalawan','country_id' => 'ID','state_code' => 'RI','adm1_code' => 'ID14','adm1_id' => '4'),
  array('id' => '82','code' => 'ID1405','name' => 'Siak','country_id' => 'ID','state_code' => 'RI','adm1_code' => 'ID14','adm1_id' => '4'),
  array('id' => '83','code' => 'ID1406','name' => 'Kampar','country_id' => 'ID','state_code' => 'RI','adm1_code' => 'ID14','adm1_id' => '4'),
  array('id' => '84','code' => 'ID1407','name' => 'Rokan Hulu','country_id' => 'ID','state_code' => 'RI','adm1_code' => 'ID14','adm1_id' => '4'),
  array('id' => '85','code' => 'ID1408','name' => 'Bengkalis','country_id' => 'ID','state_code' => 'RI','adm1_code' => 'ID14','adm1_id' => '4'),
  array('id' => '86','code' => 'ID1409','name' => 'Rokan Hilir','country_id' => 'ID','state_code' => 'RI','adm1_code' => 'ID14','adm1_id' => '4'),
  array('id' => '87','code' => 'ID1410','name' => 'Kepulauan Meranti','country_id' => 'ID','state_code' => 'RI','adm1_code' => 'ID14','adm1_id' => '4'),
  array('id' => '88','code' => 'ID1471','name' => 'Kota Pekanbaru','country_id' => 'ID','state_code' => 'RI','adm1_code' => 'ID14','adm1_id' => '4'),
  array('id' => '89','code' => 'ID1473','name' => 'Kota Dumai','country_id' => 'ID','state_code' => 'RI','adm1_code' => 'ID14','adm1_id' => '4'),
  array('id' => '90','code' => 'ID1501','name' => 'Kerinci','country_id' => 'ID','state_code' => 'JA','adm1_code' => 'ID15','adm1_id' => '5'),
  array('id' => '91','code' => 'ID1502','name' => 'Merangin','country_id' => 'ID','state_code' => 'JA','adm1_code' => 'ID15','adm1_id' => '5'),
  array('id' => '92','code' => 'ID1503','name' => 'Sarolangun','country_id' => 'ID','state_code' => 'JA','adm1_code' => 'ID15','adm1_id' => '5'),
  array('id' => '93','code' => 'ID1504','name' => 'Batang Hari','country_id' => 'ID','state_code' => 'JA','adm1_code' => 'ID15','adm1_id' => '5'),
  array('id' => '94','code' => 'ID1505','name' => 'Muaro Jambi','country_id' => 'ID','state_code' => 'JA','adm1_code' => 'ID15','adm1_id' => '5'),
  array('id' => '95','code' => 'ID1506','name' => 'Tanjung Jabung Timur','country_id' => 'ID','state_code' => 'JA','adm1_code' => 'ID15','adm1_id' => '5'),
  array('id' => '96','code' => 'ID1507','name' => 'Tanjung Jabung Barat','country_id' => 'ID','state_code' => 'JA','adm1_code' => 'ID15','adm1_id' => '5'),
  array('id' => '97','code' => 'ID1508','name' => 'Tebo','country_id' => 'ID','state_code' => 'JA','adm1_code' => 'ID15','adm1_id' => '5'),
  array('id' => '98','code' => 'ID1509','name' => 'Bungo','country_id' => 'ID','state_code' => 'JA','adm1_code' => 'ID15','adm1_id' => '5'),
  array('id' => '99','code' => 'ID1571','name' => 'Kota Jambi','country_id' => 'ID','state_code' => 'JA','adm1_code' => 'ID15','adm1_id' => '5'),
  array('id' => '100','code' => 'ID1572','name' => 'Kota Sungai Penuh','country_id' => 'ID','state_code' => 'JA','adm1_code' => 'ID15','adm1_id' => '5'),
  array('id' => '101','code' => 'ID1601','name' => 'Ogan Komering Ulu','country_id' => 'ID','state_code' => 'SS','adm1_code' => 'ID16','adm1_id' => '6'),
  array('id' => '102','code' => 'ID1602','name' => 'Ogan Komering Ilir','country_id' => 'ID','state_code' => 'SS','adm1_code' => 'ID16','adm1_id' => '6'),
  array('id' => '103','code' => 'ID1603','name' => 'Muara Enim','country_id' => 'ID','state_code' => 'SS','adm1_code' => 'ID16','adm1_id' => '6'),
  array('id' => '104','code' => 'ID1604','name' => 'Lahat','country_id' => 'ID','state_code' => 'SS','adm1_code' => 'ID16','adm1_id' => '6'),
  array('id' => '105','code' => 'ID1605','name' => 'Musi Rawas','country_id' => 'ID','state_code' => 'SS','adm1_code' => 'ID16','adm1_id' => '6'),
  array('id' => '106','code' => 'ID1606','name' => 'Musi Banyuasin','country_id' => 'ID','state_code' => 'SS','adm1_code' => 'ID16','adm1_id' => '6'),
  array('id' => '107','code' => 'ID1607','name' => 'Banyu Asin','country_id' => 'ID','state_code' => 'SS','adm1_code' => 'ID16','adm1_id' => '6'),
  array('id' => '108','code' => 'ID1608','name' => 'Ogan Komering Ulu Selatan','country_id' => 'ID','state_code' => 'SS','adm1_code' => 'ID16','adm1_id' => '6'),
  array('id' => '109','code' => 'ID1609','name' => 'Ogan Komering Ulu Timur','country_id' => 'ID','state_code' => 'SS','adm1_code' => 'ID16','adm1_id' => '6'),
  array('id' => '110','code' => 'ID1610','name' => 'Ogan Ilir','country_id' => 'ID','state_code' => 'SS','adm1_code' => 'ID16','adm1_id' => '6'),
  array('id' => '111','code' => 'ID1611','name' => 'Empat Lawang','country_id' => 'ID','state_code' => 'SS','adm1_code' => 'ID16','adm1_id' => '6'),
  array('id' => '112','code' => 'ID1612','name' => 'Penukal Abab Lematang Ilir','country_id' => 'ID','state_code' => 'SS','adm1_code' => 'ID16','adm1_id' => '6'),
  array('id' => '113','code' => 'ID1613','name' => 'Musi Rawas Utara','country_id' => 'ID','state_code' => 'SS','adm1_code' => 'ID16','adm1_id' => '6'),
  array('id' => '114','code' => 'ID1671','name' => 'Kota Palembang','country_id' => 'ID','state_code' => 'SS','adm1_code' => 'ID16','adm1_id' => '6'),
  array('id' => '115','code' => 'ID1672','name' => 'Kota Prabumulih','country_id' => 'ID','state_code' => 'SS','adm1_code' => 'ID16','adm1_id' => '6'),
  array('id' => '116','code' => 'ID1673','name' => 'Kota Pagar Alam','country_id' => 'ID','state_code' => 'SS','adm1_code' => 'ID16','adm1_id' => '6'),
  array('id' => '117','code' => 'ID1674','name' => 'Kota Lubuklinggau','country_id' => 'ID','state_code' => 'SS','adm1_code' => 'ID16','adm1_id' => '6'),
  array('id' => '118','code' => 'ID1688','name' => 'Danau','country_id' => 'ID','state_code' => 'SS','adm1_code' => 'ID16','adm1_id' => '6'),
  array('id' => '119','code' => 'ID1701','name' => 'Bengkulu Selatan','country_id' => 'ID','state_code' => 'BE','adm1_code' => 'ID17','adm1_id' => '7'),
  array('id' => '120','code' => 'ID1702','name' => 'Rejang Lebong','country_id' => 'ID','state_code' => 'BE','adm1_code' => 'ID17','adm1_id' => '7'),
  array('id' => '121','code' => 'ID1703','name' => 'Bengkulu Utara','country_id' => 'ID','state_code' => 'BE','adm1_code' => 'ID17','adm1_id' => '7'),
  array('id' => '122','code' => 'ID1704','name' => 'Kaur','country_id' => 'ID','state_code' => 'BE','adm1_code' => 'ID17','adm1_id' => '7'),
  array('id' => '123','code' => 'ID1705','name' => 'Seluma','country_id' => 'ID','state_code' => 'BE','adm1_code' => 'ID17','adm1_id' => '7'),
  array('id' => '124','code' => 'ID1706','name' => 'Mukomuko','country_id' => 'ID','state_code' => 'BE','adm1_code' => 'ID17','adm1_id' => '7'),
  array('id' => '125','code' => 'ID1707','name' => 'Lebong','country_id' => 'ID','state_code' => 'BE','adm1_code' => 'ID17','adm1_id' => '7'),
  array('id' => '126','code' => 'ID1708','name' => 'Kepahiang','country_id' => 'ID','state_code' => 'BE','adm1_code' => 'ID17','adm1_id' => '7'),
  array('id' => '127','code' => 'ID1709','name' => 'Bengkulu Tengah','country_id' => 'ID','state_code' => 'BE','adm1_code' => 'ID17','adm1_id' => '7'),
  array('id' => '128','code' => 'ID1771','name' => 'Kota Bengkulu','country_id' => 'ID','state_code' => 'BE','adm1_code' => 'ID17','adm1_id' => '7'),
  array('id' => '129','code' => 'ID1801','name' => 'Lampung Barat','country_id' => 'ID','state_code' => 'LA','adm1_code' => 'ID18','adm1_id' => '8'),
  array('id' => '130','code' => 'ID1802','name' => 'Tanggamus','country_id' => 'ID','state_code' => 'LA','adm1_code' => 'ID18','adm1_id' => '8'),
  array('id' => '131','code' => 'ID1803','name' => 'Lampung Selatan','country_id' => 'ID','state_code' => 'LA','adm1_code' => 'ID18','adm1_id' => '8'),
  array('id' => '132','code' => 'ID1804','name' => 'Lampung Timur','country_id' => 'ID','state_code' => 'LA','adm1_code' => 'ID18','adm1_id' => '8'),
  array('id' => '133','code' => 'ID1805','name' => 'Lampung Tengah','country_id' => 'ID','state_code' => 'LA','adm1_code' => 'ID18','adm1_id' => '8'),
  array('id' => '134','code' => 'ID1806','name' => 'Lampung Utara','country_id' => 'ID','state_code' => 'LA','adm1_code' => 'ID18','adm1_id' => '8'),
  array('id' => '135','code' => 'ID1807','name' => 'Way Kanan','country_id' => 'ID','state_code' => 'LA','adm1_code' => 'ID18','adm1_id' => '8'),
  array('id' => '136','code' => 'ID1808','name' => 'Tulangbawang','country_id' => 'ID','state_code' => 'LA','adm1_code' => 'ID18','adm1_id' => '8'),
  array('id' => '137','code' => 'ID1809','name' => 'Pesawaran','country_id' => 'ID','state_code' => 'LA','adm1_code' => 'ID18','adm1_id' => '8'),
  array('id' => '138','code' => 'ID1810','name' => 'Pringsewu','country_id' => 'ID','state_code' => 'LA','adm1_code' => 'ID18','adm1_id' => '8'),
  array('id' => '139','code' => 'ID1811','name' => 'Mesuji','country_id' => 'ID','state_code' => 'LA','adm1_code' => 'ID18','adm1_id' => '8'),
  array('id' => '140','code' => 'ID1812','name' => 'Tulang Bawang Barat','country_id' => 'ID','state_code' => 'LA','adm1_code' => 'ID18','adm1_id' => '8'),
  array('id' => '141','code' => 'ID1813','name' => 'Pesisir Barat','country_id' => 'ID','state_code' => 'LA','adm1_code' => 'ID18','adm1_id' => '8'),
  array('id' => '142','code' => 'ID1871','name' => 'Kota Bandar Lampung','country_id' => 'ID','state_code' => 'LA','adm1_code' => 'ID18','adm1_id' => '8'),
  array('id' => '143','code' => 'ID1872','name' => 'Kota Metro','country_id' => 'ID','state_code' => 'LA','adm1_code' => 'ID18','adm1_id' => '8'),
  array('id' => '144','code' => 'ID1888','name' => 'Danau','country_id' => 'ID','state_code' => 'LA','adm1_code' => 'ID18','adm1_id' => '8'),
  array('id' => '145','code' => 'ID1901','name' => 'Bangka','country_id' => 'ID','state_code' => 'BB','adm1_code' => 'ID19','adm1_id' => '9'),
  array('id' => '146','code' => 'ID1902','name' => 'Belitung','country_id' => 'ID','state_code' => 'BB','adm1_code' => 'ID19','adm1_id' => '9'),
  array('id' => '147','code' => 'ID1903','name' => 'Bangka Barat','country_id' => 'ID','state_code' => 'BB','adm1_code' => 'ID19','adm1_id' => '9'),
  array('id' => '148','code' => 'ID1904','name' => 'Bangka Tengah','country_id' => 'ID','state_code' => 'BB','adm1_code' => 'ID19','adm1_id' => '9'),
  array('id' => '149','code' => 'ID1905','name' => 'Bangka Selatan','country_id' => 'ID','state_code' => 'BB','adm1_code' => 'ID19','adm1_id' => '9'),
  array('id' => '150','code' => 'ID1906','name' => 'Belitung Timur','country_id' => 'ID','state_code' => 'BB','adm1_code' => 'ID19','adm1_id' => '9'),
  array('id' => '151','code' => 'ID1971','name' => 'Kota Pangkal Pinang','country_id' => 'ID','state_code' => 'BB','adm1_code' => 'ID19','adm1_id' => '9'),
  array('id' => '152','code' => 'ID2101','name' => 'Karimun','country_id' => 'ID','state_code' => 'KR','adm1_code' => 'ID21','adm1_id' => '10'),
  array('id' => '153','code' => 'ID2102','name' => 'Bintan','country_id' => 'ID','state_code' => 'KR','adm1_code' => 'ID21','adm1_id' => '10'),
  array('id' => '154','code' => 'ID2103','name' => 'Natuna','country_id' => 'ID','state_code' => 'KR','adm1_code' => 'ID21','adm1_id' => '10'),
  array('id' => '155','code' => 'ID2104','name' => 'Lingga','country_id' => 'ID','state_code' => 'KR','adm1_code' => 'ID21','adm1_id' => '10'),
  array('id' => '156','code' => 'ID2105','name' => 'Kepulauan Anambas','country_id' => 'ID','state_code' => 'KR','adm1_code' => 'ID21','adm1_id' => '10'),
  array('id' => '157','code' => 'ID2171','name' => 'Kota Batam','country_id' => 'ID','state_code' => 'KR','adm1_code' => 'ID21','adm1_id' => '10'),
  array('id' => '158','code' => 'ID2172','name' => 'Kota Tanjung Pinang','country_id' => 'ID','state_code' => 'KR','adm1_code' => 'ID21','adm1_id' => '10'),
  array('id' => '159','code' => 'ID3101','name' => 'Kepulauan Seribu','country_id' => 'ID','state_code' => 'JK','adm1_code' => 'ID31','adm1_id' => '11'),
  array('id' => '160','code' => 'ID3171','name' => 'Kota Jakarta Selatan','country_id' => 'ID','state_code' => 'JK','adm1_code' => 'ID31','adm1_id' => '11'),
  array('id' => '161','code' => 'ID3172','name' => 'Kota Jakarta Timur','country_id' => 'ID','state_code' => 'JK','adm1_code' => 'ID31','adm1_id' => '11'),
  array('id' => '162','code' => 'ID3173','name' => 'Kota Jakarta Pusat','country_id' => 'ID','state_code' => 'JK','adm1_code' => 'ID31','adm1_id' => '11'),
  array('id' => '163','code' => 'ID3174','name' => 'Kota Jakarta Barat','country_id' => 'ID','state_code' => 'JK','adm1_code' => 'ID31','adm1_id' => '11'),
  array('id' => '164','code' => 'ID3175','name' => 'Kota Jakarta Utara','country_id' => 'ID','state_code' => 'JK','adm1_code' => 'ID31','adm1_id' => '11'),
  array('id' => '165','code' => 'ID3201','name' => 'Bogor','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '166','code' => 'ID3202','name' => 'Sukabumi','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '167','code' => 'ID3203','name' => 'Cianjur','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '168','code' => 'ID3204','name' => 'Bandung','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '169','code' => 'ID3205','name' => 'Garut','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '170','code' => 'ID3206','name' => 'Tasikmalaya','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '171','code' => 'ID3207','name' => 'Ciamis','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '172','code' => 'ID3208','name' => 'Kuningan','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '173','code' => 'ID3209','name' => 'Cirebon','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '174','code' => 'ID3210','name' => 'Majalengka','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '175','code' => 'ID3211','name' => 'Sumedang','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '176','code' => 'ID3212','name' => 'Indramayu','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '177','code' => 'ID3213','name' => 'Subang','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '178','code' => 'ID3214','name' => 'Purwakarta','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '179','code' => 'ID3215','name' => 'Karawang','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '180','code' => 'ID3216','name' => 'Bekasi','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '181','code' => 'ID3217','name' => 'Bandung Barat','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '182','code' => 'ID3218','name' => 'Pangandaran','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '183','code' => 'ID3271','name' => 'Kota Bogor','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '184','code' => 'ID3272','name' => 'Kota Sukabumi','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '185','code' => 'ID3273','name' => 'Kota Bandung','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '186','code' => 'ID3274','name' => 'Kota Cirebon','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '187','code' => 'ID3275','name' => 'Kota Bekasi','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '188','code' => 'ID3276','name' => 'Kota Depok','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '189','code' => 'ID3277','name' => 'Kota Cimahi','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '190','code' => 'ID3278','name' => 'Kota Tasikmalaya','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '191','code' => 'ID3279','name' => 'Kota Banjar','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '192','code' => 'ID3288','name' => 'Waduk Cirata','country_id' => 'ID','state_code' => 'JB','adm1_code' => 'ID32','adm1_id' => '12'),
  array('id' => '193','code' => 'ID3301','name' => 'Cilacap','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '194','code' => 'ID3302','name' => 'Banyumas','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '195','code' => 'ID3303','name' => 'Purbalingga','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '196','code' => 'ID3304','name' => 'Banjarnegara','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '197','code' => 'ID3305','name' => 'Kebumen','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '198','code' => 'ID3306','name' => 'Purworejo','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '199','code' => 'ID3307','name' => 'Wonosobo','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '200','code' => 'ID3308','name' => 'Magelang','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '201','code' => 'ID3309','name' => 'Boyolali','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '202','code' => 'ID3310','name' => 'Klaten','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '203','code' => 'ID3311','name' => 'Sukoharjo','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '204','code' => 'ID3312','name' => 'Wonogiri','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '205','code' => 'ID3313','name' => 'Karanganyar','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '206','code' => 'ID3314','name' => 'Sragen','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '207','code' => 'ID3315','name' => 'Grobogan','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '208','code' => 'ID3316','name' => 'Blora','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '209','code' => 'ID3317','name' => 'Rembang','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '210','code' => 'ID3318','name' => 'Pati','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '211','code' => 'ID3319','name' => 'Kudus','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '212','code' => 'ID3320','name' => 'Jepara','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '213','code' => 'ID3321','name' => 'Demak','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '214','code' => 'ID3322','name' => 'Semarang','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '215','code' => 'ID3323','name' => 'Temanggung','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '216','code' => 'ID3324','name' => 'Kendal','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '217','code' => 'ID3325','name' => 'Batang','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '218','code' => 'ID3326','name' => 'Pekalongan','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '219','code' => 'ID3327','name' => 'Pemalang','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '220','code' => 'ID3328','name' => 'Tegal','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '221','code' => 'ID3329','name' => 'Brebes','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '222','code' => 'ID3371','name' => 'Kota Magelang','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '223','code' => 'ID3372','name' => 'Kota Surakarta','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '224','code' => 'ID3373','name' => 'Kota Salatiga','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '225','code' => 'ID3374','name' => 'Kota Semarang','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '226','code' => 'ID3375','name' => 'Kota Pekalongan','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '227','code' => 'ID3376','name' => 'Kota Tegal','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '228','code' => 'ID3388','name' => 'Wadung Kedungombo','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '229','code' => 'ID3399','name' => 'Hutan','country_id' => 'ID','state_code' => 'JT','adm1_code' => 'ID33','adm1_id' => '13'),
  array('id' => '230','code' => 'ID3401','name' => 'Kulon Progo','country_id' => 'ID','state_code' => 'YO','adm1_code' => 'ID34','adm1_id' => '14'),
  array('id' => '231','code' => 'ID3402','name' => 'Bantul','country_id' => 'ID','state_code' => 'YO','adm1_code' => 'ID34','adm1_id' => '14'),
  array('id' => '232','code' => 'ID3403','name' => 'Gunung Kidul','country_id' => 'ID','state_code' => 'YO','adm1_code' => 'ID34','adm1_id' => '14'),
  array('id' => '233','code' => 'ID3404','name' => 'Sleman','country_id' => 'ID','state_code' => 'YO','adm1_code' => 'ID34','adm1_id' => '14'),
  array('id' => '234','code' => 'ID3471','name' => 'Kota Yogyakarta','country_id' => 'ID','state_code' => 'YO','adm1_code' => 'ID34','adm1_id' => '14'),
  array('id' => '235','code' => 'ID3501','name' => 'Pacitan','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '236','code' => 'ID3502','name' => 'Ponorogo','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '237','code' => 'ID3503','name' => 'Trenggalek','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '238','code' => 'ID3504','name' => 'Tulungagung','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '239','code' => 'ID3505','name' => 'Blitar','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '240','code' => 'ID3506','name' => 'Kediri','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '241','code' => 'ID3507','name' => 'Malang','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '242','code' => 'ID3508','name' => 'Lumajang','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '243','code' => 'ID3509','name' => 'Jember','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '244','code' => 'ID3510','name' => 'Banyuwangi','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '245','code' => 'ID3511','name' => 'Bondowoso','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '246','code' => 'ID3512','name' => 'Situbondo','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '247','code' => 'ID3513','name' => 'Probolinggo','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '248','code' => 'ID3514','name' => 'Pasuruan','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '249','code' => 'ID3515','name' => 'Sidoarjo','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '250','code' => 'ID3516','name' => 'Mojokerto','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '251','code' => 'ID3517','name' => 'Jombang','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '252','code' => 'ID3518','name' => 'Nganjuk','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '253','code' => 'ID3519','name' => 'Madiun','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '254','code' => 'ID3520','name' => 'Magetan','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '255','code' => 'ID3521','name' => 'Ngawi','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '256','code' => 'ID3522','name' => 'Bojonegoro','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '257','code' => 'ID3523','name' => 'Tuban','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '258','code' => 'ID3524','name' => 'Lamongan','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '259','code' => 'ID3525','name' => 'Gresik','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '260','code' => 'ID3526','name' => 'Bangkalan','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '261','code' => 'ID3527','name' => 'Sampang','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '262','code' => 'ID3528','name' => 'Pamekasan','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '263','code' => 'ID3529','name' => 'Sumenep','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '264','code' => 'ID3571','name' => 'Kota Kediri','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '265','code' => 'ID3572','name' => 'Kota Blitar','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '266','code' => 'ID3573','name' => 'Kota Malang','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '267','code' => 'ID3574','name' => 'Kota Probolinggo','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '268','code' => 'ID3575','name' => 'Kota Pasuruan','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '269','code' => 'ID3576','name' => 'Kota Mojokerto','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '270','code' => 'ID3577','name' => 'Kota Madiun','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '271','code' => 'ID3578','name' => 'Kota Surabaya','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '272','code' => 'ID3579','name' => 'Kota Batu','country_id' => 'ID','state_code' => 'JI','adm1_code' => 'ID35','adm1_id' => '15'),
  array('id' => '273','code' => 'ID3601','name' => 'Pandeglang','country_id' => 'ID','state_code' => 'BT','adm1_code' => 'ID36','adm1_id' => '16'),
  array('id' => '274','code' => 'ID3602','name' => 'Lebak','country_id' => 'ID','state_code' => 'BT','adm1_code' => 'ID36','adm1_id' => '16'),
  array('id' => '275','code' => 'ID3603','name' => 'Tangerang','country_id' => 'ID','state_code' => 'BT','adm1_code' => 'ID36','adm1_id' => '16'),
  array('id' => '276','code' => 'ID3604','name' => 'Serang','country_id' => 'ID','state_code' => 'BT','adm1_code' => 'ID36','adm1_id' => '16'),
  array('id' => '277','code' => 'ID3671','name' => 'Kota Tangerang','country_id' => 'ID','state_code' => 'BT','adm1_code' => 'ID36','adm1_id' => '16'),
  array('id' => '278','code' => 'ID3672','name' => 'Kota Cilegon','country_id' => 'ID','state_code' => 'BT','adm1_code' => 'ID36','adm1_id' => '16'),
  array('id' => '279','code' => 'ID3673','name' => 'Kota Serang','country_id' => 'ID','state_code' => 'BT','adm1_code' => 'ID36','adm1_id' => '16'),
  array('id' => '280','code' => 'ID3674','name' => 'Kota Tangerang Selatan','country_id' => 'ID','state_code' => 'BT','adm1_code' => 'ID36','adm1_id' => '16'),
  array('id' => '281','code' => 'ID5101','name' => 'Jembrana','country_id' => 'ID','state_code' => 'BA','adm1_code' => 'ID51','adm1_id' => '17'),
  array('id' => '282','code' => 'ID5102','name' => 'Tabanan','country_id' => 'ID','state_code' => 'BA','adm1_code' => 'ID51','adm1_id' => '17'),
  array('id' => '283','code' => 'ID5103','name' => 'Badung','country_id' => 'ID','state_code' => 'BA','adm1_code' => 'ID51','adm1_id' => '17'),
  array('id' => '284','code' => 'ID5104','name' => 'Gianyar','country_id' => 'ID','state_code' => 'BA','adm1_code' => 'ID51','adm1_id' => '17'),
  array('id' => '285','code' => 'ID5105','name' => 'Klungkung','country_id' => 'ID','state_code' => 'BA','adm1_code' => 'ID51','adm1_id' => '17'),
  array('id' => '286','code' => 'ID5106','name' => 'Bangli','country_id' => 'ID','state_code' => 'BA','adm1_code' => 'ID51','adm1_id' => '17'),
  array('id' => '287','code' => 'ID5107','name' => 'Karang Asem','country_id' => 'ID','state_code' => 'BA','adm1_code' => 'ID51','adm1_id' => '17'),
  array('id' => '288','code' => 'ID5108','name' => 'Buleleng','country_id' => 'ID','state_code' => 'BA','adm1_code' => 'ID51','adm1_id' => '17'),
  array('id' => '289','code' => 'ID5171','name' => 'Kota Denpasar','country_id' => 'ID','state_code' => 'BA','adm1_code' => 'ID51','adm1_id' => '17'),
  array('id' => '290','code' => 'ID5201','name' => 'Lombok Barat','country_id' => 'ID','state_code' => 'NB','adm1_code' => 'ID52','adm1_id' => '18'),
  array('id' => '291','code' => 'ID5202','name' => 'Lombok Tengah','country_id' => 'ID','state_code' => 'NB','adm1_code' => 'ID52','adm1_id' => '18'),
  array('id' => '292','code' => 'ID5203','name' => 'Lombok Timur','country_id' => 'ID','state_code' => 'NB','adm1_code' => 'ID52','adm1_id' => '18'),
  array('id' => '293','code' => 'ID5204','name' => 'Sumbawa','country_id' => 'ID','state_code' => 'NB','adm1_code' => 'ID52','adm1_id' => '18'),
  array('id' => '294','code' => 'ID5205','name' => 'Dompu','country_id' => 'ID','state_code' => 'NB','adm1_code' => 'ID52','adm1_id' => '18'),
  array('id' => '295','code' => 'ID5206','name' => 'Bima','country_id' => 'ID','state_code' => 'NB','adm1_code' => 'ID52','adm1_id' => '18'),
  array('id' => '296','code' => 'ID5207','name' => 'Sumbawa Barat','country_id' => 'ID','state_code' => 'NB','adm1_code' => 'ID52','adm1_id' => '18'),
  array('id' => '297','code' => 'ID5208','name' => 'Lombok Utara','country_id' => 'ID','state_code' => 'NB','adm1_code' => 'ID52','adm1_id' => '18'),
  array('id' => '298','code' => 'ID5271','name' => 'Kota Mataram','country_id' => 'ID','state_code' => 'NB','adm1_code' => 'ID52','adm1_id' => '18'),
  array('id' => '299','code' => 'ID5272','name' => 'Kota Bima','country_id' => 'ID','state_code' => 'NB','adm1_code' => 'ID52','adm1_id' => '18'),
  array('id' => '300','code' => 'ID5301','name' => 'Sumba Barat','country_id' => 'ID','state_code' => 'NT','adm1_code' => 'ID53','adm1_id' => '19'),
  array('id' => '301','code' => 'ID5302','name' => 'Sumba Timur','country_id' => 'ID','state_code' => 'NT','adm1_code' => 'ID53','adm1_id' => '19'),
  array('id' => '302','code' => 'ID5303','name' => 'Kupang','country_id' => 'ID','state_code' => 'NT','adm1_code' => 'ID53','adm1_id' => '19'),
  array('id' => '303','code' => 'ID5304','name' => 'Timor Tengah Selatan','country_id' => 'ID','state_code' => 'NT','adm1_code' => 'ID53','adm1_id' => '19'),
  array('id' => '304','code' => 'ID5305','name' => 'Timor Tengah Utara','country_id' => 'ID','state_code' => 'NT','adm1_code' => 'ID53','adm1_id' => '19'),
  array('id' => '305','code' => 'ID5306','name' => 'Belu','country_id' => 'ID','state_code' => 'NT','adm1_code' => 'ID53','adm1_id' => '19'),
  array('id' => '306','code' => 'ID5307','name' => 'Alor','country_id' => 'ID','state_code' => 'NT','adm1_code' => 'ID53','adm1_id' => '19'),
  array('id' => '307','code' => 'ID5308','name' => 'Lembata','country_id' => 'ID','state_code' => 'NT','adm1_code' => 'ID53','adm1_id' => '19'),
  array('id' => '308','code' => 'ID5309','name' => 'Flores Timur','country_id' => 'ID','state_code' => 'NT','adm1_code' => 'ID53','adm1_id' => '19'),
  array('id' => '309','code' => 'ID5310','name' => 'Sikka','country_id' => 'ID','state_code' => 'NT','adm1_code' => 'ID53','adm1_id' => '19'),
  array('id' => '310','code' => 'ID5311','name' => 'Ende','country_id' => 'ID','state_code' => 'NT','adm1_code' => 'ID53','adm1_id' => '19'),
  array('id' => '311','code' => 'ID5312','name' => 'Ngada','country_id' => 'ID','state_code' => 'NT','adm1_code' => 'ID53','adm1_id' => '19'),
  array('id' => '312','code' => 'ID5313','name' => 'Manggarai','country_id' => 'ID','state_code' => 'NT','adm1_code' => 'ID53','adm1_id' => '19'),
  array('id' => '313','code' => 'ID5314','name' => 'Rote Ndao','country_id' => 'ID','state_code' => 'NT','adm1_code' => 'ID53','adm1_id' => '19'),
  array('id' => '314','code' => 'ID5315','name' => 'Manggarai Barat','country_id' => 'ID','state_code' => 'NT','adm1_code' => 'ID53','adm1_id' => '19'),
  array('id' => '315','code' => 'ID5316','name' => 'Sumba Tengah','country_id' => 'ID','state_code' => 'NT','adm1_code' => 'ID53','adm1_id' => '19'),
  array('id' => '316','code' => 'ID5317','name' => 'Sumba Barat Daya','country_id' => 'ID','state_code' => 'NT','adm1_code' => 'ID53','adm1_id' => '19'),
  array('id' => '317','code' => 'ID5318','name' => 'Nagekeo','country_id' => 'ID','state_code' => 'NT','adm1_code' => 'ID53','adm1_id' => '19'),
  array('id' => '318','code' => 'ID5319','name' => 'Manggarai Timur','country_id' => 'ID','state_code' => 'NT','adm1_code' => 'ID53','adm1_id' => '19'),
  array('id' => '319','code' => 'ID5320','name' => 'Sabu Raijua','country_id' => 'ID','state_code' => 'NT','adm1_code' => 'ID53','adm1_id' => '19'),
  array('id' => '320','code' => 'ID5321','name' => 'Malaka','country_id' => 'ID','state_code' => 'NT','adm1_code' => 'ID53','adm1_id' => '19'),
  array('id' => '321','code' => 'ID5371','name' => 'Kota Kupang','country_id' => 'ID','state_code' => 'NT','adm1_code' => 'ID53','adm1_id' => '19'),
  array('id' => '322','code' => 'ID6101','name' => 'Sambas','country_id' => 'ID','state_code' => 'KB','adm1_code' => 'ID61','adm1_id' => '20'),
  array('id' => '323','code' => 'ID6102','name' => 'Bengkayang','country_id' => 'ID','state_code' => 'KB','adm1_code' => 'ID61','adm1_id' => '20'),
  array('id' => '324','code' => 'ID6103','name' => 'Landak','country_id' => 'ID','state_code' => 'KB','adm1_code' => 'ID61','adm1_id' => '20'),
  array('id' => '325','code' => 'ID6104','name' => 'Mempawah','country_id' => 'ID','state_code' => 'KB','adm1_code' => 'ID61','adm1_id' => '20'),
  array('id' => '326','code' => 'ID6105','name' => 'Sanggau','country_id' => 'ID','state_code' => 'KB','adm1_code' => 'ID61','adm1_id' => '20'),
  array('id' => '327','code' => 'ID6106','name' => 'Ketapang','country_id' => 'ID','state_code' => 'KB','adm1_code' => 'ID61','adm1_id' => '20'),
  array('id' => '328','code' => 'ID6107','name' => 'Sintang','country_id' => 'ID','state_code' => 'KB','adm1_code' => 'ID61','adm1_id' => '20'),
  array('id' => '329','code' => 'ID6108','name' => 'Kapuas Hulu','country_id' => 'ID','state_code' => 'KB','adm1_code' => 'ID61','adm1_id' => '20'),
  array('id' => '330','code' => 'ID6109','name' => 'Sekadau','country_id' => 'ID','state_code' => 'KB','adm1_code' => 'ID61','adm1_id' => '20'),
  array('id' => '331','code' => 'ID6110','name' => 'Melawi','country_id' => 'ID','state_code' => 'KB','adm1_code' => 'ID61','adm1_id' => '20'),
  array('id' => '332','code' => 'ID6111','name' => 'Kayong Utara','country_id' => 'ID','state_code' => 'KB','adm1_code' => 'ID61','adm1_id' => '20'),
  array('id' => '333','code' => 'ID6112','name' => 'Kubu Raya','country_id' => 'ID','state_code' => 'KB','adm1_code' => 'ID61','adm1_id' => '20'),
  array('id' => '334','code' => 'ID6171','name' => 'Kota Pontianak','country_id' => 'ID','state_code' => 'KB','adm1_code' => 'ID61','adm1_id' => '20'),
  array('id' => '335','code' => 'ID6172','name' => 'Kota Singkawang','country_id' => 'ID','state_code' => 'KB','adm1_code' => 'ID61','adm1_id' => '20'),
  array('id' => '336','code' => 'ID6201','name' => 'Kotawaringin Barat','country_id' => 'ID','state_code' => 'KT','adm1_code' => 'ID62','adm1_id' => '21'),
  array('id' => '337','code' => 'ID6202','name' => 'Kotawaringin Timur','country_id' => 'ID','state_code' => 'KT','adm1_code' => 'ID62','adm1_id' => '21'),
  array('id' => '338','code' => 'ID6203','name' => 'Kapuas','country_id' => 'ID','state_code' => 'KT','adm1_code' => 'ID62','adm1_id' => '21'),
  array('id' => '339','code' => 'ID6204','name' => 'Barito Selatan','country_id' => 'ID','state_code' => 'KT','adm1_code' => 'ID62','adm1_id' => '21'),
  array('id' => '340','code' => 'ID6205','name' => 'Barito Utara','country_id' => 'ID','state_code' => 'KT','adm1_code' => 'ID62','adm1_id' => '21'),
  array('id' => '341','code' => 'ID6206','name' => 'Sukamara','country_id' => 'ID','state_code' => 'KT','adm1_code' => 'ID62','adm1_id' => '21'),
  array('id' => '342','code' => 'ID6207','name' => 'Lamandau','country_id' => 'ID','state_code' => 'KT','adm1_code' => 'ID62','adm1_id' => '21'),
  array('id' => '343','code' => 'ID6208','name' => 'Seruyan','country_id' => 'ID','state_code' => 'KT','adm1_code' => 'ID62','adm1_id' => '21'),
  array('id' => '344','code' => 'ID6209','name' => 'Katingan','country_id' => 'ID','state_code' => 'KT','adm1_code' => 'ID62','adm1_id' => '21'),
  array('id' => '345','code' => 'ID6210','name' => 'Pulang Pisau','country_id' => 'ID','state_code' => 'KT','adm1_code' => 'ID62','adm1_id' => '21'),
  array('id' => '346','code' => 'ID6211','name' => 'Gunung Mas','country_id' => 'ID','state_code' => 'KT','adm1_code' => 'ID62','adm1_id' => '21'),
  array('id' => '347','code' => 'ID6212','name' => 'Barito Timur','country_id' => 'ID','state_code' => 'KT','adm1_code' => 'ID62','adm1_id' => '21'),
  array('id' => '348','code' => 'ID6213','name' => 'Murung Raya','country_id' => 'ID','state_code' => 'KT','adm1_code' => 'ID62','adm1_id' => '21'),
  array('id' => '349','code' => 'ID6271','name' => 'Kota Palangka Raya','country_id' => 'ID','state_code' => 'KT','adm1_code' => 'ID62','adm1_id' => '21'),
  array('id' => '350','code' => 'ID6301','name' => 'Tanah Laut','country_id' => 'ID','state_code' => 'KS','adm1_code' => 'ID63','adm1_id' => '22'),
  array('id' => '351','code' => 'ID6302','name' => 'Kota Baru','country_id' => 'ID','state_code' => 'KS','adm1_code' => 'ID63','adm1_id' => '22'),
  array('id' => '352','code' => 'ID6303','name' => 'Banjar','country_id' => 'ID','state_code' => 'KS','adm1_code' => 'ID63','adm1_id' => '22'),
  array('id' => '353','code' => 'ID6304','name' => 'Barito Kuala','country_id' => 'ID','state_code' => 'KS','adm1_code' => 'ID63','adm1_id' => '22'),
  array('id' => '354','code' => 'ID6305','name' => 'Tapin','country_id' => 'ID','state_code' => 'KS','adm1_code' => 'ID63','adm1_id' => '22'),
  array('id' => '355','code' => 'ID6306','name' => 'Hulu Sungai Selatan','country_id' => 'ID','state_code' => 'KS','adm1_code' => 'ID63','adm1_id' => '22'),
  array('id' => '356','code' => 'ID6307','name' => 'Hulu Sungai Tengah','country_id' => 'ID','state_code' => 'KS','adm1_code' => 'ID63','adm1_id' => '22'),
  array('id' => '357','code' => 'ID6308','name' => 'Hulu Sungai Utara','country_id' => 'ID','state_code' => 'KS','adm1_code' => 'ID63','adm1_id' => '22'),
  array('id' => '358','code' => 'ID6309','name' => 'Tabalong','country_id' => 'ID','state_code' => 'KS','adm1_code' => 'ID63','adm1_id' => '22'),
  array('id' => '359','code' => 'ID6310','name' => 'Tanah Bumbu','country_id' => 'ID','state_code' => 'KS','adm1_code' => 'ID63','adm1_id' => '22'),
  array('id' => '360','code' => 'ID6311','name' => 'Balangan','country_id' => 'ID','state_code' => 'KS','adm1_code' => 'ID63','adm1_id' => '22'),
  array('id' => '361','code' => 'ID6371','name' => 'Kota Banjarmasin','country_id' => 'ID','state_code' => 'KS','adm1_code' => 'ID63','adm1_id' => '22'),
  array('id' => '362','code' => 'ID6372','name' => 'Kota Banjar Baru','country_id' => 'ID','state_code' => 'KS','adm1_code' => 'ID63','adm1_id' => '22'),
  array('id' => '363','code' => 'ID6401','name' => 'Paser','country_id' => 'ID','state_code' => 'KI','adm1_code' => 'ID64','adm1_id' => '23'),
  array('id' => '364','code' => 'ID6402','name' => 'Kutai Barat','country_id' => 'ID','state_code' => 'KI','adm1_code' => 'ID64','adm1_id' => '23'),
  array('id' => '365','code' => 'ID6403','name' => 'Kutai Kartanegara','country_id' => 'ID','state_code' => 'KI','adm1_code' => 'ID64','adm1_id' => '23'),
  array('id' => '366','code' => 'ID6404','name' => 'Kutai Timur','country_id' => 'ID','state_code' => 'KI','adm1_code' => 'ID64','adm1_id' => '23'),
  array('id' => '367','code' => 'ID6405','name' => 'Berau','country_id' => 'ID','state_code' => 'KI','adm1_code' => 'ID64','adm1_id' => '23'),
  array('id' => '368','code' => 'ID6409','name' => 'Penajam Paser Utara','country_id' => 'ID','state_code' => 'KI','adm1_code' => 'ID64','adm1_id' => '23'),
  array('id' => '369','code' => 'ID6411','name' => 'Mahakam Hulu','country_id' => 'ID','state_code' => 'KI','adm1_code' => 'ID64','adm1_id' => '23'),
  array('id' => '370','code' => 'ID6471','name' => 'Kota Balikpapan','country_id' => 'ID','state_code' => 'KI','adm1_code' => 'ID64','adm1_id' => '23'),
  array('id' => '371','code' => 'ID6472','name' => 'Kota Samarinda','country_id' => 'ID','state_code' => 'KI','adm1_code' => 'ID64','adm1_id' => '23'),
  array('id' => '372','code' => 'ID6474','name' => 'Kota Bontang','country_id' => 'ID','state_code' => 'KI','adm1_code' => 'ID64','adm1_id' => '23'),
  array('id' => '373','code' => 'ID6501','name' => 'Malinau','country_id' => 'ID','state_code' => 'KU','adm1_code' => 'ID65','adm1_id' => '24'),
  array('id' => '374','code' => 'ID6502','name' => 'Bulungan','country_id' => 'ID','state_code' => 'KU','adm1_code' => 'ID65','adm1_id' => '24'),
  array('id' => '375','code' => 'ID6503','name' => 'Tana Tidung','country_id' => 'ID','state_code' => 'KU','adm1_code' => 'ID65','adm1_id' => '24'),
  array('id' => '376','code' => 'ID6504','name' => 'Nunukan','country_id' => 'ID','state_code' => 'KU','adm1_code' => 'ID65','adm1_id' => '24'),
  array('id' => '377','code' => 'ID6571','name' => 'Kota Tarakan','country_id' => 'ID','state_code' => 'KU','adm1_code' => 'ID65','adm1_id' => '24'),
  array('id' => '378','code' => 'ID7101','name' => 'Bolaang Mongondow','country_id' => 'ID','state_code' => 'SA','adm1_code' => 'ID71','adm1_id' => '25'),
  array('id' => '379','code' => 'ID7102','name' => 'Minahasa','country_id' => 'ID','state_code' => 'SA','adm1_code' => 'ID71','adm1_id' => '25'),
  array('id' => '380','code' => 'ID7103','name' => 'Kepulauan Sangihe','country_id' => 'ID','state_code' => 'SA','adm1_code' => 'ID71','adm1_id' => '25'),
  array('id' => '381','code' => 'ID7104','name' => 'Kepulauan Talaud','country_id' => 'ID','state_code' => 'SA','adm1_code' => 'ID71','adm1_id' => '25'),
  array('id' => '382','code' => 'ID7105','name' => 'Minahasa Selatan','country_id' => 'ID','state_code' => 'SA','adm1_code' => 'ID71','adm1_id' => '25'),
  array('id' => '383','code' => 'ID7106','name' => 'Minahasa Utara','country_id' => 'ID','state_code' => 'SA','adm1_code' => 'ID71','adm1_id' => '25'),
  array('id' => '384','code' => 'ID7107','name' => 'Bolaang Mongondow Utara','country_id' => 'ID','state_code' => 'SA','adm1_code' => 'ID71','adm1_id' => '25'),
  array('id' => '385','code' => 'ID7108','name' => 'Siau Tagulandang Biaro','country_id' => 'ID','state_code' => 'SA','adm1_code' => 'ID71','adm1_id' => '25'),
  array('id' => '386','code' => 'ID7109','name' => 'Minahasa Tenggara','country_id' => 'ID','state_code' => 'SA','adm1_code' => 'ID71','adm1_id' => '25'),
  array('id' => '387','code' => 'ID7110','name' => 'Bolaang Mongondow Selatan','country_id' => 'ID','state_code' => 'SA','adm1_code' => 'ID71','adm1_id' => '25'),
  array('id' => '388','code' => 'ID7111','name' => 'Bolaang Mongondow Timur','country_id' => 'ID','state_code' => 'SA','adm1_code' => 'ID71','adm1_id' => '25'),
  array('id' => '389','code' => 'ID7171','name' => 'Kota Manado','country_id' => 'ID','state_code' => 'SA','adm1_code' => 'ID71','adm1_id' => '25'),
  array('id' => '390','code' => 'ID7172','name' => 'Kota Bitung','country_id' => 'ID','state_code' => 'SA','adm1_code' => 'ID71','adm1_id' => '25'),
  array('id' => '391','code' => 'ID7173','name' => 'Kota Tomohon','country_id' => 'ID','state_code' => 'SA','adm1_code' => 'ID71','adm1_id' => '25'),
  array('id' => '392','code' => 'ID7174','name' => 'Kota Kotamobagu','country_id' => 'ID','state_code' => 'SA','adm1_code' => 'ID71','adm1_id' => '25'),
  array('id' => '393','code' => 'ID7188','name' => 'Danau','country_id' => 'ID','state_code' => 'SA','adm1_code' => 'ID71','adm1_id' => '25'),
  array('id' => '394','code' => 'ID7201','name' => 'Banggai Kepulauan','country_id' => 'ID','state_code' => 'ST','adm1_code' => 'ID72','adm1_id' => '26'),
  array('id' => '395','code' => 'ID7202','name' => 'Banggai','country_id' => 'ID','state_code' => 'ST','adm1_code' => 'ID72','adm1_id' => '26'),
  array('id' => '396','code' => 'ID7203','name' => 'Morowali','country_id' => 'ID','state_code' => 'ST','adm1_code' => 'ID72','adm1_id' => '26'),
  array('id' => '397','code' => 'ID7204','name' => 'Poso','country_id' => 'ID','state_code' => 'ST','adm1_code' => 'ID72','adm1_id' => '26'),
  array('id' => '398','code' => 'ID7205','name' => 'Donggala','country_id' => 'ID','state_code' => 'ST','adm1_code' => 'ID72','adm1_id' => '26'),
  array('id' => '399','code' => 'ID7206','name' => 'Toli-Toli','country_id' => 'ID','state_code' => 'ST','adm1_code' => 'ID72','adm1_id' => '26'),
  array('id' => '400','code' => 'ID7207','name' => 'Buol','country_id' => 'ID','state_code' => 'ST','adm1_code' => 'ID72','adm1_id' => '26'),
  array('id' => '401','code' => 'ID7208','name' => 'Parigi Moutong','country_id' => 'ID','state_code' => 'ST','adm1_code' => 'ID72','adm1_id' => '26'),
  array('id' => '402','code' => 'ID7209','name' => 'Tojo Una-Una','country_id' => 'ID','state_code' => 'ST','adm1_code' => 'ID72','adm1_id' => '26'),
  array('id' => '403','code' => 'ID7210','name' => 'Sigi','country_id' => 'ID','state_code' => 'ST','adm1_code' => 'ID72','adm1_id' => '26'),
  array('id' => '404','code' => 'ID7211','name' => 'Banggai Laut','country_id' => 'ID','state_code' => 'ST','adm1_code' => 'ID72','adm1_id' => '26'),
  array('id' => '405','code' => 'ID7212','name' => 'Morowali Utara','country_id' => 'ID','state_code' => 'ST','adm1_code' => 'ID72','adm1_id' => '26'),
  array('id' => '406','code' => 'ID7271','name' => 'Kota Palu','country_id' => 'ID','state_code' => 'ST','adm1_code' => 'ID72','adm1_id' => '26'),
  array('id' => '407','code' => 'ID7301','name' => 'Kepulauan Selayar','country_id' => 'ID','state_code' => 'SN','adm1_code' => 'ID73','adm1_id' => '27'),
  array('id' => '408','code' => 'ID7302','name' => 'Bulukumba','country_id' => 'ID','state_code' => 'SN','adm1_code' => 'ID73','adm1_id' => '27'),
  array('id' => '409','code' => 'ID7303','name' => 'Bantaeng','country_id' => 'ID','state_code' => 'SN','adm1_code' => 'ID73','adm1_id' => '27'),
  array('id' => '410','code' => 'ID7304','name' => 'Jeneponto','country_id' => 'ID','state_code' => 'SN','adm1_code' => 'ID73','adm1_id' => '27'),
  array('id' => '411','code' => 'ID7305','name' => 'Takalar','country_id' => 'ID','state_code' => 'SN','adm1_code' => 'ID73','adm1_id' => '27'),
  array('id' => '412','code' => 'ID7306','name' => 'Gowa','country_id' => 'ID','state_code' => 'SN','adm1_code' => 'ID73','adm1_id' => '27'),
  array('id' => '413','code' => 'ID7307','name' => 'Sinjai','country_id' => 'ID','state_code' => 'SN','adm1_code' => 'ID73','adm1_id' => '27'),
  array('id' => '414','code' => 'ID7308','name' => 'Maros','country_id' => 'ID','state_code' => 'SN','adm1_code' => 'ID73','adm1_id' => '27'),
  array('id' => '415','code' => 'ID7309','name' => 'Pangkajene Dan Kepulauan','country_id' => 'ID','state_code' => 'SN','adm1_code' => 'ID73','adm1_id' => '27'),
  array('id' => '416','code' => 'ID7310','name' => 'Barru','country_id' => 'ID','state_code' => 'SN','adm1_code' => 'ID73','adm1_id' => '27'),
  array('id' => '417','code' => 'ID7311','name' => 'Bone','country_id' => 'ID','state_code' => 'SN','adm1_code' => 'ID73','adm1_id' => '27'),
  array('id' => '418','code' => 'ID7312','name' => 'Soppeng','country_id' => 'ID','state_code' => 'SN','adm1_code' => 'ID73','adm1_id' => '27'),
  array('id' => '419','code' => 'ID7313','name' => 'Wajo','country_id' => 'ID','state_code' => 'SN','adm1_code' => 'ID73','adm1_id' => '27'),
  array('id' => '420','code' => 'ID7314','name' => 'Sidenreng Rappang','country_id' => 'ID','state_code' => 'SN','adm1_code' => 'ID73','adm1_id' => '27'),
  array('id' => '421','code' => 'ID7315','name' => 'Pinrang','country_id' => 'ID','state_code' => 'SN','adm1_code' => 'ID73','adm1_id' => '27'),
  array('id' => '422','code' => 'ID7316','name' => 'Enrekang','country_id' => 'ID','state_code' => 'SN','adm1_code' => 'ID73','adm1_id' => '27'),
  array('id' => '423','code' => 'ID7317','name' => 'Luwu','country_id' => 'ID','state_code' => 'SN','adm1_code' => 'ID73','adm1_id' => '27'),
  array('id' => '424','code' => 'ID7318','name' => 'Tana Toraja','country_id' => 'ID','state_code' => 'SN','adm1_code' => 'ID73','adm1_id' => '27'),
  array('id' => '425','code' => 'ID7322','name' => 'Luwu Utara','country_id' => 'ID','state_code' => 'SN','adm1_code' => 'ID73','adm1_id' => '27'),
  array('id' => '426','code' => 'ID7325','name' => 'Luwu Timur','country_id' => 'ID','state_code' => 'SN','adm1_code' => 'ID73','adm1_id' => '27'),
  array('id' => '427','code' => 'ID7326','name' => 'Toraja Utara','country_id' => 'ID','state_code' => 'SN','adm1_code' => 'ID73','adm1_id' => '27'),
  array('id' => '428','code' => 'ID7371','name' => 'Kota Makassar','country_id' => 'ID','state_code' => 'SN','adm1_code' => 'ID73','adm1_id' => '27'),
  array('id' => '429','code' => 'ID7372','name' => 'Kota Parepare','country_id' => 'ID','state_code' => 'SN','adm1_code' => 'ID73','adm1_id' => '27'),
  array('id' => '430','code' => 'ID7373','name' => 'Kota Palopo','country_id' => 'ID','state_code' => 'SN','adm1_code' => 'ID73','adm1_id' => '27'),
  array('id' => '431','code' => 'ID7401','name' => 'Buton','country_id' => 'ID','state_code' => 'SG','adm1_code' => 'ID74','adm1_id' => '28'),
  array('id' => '432','code' => 'ID7402','name' => 'Muna','country_id' => 'ID','state_code' => 'SG','adm1_code' => 'ID74','adm1_id' => '28'),
  array('id' => '433','code' => 'ID7403','name' => 'Konawe','country_id' => 'ID','state_code' => 'SG','adm1_code' => 'ID74','adm1_id' => '28'),
  array('id' => '434','code' => 'ID7404','name' => 'Kolaka','country_id' => 'ID','state_code' => 'SG','adm1_code' => 'ID74','adm1_id' => '28'),
  array('id' => '435','code' => 'ID7405','name' => 'Konawe Selatan','country_id' => 'ID','state_code' => 'SG','adm1_code' => 'ID74','adm1_id' => '28'),
  array('id' => '436','code' => 'ID7406','name' => 'Bombana','country_id' => 'ID','state_code' => 'SG','adm1_code' => 'ID74','adm1_id' => '28'),
  array('id' => '437','code' => 'ID7407','name' => 'Wakatobi','country_id' => 'ID','state_code' => 'SG','adm1_code' => 'ID74','adm1_id' => '28'),
  array('id' => '438','code' => 'ID7408','name' => 'Kolaka Utara','country_id' => 'ID','state_code' => 'SG','adm1_code' => 'ID74','adm1_id' => '28'),
  array('id' => '439','code' => 'ID7409','name' => 'Buton Utara','country_id' => 'ID','state_code' => 'SG','adm1_code' => 'ID74','adm1_id' => '28'),
  array('id' => '440','code' => 'ID7410','name' => 'Konawe Utara','country_id' => 'ID','state_code' => 'SG','adm1_code' => 'ID74','adm1_id' => '28'),
  array('id' => '441','code' => 'ID7411','name' => 'Kolaka Timur','country_id' => 'ID','state_code' => 'SG','adm1_code' => 'ID74','adm1_id' => '28'),
  array('id' => '442','code' => 'ID7412','name' => 'Konawe Kepulauan','country_id' => 'ID','state_code' => 'SG','adm1_code' => 'ID74','adm1_id' => '28'),
  array('id' => '443','code' => 'ID7413','name' => 'Muna Barat','country_id' => 'ID','state_code' => 'SG','adm1_code' => 'ID74','adm1_id' => '28'),
  array('id' => '444','code' => 'ID7414','name' => 'Buton Tengah','country_id' => 'ID','state_code' => 'SG','adm1_code' => 'ID74','adm1_id' => '28'),
  array('id' => '445','code' => 'ID7415','name' => 'Buton Selatan','country_id' => 'ID','state_code' => 'SG','adm1_code' => 'ID74','adm1_id' => '28'),
  array('id' => '446','code' => 'ID7471','name' => 'Kota Kendari','country_id' => 'ID','state_code' => 'SG','adm1_code' => 'ID74','adm1_id' => '28'),
  array('id' => '447','code' => 'ID7472','name' => 'Kota Baubau','country_id' => 'ID','state_code' => 'SG','adm1_code' => 'ID74','adm1_id' => '28'),
  array('id' => '448','code' => 'ID7501','name' => 'Boalemo','country_id' => 'ID','state_code' => 'GO','adm1_code' => 'ID75','adm1_id' => '29'),
  array('id' => '449','code' => 'ID7502','name' => 'Gorontalo','country_id' => 'ID','state_code' => 'GO','adm1_code' => 'ID75','adm1_id' => '29'),
  array('id' => '450','code' => 'ID7503','name' => 'Pohuwato','country_id' => 'ID','state_code' => 'GO','adm1_code' => 'ID75','adm1_id' => '29'),
  array('id' => '451','code' => 'ID7504','name' => 'Bone Bolango','country_id' => 'ID','state_code' => 'GO','adm1_code' => 'ID75','adm1_id' => '29'),
  array('id' => '452','code' => 'ID7505','name' => 'Gorontalo Utara','country_id' => 'ID','state_code' => 'GO','adm1_code' => 'ID75','adm1_id' => '29'),
  array('id' => '453','code' => 'ID7571','name' => 'Kota Gorontalo','country_id' => 'ID','state_code' => 'GO','adm1_code' => 'ID75','adm1_id' => '29'),
  array('id' => '454','code' => 'ID7601','name' => 'Majene','country_id' => 'ID','state_code' => 'SR','adm1_code' => 'ID76','adm1_id' => '30'),
  array('id' => '455','code' => 'ID7602','name' => 'Polewali Mandar','country_id' => 'ID','state_code' => 'SR','adm1_code' => 'ID76','adm1_id' => '30'),
  array('id' => '456','code' => 'ID7603','name' => 'Mamasa','country_id' => 'ID','state_code' => 'SR','adm1_code' => 'ID76','adm1_id' => '30'),
  array('id' => '457','code' => 'ID7604','name' => 'Mamuju','country_id' => 'ID','state_code' => 'SR','adm1_code' => 'ID76','adm1_id' => '30'),
  array('id' => '458','code' => 'ID7605','name' => 'Mamuju Utara','country_id' => 'ID','state_code' => 'SR','adm1_code' => 'ID76','adm1_id' => '30'),
  array('id' => '459','code' => 'ID7606','name' => 'Mamuju Tengah','country_id' => 'ID','state_code' => 'SR','adm1_code' => 'ID76','adm1_id' => '30'),
  array('id' => '460','code' => 'ID8101','name' => 'Maluku Tenggara Barat','country_id' => 'ID','state_code' => 'MA','adm1_code' => 'ID81','adm1_id' => '31'),
  array('id' => '461','code' => 'ID8102','name' => 'Maluku Tenggara','country_id' => 'ID','state_code' => 'MA','adm1_code' => 'ID81','adm1_id' => '31'),
  array('id' => '462','code' => 'ID8103','name' => 'Maluku Tengah','country_id' => 'ID','state_code' => 'MA','adm1_code' => 'ID81','adm1_id' => '31'),
  array('id' => '463','code' => 'ID8104','name' => 'Buru','country_id' => 'ID','state_code' => 'MA','adm1_code' => 'ID81','adm1_id' => '31'),
  array('id' => '464','code' => 'ID8105','name' => 'Kepulauan Aru','country_id' => 'ID','state_code' => 'MA','adm1_code' => 'ID81','adm1_id' => '31'),
  array('id' => '465','code' => 'ID8106','name' => 'Seram Bagian Barat','country_id' => 'ID','state_code' => 'MA','adm1_code' => 'ID81','adm1_id' => '31'),
  array('id' => '466','code' => 'ID8107','name' => 'Seram Bagian Timur','country_id' => 'ID','state_code' => 'MA','adm1_code' => 'ID81','adm1_id' => '31'),
  array('id' => '467','code' => 'ID8108','name' => 'Maluku Barat Daya','country_id' => 'ID','state_code' => 'MA','adm1_code' => 'ID81','adm1_id' => '31'),
  array('id' => '468','code' => 'ID8109','name' => 'Buru Selatan','country_id' => 'ID','state_code' => 'MA','adm1_code' => 'ID81','adm1_id' => '31'),
  array('id' => '469','code' => 'ID8171','name' => 'Kota Ambon','country_id' => 'ID','state_code' => 'MA','adm1_code' => 'ID81','adm1_id' => '31'),
  array('id' => '470','code' => 'ID8172','name' => 'Kota Tual','country_id' => 'ID','state_code' => 'MA','adm1_code' => 'ID81','adm1_id' => '31'),
  array('id' => '471','code' => 'ID8201','name' => 'Halmahera Barat','country_id' => 'ID','state_code' => 'MU','adm1_code' => 'ID82','adm1_id' => '32'),
  array('id' => '472','code' => 'ID8202','name' => 'Halmahera Tengah','country_id' => 'ID','state_code' => 'MU','adm1_code' => 'ID82','adm1_id' => '32'),
  array('id' => '473','code' => 'ID8203','name' => 'Kepulauan Sula','country_id' => 'ID','state_code' => 'MU','adm1_code' => 'ID82','adm1_id' => '32'),
  array('id' => '474','code' => 'ID8204','name' => 'Halmahera Selatan','country_id' => 'ID','state_code' => 'MU','adm1_code' => 'ID82','adm1_id' => '32'),
  array('id' => '475','code' => 'ID8205','name' => 'Halmahera Utara','country_id' => 'ID','state_code' => 'MU','adm1_code' => 'ID82','adm1_id' => '32'),
  array('id' => '476','code' => 'ID8206','name' => 'Halmahera Timur','country_id' => 'ID','state_code' => 'MU','adm1_code' => 'ID82','adm1_id' => '32'),
  array('id' => '477','code' => 'ID8207','name' => 'Pulau Morotai','country_id' => 'ID','state_code' => 'MU','adm1_code' => 'ID82','adm1_id' => '32'),
  array('id' => '478','code' => 'ID8208','name' => 'Pulau Taliabu','country_id' => 'ID','state_code' => 'MU','adm1_code' => 'ID82','adm1_id' => '32'),
  array('id' => '479','code' => 'ID8271','name' => 'Kota Ternate','country_id' => 'ID','state_code' => 'MU','adm1_code' => 'ID82','adm1_id' => '32'),
  array('id' => '480','code' => 'ID8272','name' => 'Kota Tidore Kepulauan','country_id' => 'ID','state_code' => 'MU','adm1_code' => 'ID82','adm1_id' => '32'),
  array('id' => '481','code' => 'ID9101','name' => 'Fakfak','country_id' => 'ID','state_code' => 'PB','adm1_code' => 'ID91','adm1_id' => '33'),
  array('id' => '482','code' => 'ID9102','name' => 'Kaimana','country_id' => 'ID','state_code' => 'PB','adm1_code' => 'ID91','adm1_id' => '33'),
  array('id' => '483','code' => 'ID9103','name' => 'Teluk Wondama','country_id' => 'ID','state_code' => 'PB','adm1_code' => 'ID91','adm1_id' => '33'),
  array('id' => '484','code' => 'ID9104','name' => 'Teluk Bintuni','country_id' => 'ID','state_code' => 'PB','adm1_code' => 'ID91','adm1_id' => '33'),
  array('id' => '485','code' => 'ID9105','name' => 'Manokwari','country_id' => 'ID','state_code' => 'PB','adm1_code' => 'ID91','adm1_id' => '33'),
  array('id' => '486','code' => 'ID9106','name' => 'Sorong Selatan','country_id' => 'ID','state_code' => 'PB','adm1_code' => 'ID91','adm1_id' => '33'),
  array('id' => '487','code' => 'ID9107','name' => 'Sorong','country_id' => 'ID','state_code' => 'PB','adm1_code' => 'ID91','adm1_id' => '33'),
  array('id' => '488','code' => 'ID9108','name' => 'Raja Ampat','country_id' => 'ID','state_code' => 'PB','adm1_code' => 'ID91','adm1_id' => '33'),
  array('id' => '489','code' => 'ID9109','name' => 'Tambrauw','country_id' => 'ID','state_code' => 'PB','adm1_code' => 'ID91','adm1_id' => '33'),
  array('id' => '490','code' => 'ID9110','name' => 'Maybrat','country_id' => 'ID','state_code' => 'PB','adm1_code' => 'ID91','adm1_id' => '33'),
  array('id' => '491','code' => 'ID9111','name' => 'Manokwari Selatan','country_id' => 'ID','state_code' => 'PB','adm1_code' => 'ID91','adm1_id' => '33'),
  array('id' => '492','code' => 'ID9112','name' => 'Pegunungan Arfak','country_id' => 'ID','state_code' => 'PB','adm1_code' => 'ID91','adm1_id' => '33'),
  array('id' => '493','code' => 'ID9171','name' => 'Kota Sorong','country_id' => 'ID','state_code' => 'PB','adm1_code' => 'ID91','adm1_id' => '33'),
  array('id' => '494','code' => 'ID9401','name' => 'Merauke','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '495','code' => 'ID9402','name' => 'Jayawijaya','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '496','code' => 'ID9403','name' => 'Jayapura','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '497','code' => 'ID9404','name' => 'Nabire','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '498','code' => 'ID9408','name' => 'Kepulauan Yapen','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '499','code' => 'ID9409','name' => 'Biak Numfor','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '500','code' => 'ID9410','name' => 'Paniai','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '501','code' => 'ID9411','name' => 'Puncak Jaya','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '502','code' => 'ID9412','name' => 'Mimika','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '503','code' => 'ID9413','name' => 'Boven Digoel','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '504','code' => 'ID9414','name' => 'Mappi','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '505','code' => 'ID9415','name' => 'Asmat','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '506','code' => 'ID9416','name' => 'Yahukimo','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '507','code' => 'ID9417','name' => 'Pegunungan Bintang','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '508','code' => 'ID9418','name' => 'Tolikara','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '509','code' => 'ID9419','name' => 'Sarmi','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '510','code' => 'ID9420','name' => 'Keerom','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '511','code' => 'ID9426','name' => 'Waropen','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '512','code' => 'ID9427','name' => 'Supiori','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '513','code' => 'ID9428','name' => 'Mamberamo Raya','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '514','code' => 'ID9429','name' => 'Nduga','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '515','code' => 'ID9430','name' => 'Lanny Jaya','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '516','code' => 'ID9431','name' => 'Mamberamo Tengah','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '517','code' => 'ID9432','name' => 'Yalimo','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '518','code' => 'ID9433','name' => 'Puncak','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '519','code' => 'ID9434','name' => 'Dogiyai','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '520','code' => 'ID9435','name' => 'Intan Jaya','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '521','code' => 'ID9436','name' => 'Deiyai','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34'),
  array('id' => '522','code' => 'ID9471','name' => 'Kota Jayapura','country_id' => 'ID','state_code' => 'PA','adm1_code' => 'ID94','adm1_id' => '34')
);
