<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.0.2
 */

/**
 * Database `world_x`
 */

/* `world_x`.`world_currencies` */
return array(
  array('code' => 'AED','name' => 'United Arab Emirates Dirham','symbol' => 'د.إ'),
  array('code' => 'AFN','name' => 'Afghanistani Afghani','symbol' => '؋'),
  array('code' => 'ALL','name' => 'Albanian Lek','symbol' => 'Lek'),
  array('code' => 'AMD','name' => 'Armenian Dram','symbol' => 'դր.'),
  array('code' => 'AOA','name' => 'Angolan Kwanza','symbol' => 'Kz'),
  array('code' => 'ARS','name' => 'Argentine Peso','symbol' => '$'),
  array('code' => 'AUD','name' => 'Australian Dollar','symbol' => '$'),
  array('code' => 'AWG','name' => 'Aruban florin','symbol' => NULL),
  array('code' => 'AZN','name' => 'Azerbaijani Manat','symbol' => '₼'),
  array('code' => 'BAM','name' => 'Bosnia-Herzegovina Convertible Mark','symbol' => 'KM'),
  array('code' => 'BBD','name' => 'Barbados Dollar','symbol' => '$'),
  array('code' => 'BDT','name' => 'Bangladeshi Taka','symbol' => '৳'),
  array('code' => 'BGN','name' => 'Bulgarian Lev','symbol' => 'лв'),
  array('code' => 'BHD','name' => 'Bahraini Dinar','symbol' => '.د.ب'),
  array('code' => 'BIF','name' => 'Burundian Franc','symbol' => 'FBu'),
  array('code' => 'BMD','name' => 'Bermuda Dollar','symbol' => NULL),
  array('code' => 'BND','name' => 'Brunei Dollar','symbol' => '$'),
  array('code' => 'BOB','name' => 'Bolivian Boliviano','symbol' => '$b'),
  array('code' => 'BRL','name' => 'Brazilian Real','symbol' => 'R$'),
  array('code' => 'BSD','name' => 'Bahamian Dollar','symbol' => '$'),
  array('code' => 'BTN','name' => 'Bhutanese Ngultrum','symbol' => 'Nu.'),
  array('code' => 'BWP','name' => 'Botswana Pula','symbol' => 'P'),
  array('code' => 'BYR','name' => 'Belarusian Ruble','symbol' => 'Br'),
  array('code' => 'BZD','name' => 'Belize Dollar','symbol' => 'BZ$'),
  array('code' => 'CAD','name' => 'Canadian Dollar','symbol' => '$'),
  array('code' => 'CDF','name' => 'Congolese franc','symbol' => 'FC'),
  array('code' => 'CHF','name' => 'Swiss Franc','symbol' => 'CHF'),
  array('code' => 'CLP','name' => 'Chilean Peso','symbol' => '$'),
  array('code' => 'CNY','name' => 'Chinese Yuan Renminbi','symbol' => '¥'),
  array('code' => 'COP','name' => 'Colombian Peso','symbol' => '$'),
  array('code' => 'CRC','name' => 'Costa Rican Colon','symbol' => '₡'),
  array('code' => 'CUC','name' => 'Cuban Convertible Peso','symbol' => '$'),
  array('code' => 'CVE','name' => 'Cape Verde Escudo','symbol' => '$'),
  array('code' => 'CYP','name' => 'Cypriot Pound','symbol' => '£'),
  array('code' => 'CZK','name' => 'Czech Koruna','symbol' => 'Kč'),
  array('code' => 'DJF','name' => 'Djiboutian Franc','symbol' => 'Fdj'),
  array('code' => 'DKK','name' => 'Danish Krone','symbol' => 'kr.'),
  array('code' => 'DOP','name' => 'Dominican Peso','symbol' => 'RD$'),
  array('code' => 'DZD','name' => 'Algerian Dinar','symbol' => 'دج'),
  array('code' => 'EEK','name' => 'Estonian Kroon','symbol' => 'EEK'),
  array('code' => 'EGP','name' => 'Egyptian Pound','symbol' => '£'),
  array('code' => 'ERN','name' => 'Eritrean Nakfa','symbol' => 'ናቕፋ'),
  array('code' => 'ETB','name' => 'Ethiopian Birr','symbol' => 'ብር'),
  array('code' => 'EUR','name' => 'European Euro','symbol' => '€'),
  array('code' => 'FJD','name' => 'Fiji Dollar','symbol' => '$'),
  array('code' => 'GBP','name' => 'United Kingdom Pound Sterling','symbol' => '£'),
  array('code' => 'GEL','name' => 'Georgian Lari','symbol' => 'ლ'),
  array('code' => 'GHC','name' => 'Ghanaian Cedi','symbol' => 'GH₵'),
  array('code' => 'GMD','name' => 'Gambian Dalasi','symbol' => 'D'),
  array('code' => 'GNF','name' => 'Guinean Franc','symbol' => 'FG'),
  array('code' => 'GTQ','name' => 'Guatemalan Quetzal','symbol' => 'Q'),
  array('code' => 'GYD','name' => 'Guyanese Dollar','symbol' => '$'),
  array('code' => 'HNL','name' => 'Honduran Lempira','symbol' => 'L'),
  array('code' => 'HRK','name' => 'Croatian Kuna','symbol' => 'kn'),
  array('code' => 'HTG','name' => 'Haitian Gourde','symbol' => 'G'),
  array('code' => 'HUF','name' => 'Hungarian Forint','symbol' => 'Ft'),
  array('code' => 'IDR','name' => 'Indonesian Rupiah','symbol' => 'Rp'),
  array('code' => 'ILS','name' => 'Israeli New Sheqel','symbol' => '₪'),
  array('code' => 'INR','name' => 'Indian Rupee','symbol' => '₹'),
  array('code' => 'IQD','name' => 'Iraqi Dinar','symbol' => 'ع.د'),
  array('code' => 'IRR','name' => 'Iranian Rial','symbol' => '﷼'),
  array('code' => 'ISK','name' => 'Icelandic Krona','symbol' => 'kr'),
  array('code' => 'JMD','name' => 'Jamaican Dollar','symbol' => 'J$'),
  array('code' => 'JOD','name' => 'Jordanian Dinar','symbol' => 'د.ا'),
  array('code' => 'JPY','name' => 'Japanese Yen','symbol' => '¥'),
  array('code' => 'KES','name' => 'Kenyan Shilling','symbol' => 'KSh,'),
  array('code' => 'KGS','name' => 'Kyrgyzstani Som','symbol' => 'лв'),
  array('code' => 'KHR','name' => 'Cambodian Riel','symbol' => '៛'),
  array('code' => 'KMF','name' => 'Comorian Franc','symbol' => 'CF'),
  array('code' => 'KPW','name' => 'North Korean Won','symbol' => '₩'),
  array('code' => 'KRW','name' => 'Korean Won','symbol' => '₩'),
  array('code' => 'KWD','name' => 'Kuwaiti Dinar','symbol' => 'د.ك'),
  array('code' => 'KZT','name' => 'Kazakhstani Tenge','symbol' => 'лв'),
  array('code' => 'LAK','name' => 'Lao Kip','symbol' => '₭'),
  array('code' => 'LBP','name' => 'Lebanese Pound','symbol' => '£'),
  array('code' => 'LKR','name' => 'Sri Lankan Rupee','symbol' => '₨'),
  array('code' => 'LRD','name' => 'Liberian Dollar','symbol' => '$'),
  array('code' => 'LSL','name' => 'Lesotho Loti','symbol' => 'L'),
  array('code' => 'LTL','name' => 'Lithuanian Litas','symbol' => 'Lt'),
  array('code' => 'LVL','name' => 'Latvian Lats','symbol' => 'Ls'),
  array('code' => 'LYD','name' => 'Libyan Dinar','symbol' => 'ل.د'),
  array('code' => 'MAD','name' => 'Moroccan Dirham','symbol' => 'DH'),
  array('code' => 'MDL','name' => 'Moldovan Leu','symbol' => 'L'),
  array('code' => 'MGA','name' => 'Malagasy Ariary','symbol' => 'Ar'),
  array('code' => 'MKD','name' => 'Macedonian Denar','symbol' => 'ден'),
  array('code' => 'MMK','name' => 'Myanmar Kyat','symbol' => 'K'),
  array('code' => 'MNT','name' => 'Mongolian Tugrik','symbol' => '₮'),
  array('code' => 'MRO','name' => 'Mauritanian Ouguiya','symbol' => 'UM'),
  array('code' => 'MTL','name' => 'Maltese Lira','symbol' => '₤'),
  array('code' => 'MUR','name' => 'Mauritian Rupee','symbol' => '₨'),
  array('code' => 'MVR','name' => 'Maldives Rufiyaa','symbol' => 'Rf'),
  array('code' => 'MWK','name' => 'Malawian Kwacha','symbol' => 'MK'),
  array('code' => 'MXN','name' => 'Mexican Peso','symbol' => '$'),
  array('code' => 'MYR','name' => 'Malaysian Ringgit','symbol' => 'RM'),
  array('code' => 'MZN','name' => 'Mozambican Metical','symbol' => 'MT'),
  array('code' => 'NAD','name' => 'Namibian Dollar','symbol' => '$'),
  array('code' => 'NGN','name' => 'Nigerian Naira','symbol' => '₦'),
  array('code' => 'NIO','name' => 'Nicaraguan Córdoba','symbol' => 'C$'),
  array('code' => 'NOK','name' => 'Norwegian Krone','symbol' => 'kr'),
  array('code' => 'NPR','name' => 'Nepalese Rupee','symbol' => '₨'),
  array('code' => 'NZD','name' => 'New Zealand Dollar','symbol' => '$'),
  array('code' => 'OMR','name' => 'Omani Rial','symbol' => '﷼'),
  array('code' => 'PAB','name' => 'Panamanian Balboa','symbol' => 'B/.'),
  array('code' => 'PEN','name' => 'Peruvian Nuevo Sol','symbol' => 'S/.'),
  array('code' => 'PGK','name' => 'Papua New Guinea Kina','symbol' => 'K'),
  array('code' => 'PHP','name' => 'Philippine Peso','symbol' => '₱'),
  array('code' => 'PKR','name' => 'Pakistan Rupee','symbol' => '₨'),
  array('code' => 'PLN','name' => 'Polish Zloty','symbol' => 'zł'),
  array('code' => 'PYG','name' => 'Paraguay Guarani','symbol' => 'Gs'),
  array('code' => 'QAR','name' => 'Qatari Riyal','symbol' => '﷼'),
  array('code' => 'RON','name' => 'Romanian Leu','symbol' => 'lei'),
  array('code' => 'RSD','name' => 'Serbian Dinar','symbol' => 'Дин.'),
  array('code' => 'RUB','name' => 'Russian Ruble','symbol' => '₽'),
  array('code' => 'RWF','name' => 'Rwandan Franc','symbol' => 'FRw'),
  array('code' => 'SAR','name' => 'Saudi Arabian Riyal','symbol' => '﷼'),
  array('code' => 'SBD','name' => 'Solomon Islands Dollar','symbol' => '$'),
  array('code' => 'SCR','name' => 'Seychelles Rupee','symbol' => '₨'),
  array('code' => 'SDG','name' => 'Sudanese pound','symbol' => 'SD'),
  array('code' => 'SEK','name' => 'Swedish Krona','symbol' => 'kr'),
  array('code' => 'SGD','name' => 'Singapore Dollar','symbol' => '$'),
  array('code' => 'SKK','name' => 'Slovak Koruna','symbol' => 'Sk'),
  array('code' => 'SLL','name' => 'Sierra Leonean Leone','symbol' => 'Le'),
  array('code' => 'SOS','name' => 'Somali Shilling','symbol' => 'S'),
  array('code' => 'SRD','name' => 'Suriname Dollar','symbol' => '$'),
  array('code' => 'SSP','name' => 'South Sudanese pound','symbol' => '£'),
  array('code' => 'STD','name' => 'Sao Tome Dobra','symbol' => 'Db'),
  array('code' => 'SYP','name' => 'Syrian Pound','symbol' => '£'),
  array('code' => 'SZL','name' => 'Swazi Lilangeni','symbol' => 'E'),
  array('code' => 'THB','name' => 'Thai Baht','symbol' => '฿'),
  array('code' => 'TJS','name' => 'Tajikistan Somoni','symbol' => 'ЅM'),
  array('code' => 'TMM','name' => 'Turkmenistani Manat','symbol' => 'T'),
  array('code' => 'TND','name' => 'Tunisian Dinar','symbol' => 'د.ت'),
  array('code' => 'TOP','name' => 'Tongan Pa\'Anga','symbol' => 'T$'),
  array('code' => 'TRY','name' => 'Turkish New Lira','symbol' => '₺'),
  array('code' => 'TTD','name' => 'Trinidad and Tobago Dollar','symbol' => 'TT$'),
  array('code' => 'TWD','name' => 'New Taiwan Dollar','symbol' => 'NT$'),
  array('code' => 'TZS','name' => 'Tanzanian Shilling','symbol' => 'TSh'),
  array('code' => 'UAH','name' => 'Ukrainian Hryvnia','symbol' => '₴'),
  array('code' => 'UGX','name' => 'Ugandan Shilling','symbol' => 'USh'),
  array('code' => 'USD','name' => 'United States Dollar','symbol' => '$'),
  array('code' => 'UYU','name' => 'Uruguayan peso','symbol' => '$U'),
  array('code' => 'UZS','name' => 'Uzbekistani Som','symbol' => 'лв'),
  array('code' => 'VEF','name' => 'Venezuelan Bolivar','symbol' => 'Bs'),
  array('code' => 'VND','name' => 'Viet Nam Dong','symbol' => '₫'),
  array('code' => 'WST','name' => 'Samoan Tala','symbol' => 'WS$'),
  array('code' => 'XAF','name' => 'Central African CFA','symbol' => 'FCFA'),
  array('code' => 'XCD','name' => 'East Caribbean Dollar','symbol' => '$'),
  array('code' => 'XOF','name' => 'West African CFA','symbol' => 'CFA'),
  array('code' => 'YER','name' => 'Yemeni Rial','symbol' => '﷼'),
  array('code' => 'ZAR','name' => 'South African Rand','symbol' => 'R'),
  array('code' => 'ZMK','name' => 'Zambian Kwacha','symbol' => 'ZK'),
  array('code' => 'ZWD','name' => 'Zimbabwean Dollar','symbol' => '$')
);
