<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.0.2
 */

/**
 * Database `midware_master_db`
 */

/* `midware_master_db`.`world_timezone_abbreviations` */
return array(
  array('id' => '1','code' => 'WET','name' => 'Western European Time','utc_offset' => 'UTC'),
  array('id' => '2','code' => 'UTC','name' => 'Coordinated Universal Time','utc_offset' => 'UTC'),
  array('id' => '3','code' => 'UCT','name' => 'Coordinated Universal Time','utc_offset' => 'UTC'),
  array('id' => '4','code' => 'GMT','name' => 'Greenwich Mean Time','utc_offset' => 'UTC'),
  array('id' => '5','code' => 'Z','name' => 'Zulu Time (Coordinated Universal Time)','utc_offset' => 'UTC'),
  array('id' => '6','code' => 'BIT','name' => 'Baker Island Time','utc_offset' => '-12:00'),
  array('id' => '7','code' => 'NUT','name' => 'Niue Time','utc_offset' => '-11:00'),
  array('id' => '8','code' => 'SST','name' => 'Samoa Standard Time','utc_offset' => '-11:00'),
  array('id' => '9','code' => 'CKT','name' => 'Cook Island Time','utc_offset' => '-10:00'),
  array('id' => '10','code' => 'TAHT','name' => 'Tahiti Time','utc_offset' => '-10:00'),
  array('id' => '11','code' => 'HST','name' => 'Hawaii Standard Time','utc_offset' => '-10:00'),
  array('id' => '12','code' => 'HAST','name' => 'Hawaii-Aleutian Standard Time','utc_offset' => '-10:00'),
  array('id' => '13','code' => 'MIT','name' => 'Marquesas Islands Time','utc_offset' => '-09:30'),
  array('id' => '14','code' => 'MART','name' => 'Marquesas Islands Time','utc_offset' => '-09:30'),
  array('id' => '15','code' => 'HADT','name' => 'Hawaii-Aleutian Daylight Time','utc_offset' => '-09:00'),
  array('id' => '16','code' => 'AKST','name' => 'Alaska Standard Time','utc_offset' => '-09:00'),
  array('id' => '17','code' => 'GIT','name' => 'Gambier Island Time','utc_offset' => '-09:00'),
  array('id' => '18','code' => 'GAMT','name' => 'Gambier Islands','utc_offset' => '-09:00'),
  array('id' => '19','code' => 'PST','name' => 'Pacific Standard Time (North America)','utc_offset' => '-08:00'),
  array('id' => '20','code' => 'CIST','name' => 'Clipperton Island Standard Time','utc_offset' => '-08:00'),
  array('id' => '21','code' => 'AKDT','name' => 'Alaska Daylight Time','utc_offset' => '-08:00'),
  array('id' => '22','code' => 'PDT','name' => 'Pacific Daylight Time (North America)','utc_offset' => '-07:00'),
  array('id' => '23','code' => 'MST','name' => 'Mountain Standard Time (North America)','utc_offset' => '-07:00'),
  array('id' => '24','code' => 'EAST','name' => 'Easter Island Standard Time','utc_offset' => '-06:00'),
  array('id' => '25','code' => 'GALT','name' => 'Galapagos Time','utc_offset' => '-06:00'),
  array('id' => '26','code' => 'CST','name' => 'Central Standard Time (North America)','utc_offset' => '-06:00'),
  array('id' => '27','code' => 'MDT','name' => 'Mountain Daylight Time (North America)','utc_offset' => '-06:00'),
  array('id' => '28','code' => 'ECT','name' => 'Ecuador Time','utc_offset' => '-05:00'),
  array('id' => '29','code' => 'EASST','name' => 'Easter Island Standard Summer Time','utc_offset' => '-05:00'),
  array('id' => '30','code' => 'COT','name' => 'Colombia Time','utc_offset' => '-05:00'),
  array('id' => '31','code' => 'EST','name' => 'Eastern Standard Time (North America)','utc_offset' => '-05:00'),
  array('id' => '32','code' => 'PET','name' => 'Peru Time','utc_offset' => '-05:00'),
  array('id' => '33','code' => 'CST','name' => 'Cuba Standard Time','utc_offset' => '-05:00'),
  array('id' => '34','code' => 'CDT','name' => 'Central Daylight Time (North America)','utc_offset' => '-05:00'),
  array('id' => '35','code' => 'VET','name' => 'Venezuelan Standard Time','utc_offset' => '-04:30'),
  array('id' => '36','code' => 'GYT','name' => 'Guyana Time','utc_offset' => '-04:00'),
  array('id' => '37','code' => 'AST','name' => 'Atlantic Standard Time','utc_offset' => '-04:00'),
  array('id' => '38','code' => 'BOT','name' => 'Bolivia Time','utc_offset' => '-04:00'),
  array('id' => '39','code' => 'ECT','name' => 'Eastern Caribbean Time (does not recognise DST)','utc_offset' => '-04:00'),
  array('id' => '40','code' => 'EDT','name' => 'Eastern Daylight Time (North America)','utc_offset' => '-04:00'),
  array('id' => '41','code' => 'COST','name' => 'Colombia Summer Time','utc_offset' => '-04:00'),
  array('id' => '42','code' => 'CLT','name' => 'Chile Standard Time','utc_offset' => '-04:00'),
  array('id' => '43','code' => 'FKT','name' => 'Falkland Islands Time','utc_offset' => '-04:00'),
  array('id' => '44','code' => 'AMT','name' => 'Amazon Time','utc_offset' => '-04:00'),
  array('id' => '45','code' => 'PYT','name' => 'Paraguay Time (South America)','utc_offset' => '-04:00'),
  array('id' => '46','code' => 'CDT','name' => 'Cuba Daylight Time','utc_offset' => '-04:00'),
  array('id' => '47','code' => 'NT','name' => 'Newfoundland Time','utc_offset' => '-03:30'),
  array('id' => '48','code' => 'NST','name' => 'Newfoundland Standard Time','utc_offset' => '-03:30'),
  array('id' => '49','code' => 'SRT','name' => 'Suriname Time','utc_offset' => '-03:00'),
  array('id' => '50','code' => 'ADT','name' => 'Atlantic Daylight Time','utc_offset' => '-03:00'),
  array('id' => '51','code' => 'ROTT','name' => 'Rothera Research Station Time','utc_offset' => '-03:00'),
  array('id' => '52','code' => 'UYT','name' => 'Uruguay Standard Time','utc_offset' => '-03:00'),
  array('id' => '53','code' => 'ART','name' => 'Argentina Time','utc_offset' => '-03:00'),
  array('id' => '54','code' => 'AMST','name' => 'Amazon Summer Time','utc_offset' => '-03:00'),
  array('id' => '55','code' => 'GFT','name' => 'French Guiana Time','utc_offset' => '-03:00'),
  array('id' => '56','code' => 'FKST','name' => 'Falkland Islands Summer Time','utc_offset' => '-03:00'),
  array('id' => '57','code' => 'FKST','name' => 'Falkland Islands Standard Time','utc_offset' => '-03:00'),
  array('id' => '58','code' => 'PYST','name' => 'Paraguay Summer Time (South America)','utc_offset' => '-03:00'),
  array('id' => '59','code' => 'PMST','name' => 'Saint Pierre and Miquelon Standard Time','utc_offset' => '-03:00'),
  array('id' => '60','code' => 'BRT','name' => 'Brasilia Time','utc_offset' => '-03:00'),
  array('id' => '61','code' => 'CLST','name' => 'Chile Summer Time','utc_offset' => '-03:00'),
  array('id' => '62','code' => 'NDT','name' => 'Newfoundland Daylight Time','utc_offset' => '-02:30'),
  array('id' => '63','code' => 'FNT','name' => 'Fernando de Noronha Time','utc_offset' => '-02:00'),
  array('id' => '64','code' => 'PMDT','name' => 'Saint Pierre and Miquelon Daylight time','utc_offset' => '-02:00'),
  array('id' => '65','code' => 'UYST','name' => 'Uruguay Summer Time','utc_offset' => '-02:00'),
  array('id' => '66','code' => 'GST','name' => 'South Georgia and the South Sandwich Islands','utc_offset' => '-02:00'),
  array('id' => '67','code' => 'AZOST','name' => 'Azores Standard Time','utc_offset' => '-01:00'),
  array('id' => '68','code' => 'CVT','name' => 'Cape Verde Time','utc_offset' => '-01:00'),
  array('id' => '69','code' => 'EGT','name' => 'Eastern Greenland Time','utc_offset' => '-01:00'),
  array('id' => '70','code' => 'LINT','name' => 'Line Islands Time','utc_offset' => '+14:00'),
  array('id' => '71','code' => 'CHADT','name' => 'Chatham Daylight Time','utc_offset' => '+13:45'),
  array('id' => '72','code' => 'PHOT','name' => 'Phoenix Island Time','utc_offset' => '+13:00'),
  array('id' => '73','code' => 'NZDT','name' => 'New Zealand Daylight Time','utc_offset' => '+13:00'),
  array('id' => '74','code' => 'TKT','name' => 'Tokelau Time','utc_offset' => '+13:00'),
  array('id' => '75','code' => 'TOT','name' => 'Tonga Time','utc_offset' => '+13:00'),
  array('id' => '76','code' => 'CHAST','name' => 'Chatham Standard Time','utc_offset' => '+12:45'),
  array('id' => '77','code' => 'MAGT','name' => 'Magadan Time','utc_offset' => '+12:00'),
  array('id' => '78','code' => 'WAKT','name' => 'Wake Island Time','utc_offset' => '+12:00'),
  array('id' => '79','code' => 'NZST','name' => 'New Zealand Standard Time','utc_offset' => '+12:00'),
  array('id' => '80','code' => 'PETT','name' => 'Kamchatka Time','utc_offset' => '+12:00'),
  array('id' => '81','code' => 'GILT','name' => 'Gilbert Island Time','utc_offset' => '+12:00'),
  array('id' => '82','code' => 'MHT','name' => 'Marshall Islands','utc_offset' => '+12:00'),
  array('id' => '83','code' => 'FJT','name' => 'Fiji Time','utc_offset' => '+12:00'),
  array('id' => '84','code' => 'TVT','name' => 'Tuvalu Time','utc_offset' => '+12:00'),
  array('id' => '85','code' => 'NFT','name' => 'Norfolk Time','utc_offset' => '+11:30'),
  array('id' => '86','code' => 'MIST','name' => 'Macquarie Island Station Time','utc_offset' => '+11:00'),
  array('id' => '87','code' => 'PONT','name' => 'Pohnpei Standard Time','utc_offset' => '+11:00'),
  array('id' => '88','code' => 'KOST','name' => 'Kosrae Time','utc_offset' => '+11:00'),
  array('id' => '89','code' => 'VUT','name' => 'Vanuatu Time','utc_offset' => '+11:00'),
  array('id' => '90','code' => 'LHST','name' => 'Lord Howe Summer Time','utc_offset' => '+11:00'),
  array('id' => '91','code' => 'SRET','name' => 'Srednekolymsk Time','utc_offset' => '+11:00'),
  array('id' => '92','code' => 'NCT','name' => 'New Caledonia Time','utc_offset' => '+11:00'),
  array('id' => '93','code' => 'SAKT','name' => 'Sakhalin Island time','utc_offset' => '+11:00'),
  array('id' => '94','code' => 'SBT','name' => 'Solomon Islands Time','utc_offset' => '+11:00'),
  array('id' => '95','code' => 'AEDT','name' => 'Australian Eastern Daylight Savings Time','utc_offset' => '+11:00'),
  array('id' => '96','code' => 'CST','name' => 'Central Summer Time (Australia)','utc_offset' => '+10:30'),
  array('id' => '97','code' => 'ACDT','name' => 'Australian Central Daylight Savings Time','utc_offset' => '+10:30'),
  array('id' => '98','code' => 'LHST','name' => 'Lord Howe Standard Time','utc_offset' => '+10:30'),
  array('id' => '99','code' => 'PGT','name' => 'Papua New Guinea Time','utc_offset' => '+10:00'),
  array('id' => '100','code' => 'DDUT','name' => 'Dumont d\'Urville Time','utc_offset' => '+10:00'),
  array('id' => '101','code' => 'AEST','name' => 'Australian Eastern Standard Time','utc_offset' => '+10:00'),
  array('id' => '102','code' => 'EST','name' => 'Eastern Standard Time (Australia)','utc_offset' => '+10:00'),
  array('id' => '103','code' => 'ChST','name' => 'Chamorro Standard Time','utc_offset' => '+10:00'),
  array('id' => '104','code' => 'VLAT','name' => 'Vladivostok Time','utc_offset' => '+10:00'),
  array('id' => '105','code' => 'CHUT','name' => 'Chuuk Time','utc_offset' => '+10:00'),
  array('id' => '106','code' => 'CST','name' => 'Central Standard Time (Australia)','utc_offset' => '+09:30'),
  array('id' => '107','code' => 'ACST','name' => 'Australian Central Standard Time','utc_offset' => '+09:30'),
  array('id' => '108','code' => 'EIT','name' => 'Eastern Indonesian Time','utc_offset' => '+09:00'),
  array('id' => '109','code' => 'AWDT','name' => 'Australian Western Daylight Time','utc_offset' => '+09:00'),
  array('id' => '110','code' => 'TLT','name' => 'Timor Leste Time','utc_offset' => '+09:00'),
  array('id' => '111','code' => 'YAKT','name' => 'Yakutsk Time','utc_offset' => '+09:00'),
  array('id' => '112','code' => 'KST','name' => 'Korea Standard Time','utc_offset' => '+09:00'),
  array('id' => '113','code' => 'JST','name' => 'Japan Standard Time','utc_offset' => '+09:00'),
  array('id' => '114','code' => 'CWST','name' => 'Central Western Standard Time (Australia) unofficial','utc_offset' => '+08:45'),
  array('id' => '115','code' => 'IRKT','name' => 'Irkutsk Time','utc_offset' => '+08:00'),
  array('id' => '116','code' => 'CT','name' => 'China time','utc_offset' => '+08:00'),
  array('id' => '117','code' => 'AWST','name' => 'Australian Western Standard Time','utc_offset' => '+08:00'),
  array('id' => '118','code' => 'PST','name' => 'Philippine Standard Time','utc_offset' => '+08:00'),
  array('id' => '119','code' => 'MYT','name' => 'Malaysia Time','utc_offset' => '+08:00'),
  array('id' => '120','code' => 'ULAT','name' => 'Ulaanbaatar Time','utc_offset' => '+08:00'),
  array('id' => '121','code' => 'BDT','name' => 'Brunei Time','utc_offset' => '+08:00'),
  array('id' => '122','code' => 'CHOT','name' => 'Choibalsan','utc_offset' => '+08:00'),
  array('id' => '123','code' => 'HKT','name' => 'Hong Kong Time','utc_offset' => '+08:00'),
  array('id' => '124','code' => 'MST','name' => 'Malaysia Standard Time','utc_offset' => '+08:00'),
  array('id' => '125','code' => 'SST','name' => 'Singapore Standard Time','utc_offset' => '+08:00'),
  array('id' => '126','code' => 'ACT','name' => 'ASEAN Common Time','utc_offset' => '+08:00'),
  array('id' => '127','code' => 'CIT','name' => 'Central Indonesia Time','utc_offset' => '+08:00'),
  array('id' => '128','code' => 'CST','name' => 'China Standard Time','utc_offset' => '+08:00'),
  array('id' => '129','code' => 'SGT','name' => 'Singapore Time','utc_offset' => '+08:00'),
  array('id' => '130','code' => 'WST','name' => 'Western Standard Time','utc_offset' => '+08:00'),
  array('id' => '131','code' => 'DAVT','name' => 'Davis Time','utc_offset' => '+07:00'),
  array('id' => '132','code' => 'CXT','name' => 'Christmas Island Time','utc_offset' => '+07:00'),
  array('id' => '133','code' => 'THA','name' => 'Thailand Standard Time','utc_offset' => '+07:00'),
  array('id' => '134','code' => 'HOVT','name' => 'Khovd Time','utc_offset' => '+07:00'),
  array('id' => '135','code' => 'WIT','name' => 'Western Indonesian Time','utc_offset' => '+07:00'),
  array('id' => '136','code' => 'ICT','name' => 'Indochina Time','utc_offset' => '+07:00'),
  array('id' => '137','code' => 'KRAT','name' => 'Krasnoyarsk Time','utc_offset' => '+07:00'),
  array('id' => '138','code' => 'MST','name' => 'Myanmar Standard Time','utc_offset' => '+06:30'),
  array('id' => '139','code' => 'MMT','name' => 'Myanmar Time','utc_offset' => '+06:30'),
  array('id' => '140','code' => 'CCT','name' => 'Cocos Islands Time','utc_offset' => '+06:30'),
  array('id' => '141','code' => 'BTT','name' => 'Bhutan Time','utc_offset' => '+06:00'),
  array('id' => '142','code' => 'BIOT','name' => 'British Indian Ocean Time','utc_offset' => '+06:00'),
  array('id' => '143','code' => 'KGT','name' => 'Kyrgyzstan time','utc_offset' => '+06:00'),
  array('id' => '144','code' => 'VOST','name' => 'Vostok Station Time','utc_offset' => '+06:00'),
  array('id' => '145','code' => 'OMST','name' => 'Omsk Time','utc_offset' => '+06:00'),
  array('id' => '146','code' => 'BST','name' => 'Bangladesh Standard Time','utc_offset' => '+06:00'),
  array('id' => '147','code' => 'NPT','name' => 'Nepal Time','utc_offset' => '+05:45'),
  array('id' => '148','code' => 'SLST','name' => 'Sri Lanka Time','utc_offset' => '+05:30'),
  array('id' => '149','code' => 'IST','name' => 'Indian Standard Time','utc_offset' => '+05:30'),
  array('id' => '150','code' => 'YEKT','name' => 'Yekaterinburg Time','utc_offset' => '+05:00'),
  array('id' => '151','code' => 'TFT','name' => 'Indian/Kerguelen','utc_offset' => '+05:00'),
  array('id' => '152','code' => 'TJT','name' => 'Tajikistan Time','utc_offset' => '+05:00'),
  array('id' => '153','code' => 'AMST','name' => 'Armenia Summer Time','utc_offset' => '+05:00'),
  array('id' => '154','code' => 'UZT','name' => 'Uzbekistan Time','utc_offset' => '+05:00'),
  array('id' => '155','code' => 'PKT','name' => 'Pakistan Standard Time','utc_offset' => '+05:00'),
  array('id' => '156','code' => 'HMT','name' => 'Heard and McDonald Islands Time','utc_offset' => '+05:00'),
  array('id' => '157','code' => 'MVT','name' => 'Maldives Time','utc_offset' => '+05:00'),
  array('id' => '158','code' => 'ORAT','name' => 'Oral Time','utc_offset' => '+05:00'),
  array('id' => '159','code' => 'TMT','name' => 'Turkmenistan Time','utc_offset' => '+05:00'),
  array('id' => '160','code' => 'MAWT','name' => 'Mawson Station Time','utc_offset' => '+05:00'),
  array('id' => '161','code' => 'AFT','name' => 'Afghanistan Time','utc_offset' => '+04:30'),
  array('id' => '162','code' => 'IRDT','name' => 'Iran Daylight Time','utc_offset' => '+04:30'),
  array('id' => '163','code' => 'GET','name' => 'Georgia Standard Time','utc_offset' => '+04:00'),
  array('id' => '164','code' => 'GST','name' => 'Gulf Standard Time','utc_offset' => '+04:00'),
  array('id' => '165','code' => 'AMT','name' => 'Armenia Time','utc_offset' => '+04:00'),
  array('id' => '166','code' => 'MUT','name' => 'Mauritius Time','utc_offset' => '+04:00'),
  array('id' => '167','code' => 'VOLT','name' => 'Volgograd Time','utc_offset' => '+04:00'),
  array('id' => '168','code' => 'AZT','name' => 'Azerbaijan Time','utc_offset' => '+04:00'),
  array('id' => '169','code' => 'SAMT','name' => 'Samara Time','utc_offset' => '+04:00'),
  array('id' => '170','code' => 'RET','name' => 'R?union Time','utc_offset' => '+04:00'),
  array('id' => '171','code' => 'SCT','name' => 'Seychelles Time','utc_offset' => '+04:00'),
  array('id' => '172','code' => 'IRST','name' => 'Iran Standard Time','utc_offset' => '+03:30'),
  array('id' => '173','code' => 'SYOT','name' => 'Showa Station Time','utc_offset' => '+03:00'),
  array('id' => '174','code' => 'IDT','name' => 'Israel Daylight Time','utc_offset' => '+03:00'),
  array('id' => '175','code' => 'IOT','name' => 'Indian Ocean Time','utc_offset' => '+03:00'),
  array('id' => '176','code' => 'FET','name' => 'Further-eastern European Time','utc_offset' => '+03:00'),
  array('id' => '177','code' => 'AST','name' => 'Arabia Standard Time','utc_offset' => '+03:00'),
  array('id' => '178','code' => 'MSK','name' => 'Moscow Time','utc_offset' => '+03:00'),
  array('id' => '179','code' => 'EAT','name' => 'East Africa Time','utc_offset' => '+03:00'),
  array('id' => '180','code' => 'EEDT','name' => 'Eastern European Daylight Time','utc_offset' => '+03:00'),
  array('id' => '181','code' => 'EEST','name' => 'Eastern European Summer Time','utc_offset' => '+03:00'),
  array('id' => '182','code' => 'WAST','name' => 'West Africa Summer Time','utc_offset' => '+02:00'),
  array('id' => '183','code' => 'CEST','name' => 'Central European Summer Time (Cf. HAEC)','utc_offset' => '+02:00'),
  array('id' => '184','code' => 'CAT','name' => 'Central Africa Time','utc_offset' => '+02:00'),
  array('id' => '185','code' => 'SAST','name' => 'South African Standard Time','utc_offset' => '+02:00'),
  array('id' => '186','code' => 'HAEC','name' => 'Heure Avanc?e d\'Europe Centrale francised name for CEST','utc_offset' => '+02:00'),
  array('id' => '187','code' => 'IST','name' => 'Israel Standard Time','utc_offset' => '+02:00'),
  array('id' => '188','code' => 'EET','name' => 'Eastern European Time','utc_offset' => '+02:00'),
  array('id' => '189','code' => 'MEST','name' => 'Middle European Saving Time Same zone as CEST','utc_offset' => '+02:00'),
  array('id' => '190','code' => 'USZ1','name' => 'Kaliningrad Time','utc_offset' => '+02:00'),
  array('id' => '191','code' => 'CEDT','name' => 'Central European Daylight Time','utc_offset' => '+02:00'),
  array('id' => '192','code' => 'DFT','name' => 'AIX specific equivalent of Central European Time[4]','utc_offset' => '+01:00'),
  array('id' => '193','code' => 'WEST','name' => 'Western European Summer Time','utc_offset' => '+01:00'),
  array('id' => '194','code' => 'WEDT','name' => 'Western European Daylight Time','utc_offset' => '+01:00'),
  array('id' => '195','code' => 'WAT','name' => 'West Africa Time','utc_offset' => '+01:00'),
  array('id' => '196','code' => 'BST','name' => 'British Summer Time (British Standard Time from Feb 1968 to Oct 1971)','utc_offset' => '+01:00'),
  array('id' => '197','code' => 'MET','name' => 'Middle European Time Same zone as CET','utc_offset' => '+01:00'),
  array('id' => '198','code' => 'CET','name' => 'Central European Time','utc_offset' => '+01:00'),
  array('id' => '199','code' => 'IST','name' => 'Irish Standard Time','utc_offset' => '+01:00'),
  array('id' => '200','code' => 'EGST','name' => 'Eastern Greenland Summer Time','utc_offset' => '+00:00')
);
