<?php
/**
 * This file is part of the Omnity project.
 *
 * Copyright (c) 2020 Eki Prathama Ramdhani <eq.petrucci@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author Eki Prathama Ramdhani <eq.petrucci@gmail.com>
 * @file   mime_types.php
 * @date   2020-09-29 7:24:57
 */

return collect([
	['mime-type' => 'application/andrew-inset', 'extension' => 'N/A', 'description' => 'Andrew Toolkit'],
	['mime-type' => 'application/applixware', 'extension' => '.aw', 'description' => 'Applixware'],
	['mime-type' => 'application/atom+xml', 'extension' => '.atom', 'description' => 'Atom Syndication Format'],
	[
		'mime-type'   => 'application/atomcat+xml',
		'extension'   => '.atomcat',
		'description' => 'Atom Publishing Protocol',
	],
	[
		'mime-type'   => 'application/atomsvc+xml',
		'extension'   => '.atomsvc',
		'description' => 'Atom Publishing Protocol Service Document',
	],
	[
		'mime-type'   => 'application/ccxml+xml',
		'extension'   => '.ccxml',
		'description' => 'Voice Browser Call Control',
	],
	[
		'mime-type'   => 'application/cdmi-capability',
		'extension'   => '.cdmia',
		'description' => 'Cloud Data Management Interface (CDMI) - Capability',
	],
	[
		'mime-type'   => 'application/cdmi-container',
		'extension'   => '.cdmic',
		'description' => 'Cloud Data Management Interface (CDMI) - Contaimer',
	],
	[
		'mime-type'   => 'application/cdmi-domain',
		'extension'   => '.cdmid',
		'description' => 'Cloud Data Management Interface (CDMI) - Domain',
	],
	[
		'mime-type'   => 'application/cdmi-object',
		'extension'   => '.cdmio',
		'description' => 'Cloud Data Management Interface (CDMI) - Object',
	],
	[
		'mime-type'   => 'application/cdmi-queue',
		'extension'   => '.cdmiq',
		'description' => 'Cloud Data Management Interface (CDMI) - Queue',
	],
	['mime-type' => 'application/cu-seeme', 'extension' => '.cu', 'description' => 'CU-SeeMe'],
	[
		'mime-type'   => 'application/davmount+xml',
		'extension'   => '.davmount',
		'description' => 'Web Distributed Authoring and Versioning',
	],
	[
		'mime-type'   => 'application/dssc+der',
		'extension'   => '.dssc',
		'description' => 'Data Structure for the Security Suitability of Cryptographic Algorithms',
	],
	[
		'mime-type'   => 'application/dssc+xml',
		'extension'   => '.xdssc',
		'description' => 'Data Structure for the Security Suitability of Cryptographic Algorithms',
	],
	['mime-type' => 'application/ecmascript', 'extension' => '.es', 'description' => 'ECMAScript'],
	[
		'mime-type'   => 'application/emma+xml',
		'extension'   => '.emma',
		'description' => 'Extensible MultiModal Annotation',
	],
	['mime-type' => 'application/epub+zip', 'extension' => '.epub', 'description' => 'Electronic Publication'],
	['mime-type' => 'application/exi', 'extension' => '.exi', 'description' => 'Efficient XML Interchange'],
	['mime-type' => 'application/font-tdpfr', 'extension' => '.pfr', 'description' => 'Portable Font Resource'],
	['mime-type' => 'application/gpx+xml', 'extension' => '.gpx', 'description' => 'GPS eXchange Format'],
	['mime-type' => 'application/hyperstudio', 'extension' => '.stk', 'description' => 'Hyperstudio'],
	[
		'mime-type'   => 'application/ipfix',
		'extension'   => '.ipfix',
		'description' => 'Internet Protocol Flow Information Export',
	],
	['mime-type' => 'application/java-archive', 'extension' => '.jar', 'description' => 'Java Archive'],
	[
		'mime-type'   => 'application/java-serialized-object',
		'extension'   => '.ser',
		'description' => 'Java Serialized Object',
	],
	['mime-type' => 'application/java-vm', 'extension' => '.class', 'description' => 'Java Bytecode File'],
	['mime-type' => 'application/javascript', 'extension' => '.js', 'description' => 'JavaScript'],
	[
		'mime-type'   => 'application/json',
		'extension'   => '.json',
		'description' => 'JavaScript Object Notation (JSON)',
	],
	['mime-type' => 'application/mac-binhex40', 'extension' => '.hqx', 'description' => 'Macintosh BinHex 4.0'],
	['mime-type' => 'application/mac-compactpro', 'extension' => '.cpt', 'description' => 'Compact Pro'],
	[
		'mime-type'   => 'application/mads+xml',
		'extension'   => '.mads',
		'description' => 'Metadata Authority  Description Schema',
	],
	['mime-type' => 'application/marc', 'extension' => '.mrc', 'description' => 'MARC Formats'],
	['mime-type' => 'application/marcxml+xml', 'extension' => '.mrcx', 'description' => 'MARC21 XML Schema'],
	['mime-type' => 'application/mathematica', 'extension' => '.ma', 'description' => 'Mathematica Notebooks'],
	[
		'mime-type'   => 'application/mathml+xml',
		'extension'   => '.mathml',
		'description' => 'Mathematical Markup Language',
	],
	['mime-type' => 'application/mbox', 'extension' => '.mbox', 'description' => 'Mbox database files'],
	[
		'mime-type'   => 'application/mediaservercontrol+xml',
		'extension'   => '.mscml',
		'description' => 'Media Server Control Markup Language',
	],
	['mime-type' => 'application/metalink4+xml', 'extension' => '.meta4', 'description' => 'Metalink'],
	[
		'mime-type'   => 'application/mets+xml',
		'extension'   => '.mets',
		'description' => 'Metadata Encoding and Transmission Standard',
	],
	[
		'mime-type'   => 'application/mods+xml',
		'extension'   => '.mods',
		'description' => 'Metadata Object Description Schema',
	],
	['mime-type' => 'application/mp21', 'extension' => '.m21', 'description' => 'MPEG-21'],
	['mime-type' => 'application/mp4', 'extension' => '.mp4', 'description' => 'MPEG4'],
	['mime-type' => 'application/msword', 'extension' => '.doc', 'description' => 'Microsoft Word'],
	['mime-type' => 'application/mxf', 'extension' => '.mxf', 'description' => 'Material Exchange Format'],
	['mime-type' => 'application/octet-stream', 'extension' => '.bin', 'description' => 'Binary Data'],
	['mime-type' => 'application/oda', 'extension' => '.oda', 'description' => 'Office Document Architecture'],
	[
		'mime-type'   => 'application/oebps-package+xml',
		'extension'   => '.opf',
		'description' => 'Open eBook Publication Structure',
	],
	['mime-type' => 'application/ogg', 'extension' => '.ogx', 'description' => 'Ogg'],
	['mime-type' => 'application/onenote', 'extension' => '.onetoc', 'description' => 'Microsoft OneNote'],
	[
		'mime-type'   => 'application/patch-ops-error+xml',
		'extension'   => '.xer',
		'description' => 'XML Patch Framework',
	],
	['mime-type' => 'application/pdf', 'extension' => '.pdf', 'description' => 'Adobe Portable Document Format'],
	['mime-type' => 'application/pgp-encrypted', 'extension' => '.pgp', 'description' => 'Pretty Good Privacy'],
	[
		'mime-type'   => 'application/pgp-signature',
		'extension'   => '.pgp',
		'description' => 'Pretty Good Privacy - Signature',
	],
	['mime-type' => 'application/pics-rules', 'extension' => '.prf', 'description' => 'PICSRules'],
	[
		'mime-type'   => 'application/pkcs10',
		'extension'   => '.p10',
		'description' => 'PKCS #10 - Certification Request Standard',
	],
	[
		'mime-type'   => 'application/pkcs7-mime',
		'extension'   => '.p7m',
		'description' => 'PKCS #7 - Cryptographic Message Syntax Standard',
	],
	[
		'mime-type'   => 'application/pkcs7-signature',
		'extension'   => '.p7s',
		'description' => 'PKCS #7 - Cryptographic Message Syntax Standard',
	],
	[
		'mime-type'   => 'application/pkcs8',
		'extension'   => '.p8',
		'description' => 'PKCS #8 - Private-Key Information Syntax Standard',
	],
	['mime-type' => 'application/pkix-attr-cert', 'extension' => '.ac', 'description' => 'Attribute Certificate'],
	[
		'mime-type'   => 'application/pkix-cert',
		'extension'   => '.cer',
		'description' => 'Internet Public Key Infrastructure - Certificate',
	],
	[
		'mime-type'   => 'application/pkix-crl',
		'extension'   => '.crl',
		'description' => 'Internet Public Key Infrastructure - Certificate Revocation Lists',
	],
	[
		'mime-type'   => 'application/pkix-pkipath',
		'extension'   => '.pkipath',
		'description' => 'Internet Public Key Infrastructure - Certification Path',
	],
	[
		'mime-type'   => 'application/pkixcmp',
		'extension'   => '.pki',
		'description' => 'Internet Public Key Infrastructure - Certificate Management Protocole',
	],
	[
		'mime-type'   => 'application/pls+xml',
		'extension'   => '.pls',
		'description' => 'Pronunciation Lexicon Specification',
	],
	['mime-type' => 'application/postscript', 'extension' => '.ai', 'description' => 'PostScript'],
	['mime-type' => 'application/prs.cww', 'extension' => '.cww', 'description' => 'CU-Writer'],
	[
		'mime-type'   => 'application/pskc+xml',
		'extension'   => '.pskcxml',
		'description' => 'Portable Symmetric Key Container',
	],
	[
		'mime-type'   => 'application/rdf+xml',
		'extension'   => '.rdf',
		'description' => 'Resource Description Framework',
	],
	['mime-type' => 'application/reginfo+xml', 'extension' => '.rif', 'description' => 'IMS Networks'],
	[
		'mime-type'   => 'application/relax-ng-compact-syntax',
		'extension'   => '.rnc',
		'description' => 'Relax NG Compact Syntax',
	],
	[
		'mime-type'   => 'application/resource-lists-diff+xml',
		'extension'   => '.rld',
		'description' => 'XML Resource Lists Diff',
	],
	['mime-type' => 'application/resource-lists+xml', 'extension' => '.rl', 'description' => 'XML Resource Lists'],
	['mime-type' => 'application/rls-services+xml', 'extension' => '.rs', 'description' => 'XML Resource Lists'],
	['mime-type' => 'application/rsd+xml', 'extension' => '.rsd', 'description' => 'Really Simple Discovery'],
	[
		'mime-type'   => 'application/rss+xml',
		'extension'   => '.rss',
		'description' => 'RSS - Really Simple Syndication',
	],
	['mime-type' => 'application/rtf', 'extension' => '.rtf', 'description' => 'Rich Text Format'],
	[
		'mime-type'   => 'application/sbml+xml',
		'extension'   => '.sbml',
		'description' => 'Systems Biology Markup Language',
	],
	[
		'mime-type'   => 'application/scvp-cv-request',
		'extension'   => '.scq',
		'description' => 'Server-Based Certificate Validation Protocol - Validation Request',
	],
	[
		'mime-type'   => 'application/scvp-cv-response',
		'extension'   => '.scs',
		'description' => 'Server-Based Certificate Validation Protocol - Validation Response',
	],
	[
		'mime-type'   => 'application/scvp-vp-request',
		'extension'   => '.spq',
		'description' => 'Server-Based Certificate Validation Protocol - Validation Policies - Request',
	],
	[
		'mime-type'   => 'application/scvp-vp-response',
		'extension'   => '.spp',
		'description' => 'Server-Based Certificate Validation Protocol - Validation Policies - Response',
	],
	['mime-type' => 'application/sdp', 'extension' => '.sdp', 'description' => 'Session Description Protocol'],
	[
		'mime-type'   => 'application/set-payment-initiation',
		'extension'   => '.setpay',
		'description' => 'Secure Electronic Transaction - Payment',
	],
	[
		'mime-type'   => 'application/set-registration-initiation',
		'extension'   => '.setreg',
		'description' => 'Secure Electronic Transaction - Registration',
	],
	['mime-type' => 'application/shf+xml', 'extension' => '.shf', 'description' => 'S Hexdump Format'],
	[
		'mime-type'   => 'application/smil+xml',
		'extension'   => '.smi',
		'description' => 'Synchronized Multimedia Integration Language',
	],
	['mime-type' => 'application/sparql-query', 'extension' => '.rq', 'description' => 'SPARQL - Query'],
	['mime-type' => 'application/sparql-results+xml', 'extension' => '.srx', 'description' => 'SPARQL - Results'],
	[
		'mime-type'   => 'application/srgs',
		'extension'   => '.gram',
		'description' => 'Speech Recognition Grammar Specification',
	],
	[
		'mime-type'   => 'application/srgs+xml',
		'extension'   => '.grxml',
		'description' => 'Speech Recognition Grammar Specification - XML',
	],
	[
		'mime-type'   => 'application/sru+xml',
		'extension'   => '.sru',
		'description' => 'Search/Retrieve via URL Response Format',
	],
	[
		'mime-type'   => 'application/ssml+xml',
		'extension'   => '.ssml',
		'description' => 'Speech Synthesis Markup Language',
	],
	[
		'mime-type'   => 'application/tei+xml',
		'extension'   => '.tei',
		'description' => 'Text Encoding and Interchange',
	],
	[
		'mime-type'   => 'application/thraud+xml',
		'extension'   => '.tfi',
		'description' => 'Sharing Transaction Fraud Data',
	],
	[
		'mime-type'   => 'application/timestamped-data',
		'extension'   => '.tsd',
		'description' => 'Time Stamped Data Envelope',
	],
	[
		'mime-type'   => 'application/vnd.3gpp.pic-bw-large',
		'extension'   => '.plb',
		'description' => '3rd Generation Partnership Project - Pic Large',
	],
	[
		'mime-type'   => 'application/vnd.3gpp.pic-bw-small',
		'extension'   => '.psb',
		'description' => '3rd Generation Partnership Project - Pic Small',
	],
	[
		'mime-type'   => 'application/vnd.3gpp.pic-bw-var',
		'extension'   => '.pvb',
		'description' => '3rd Generation Partnership Project - Pic Var',
	],
	[
		'mime-type'   => 'application/vnd.3gpp2.tcap',
		'extension'   => '.tcap',
		'description' => '3rd Generation Partnership Project - Transaction Capabilities Application Part',
	],
	[
		'mime-type'   => 'application/vnd.3m.post-it-notes',
		'extension'   => '.pwn',
		'description' => '3M Post It Notes',
	],
	[
		'mime-type'   => 'application/vnd.accpac.simply.aso',
		'extension'   => '.aso',
		'description' => 'Simply Accounting',
	],
	[
		'mime-type'   => 'application/vnd.accpac.simply.imp',
		'extension'   => '.imp',
		'description' => 'Simply Accounting - Data Import',
	],
	['mime-type' => 'application/vnd.acucobol', 'extension' => '.acu', 'description' => 'ACU Cobol'],
	['mime-type' => 'application/vnd.acucorp', 'extension' => '.atc', 'description' => 'ACU Cobol'],
	[
		'mime-type'   => 'application/vnd.adobe.air-application-installer-package+zip',
		'extension'   => '.air',
		'description' => 'Adobe AIR Application',
	],
	['mime-type' => 'application/vnd.adobe.fxp', 'extension' => '.fxp', 'description' => 'Adobe Flex Project'],
	[
		'mime-type'   => 'application/vnd.adobe.xdp+xml',
		'extension'   => '.xdp',
		'description' => 'Adobe XML Data Package',
	],
	[
		'mime-type'   => 'application/vnd.adobe.xfdf',
		'extension'   => '.xfdf',
		'description' => 'Adobe XML Forms Data Format',
	],
	[
		'mime-type'   => 'application/vnd.ahead.space',
		'extension'   => '.ahead',
		'description' => 'Ahead AIR Application',
	],
	[
		'mime-type'   => 'application/vnd.airzip.filesecure.azf',
		'extension'   => '.azf',
		'description' => 'AirZip FileSECURE',
	],
	[
		'mime-type'   => 'application/vnd.airzip.filesecure.azs',
		'extension'   => '.azs',
		'description' => 'AirZip FileSECURE',
	],
	[
		'mime-type'   => 'application/vnd.amazon.ebook',
		'extension'   => '.azw',
		'description' => 'Amazon Kindle eBook format',
	],
	[
		'mime-type'   => 'application/vnd.americandynamics.acc',
		'extension'   => '.acc',
		'description' => 'Active Content Compression',
	],
	['mime-type' => 'application/vnd.amiga.ami', 'extension' => '.ami', 'description' => 'AmigaDE'],
	[
		'mime-type'   => 'application/vnd.android.package-archive',
		'extension'   => '.apk',
		'description' => 'Android Package Archive',
	],
	[
		'mime-type'   => 'application/vnd.anser-web-certificate-issue-initiation',
		'extension'   => '.cii',
		'description' => 'ANSER-WEB Terminal Client - Certificate Issue',
	],
	[
		'mime-type'   => 'application/vnd.anser-web-funds-transfer-initiation',
		'extension'   => '.fti',
		'description' => 'ANSER-WEB Terminal Client - Web Funds Transfer',
	],
	[
		'mime-type'   => 'application/vnd.antix.game-component',
		'extension'   => '.atx',
		'description' => 'Antix Game Player',
	],
	[
		'mime-type'   => 'application/vnd.apple.installer+xml',
		'extension'   => '.mpkg',
		'description' => 'Apple Installer Package',
	],
	[
		'mime-type'   => 'application/vnd.apple.mpegurl',
		'extension'   => '.m3u8',
		'description' => 'Multimedia Playlist Unicode',
	],
	[
		'mime-type'   => 'application/vnd.aristanetworks.swi',
		'extension'   => '.swi',
		'description' => 'Arista Networks Software Image',
	],
	['mime-type' => 'application/vnd.audiograph', 'extension' => '.aep', 'description' => 'Audiograph'],
	[
		'mime-type'   => 'application/vnd.blueice.multipass',
		'extension'   => '.mpm',
		'description' => 'Blueice Research Multipass',
	],
	['mime-type' => 'application/vnd.bmi', 'extension' => '.bmi', 'description' => 'BMI Drawing Data Interchange'],
	['mime-type' => 'application/vnd.businessobjects', 'extension' => '.rep', 'description' => 'BusinessObjects'],
	[
		'mime-type'   => 'application/vnd.chemdraw+xml',
		'extension'   => '.cdxml',
		'description' => 'CambridgeSoft Chem Draw',
	],
	[
		'mime-type'   => 'application/vnd.chipnuts.karaoke-mmd',
		'extension'   => '.mmd',
		'description' => 'Karaoke on Chipnuts Chipsets',
	],
	[
		'mime-type'   => 'application/vnd.cinderella',
		'extension'   => '.cdy',
		'description' => 'Interactive Geometry Software Cinderella',
	],
	['mime-type' => 'application/vnd.claymore', 'extension' => '.cla', 'description' => 'Claymore Data Files'],
	['mime-type' => 'application/vnd.cloanto.rp9', 'extension' => '.rp9', 'description' => 'RetroPlatform Player'],
	['mime-type' => 'application/vnd.clonk.c4group', 'extension' => '.c4g', 'description' => 'Clonk Game'],
	[
		'mime-type'   => 'application/vnd.cluetrust.cartomobile-config',
		'extension'   => '.c11amc',
		'description' => 'ClueTrust CartoMobile - Config',
	],
	[
		'mime-type'   => 'application/vnd.cluetrust.cartomobile-config-pkg',
		'extension'   => '.c11amz',
		'description' => 'ClueTrust CartoMobile - Config Package',
	],
	[
		'mime-type'   => 'application/vnd.commonspace',
		'extension'   => '.csp',
		'description' => 'Sixth Floor Media - CommonSpace',
	],
	['mime-type' => 'application/vnd.contact.cmsg', 'extension' => '.cdbcmsg', 'description' => 'CIM Database'],
	['mime-type' => 'application/vnd.cosmocaller', 'extension' => '.cmc', 'description' => 'CosmoCaller'],
	[
		'mime-type'   => 'application/vnd.crick.clicker',
		'extension'   => '.clkx',
		'description' => 'CrickSoftware - Clicker',
	],
	[
		'mime-type'   => 'application/vnd.crick.clicker.keyboard',
		'extension'   => '.clkk',
		'description' => 'CrickSoftware - Clicker - Keyboard',
	],
	[
		'mime-type'   => 'application/vnd.crick.clicker.palette',
		'extension'   => '.clkp',
		'description' => 'CrickSoftware - Clicker - Palette',
	],
	[
		'mime-type'   => 'application/vnd.crick.clicker.template',
		'extension'   => '.clkt',
		'description' => 'CrickSoftware - Clicker - Template',
	],
	[
		'mime-type'   => 'application/vnd.crick.clicker.wordbank',
		'extension'   => '.clkw',
		'description' => 'CrickSoftware - Clicker - Wordbank',
	],
	[
		'mime-type'   => 'application/vnd.criticaltools.wbs+xml',
		'extension'   => '.wbs',
		'description' => 'Critical Tools - PERT Chart EXPERT',
	],
	['mime-type' => 'application/vnd.ctc-posml', 'extension' => '.pml', 'description' => 'PosML'],
	[
		'mime-type'   => 'application/vnd.cups-ppd',
		'extension'   => '.ppd',
		'description' => 'Adobe PostScript Printer Description File Format',
	],
	['mime-type' => 'application/vnd.curl.car', 'extension' => '.car', 'description' => 'CURL Applet'],
	['mime-type' => 'application/vnd.curl.pcurl', 'extension' => '.pcurl', 'description' => 'CURL Applet'],
	[
		'mime-type'   => 'application/vnd.data-vision.rdz',
		'extension'   => '.rdz',
		'description' => 'RemoteDocs R-Viewer',
	],
	[
		'mime-type'   => 'application/vnd.denovo.fcselayout-link',
		'extension'   => '.fe_launch',
		'description' => 'FCS Express Layout Link',
	],
	['mime-type' => 'application/vnd.dna', 'extension' => '.dna', 'description' => 'New Moon Liftoff/DNA'],
	[
		'mime-type'   => 'application/vnd.dolby.mlp',
		'extension'   => '.mlp',
		'description' => 'Dolby Meridian Lossless Packing',
	],
	['mime-type' => 'application/vnd.dpgraph', 'extension' => '.dpg', 'description' => 'DPGraph'],
	['mime-type' => 'application/vnd.dreamfactory', 'extension' => '.dfac', 'description' => 'DreamFactory'],
	[
		'mime-type'   => 'application/vnd.dvb.ait',
		'extension'   => '.ait',
		'description' => 'Digital Video Broadcasting',
	],
	[
		'mime-type'   => 'application/vnd.dvb.service',
		'extension'   => '.svc',
		'description' => 'Digital Video Broadcasting',
	],
	['mime-type' => 'application/vnd.dynageo', 'extension' => '.geo', 'description' => 'DynaGeo'],
	['mime-type' => 'application/vnd.ecowin.chart', 'extension' => '.mag', 'description' => 'EcoWin Chart'],
	['mime-type' => 'application/vnd.enliven', 'extension' => '.nml', 'description' => 'Enliven Viewer'],
	['mime-type' => 'application/vnd.epson.esf', 'extension' => '.esf', 'description' => 'QUASS Stream Player'],
	['mime-type' => 'application/vnd.epson.msf', 'extension' => '.msf', 'description' => 'QUASS Stream Player'],
	[
		'mime-type'   => 'application/vnd.epson.quickanime',
		'extension'   => '.qam',
		'description' => 'QuickAnime Player',
	],
	[
		'mime-type'   => 'application/vnd.epson.salt',
		'extension'   => '.slt',
		'description' => 'SimpleAnimeLite Player',
	],
	['mime-type' => 'application/vnd.epson.ssf', 'extension' => '.ssf', 'description' => 'QUASS Stream Player'],
	['mime-type' => 'application/vnd.eszigno3+xml', 'extension' => '.es3', 'description' => 'MICROSEC e-Szignï¿½'],
	[
		'mime-type'   => 'application/vnd.ezpix-album',
		'extension'   => '.ez2',
		'description' => 'EZPix Secure Photo Album',
	],
	[
		'mime-type'   => 'application/vnd.ezpix-package',
		'extension'   => '.ez3',
		'description' => 'EZPix Secure Photo Album',
	],
	['mime-type' => 'application/vnd.fdf', 'extension' => '.fdf', 'description' => 'Forms Data Format'],
	[
		'mime-type'   => 'application/vnd.fdsn.seed',
		'extension'   => '.seed',
		'description' => 'Digital Siesmograph Networks - SEED Datafiles',
	],
	['mime-type' => 'application/vnd.flographit', 'extension' => '.gph', 'description' => 'NpGraphIt'],
	['mime-type' => 'application/vnd.fluxtime.clip', 'extension' => '.ftc', 'description' => 'FluxTime Clip'],
	[
		'mime-type'   => 'application/vnd.framemaker',
		'extension'   => '.fm',
		'description' => 'FrameMaker Normal Format',
	],
	['mime-type' => 'application/vnd.frogans.fnc', 'extension' => '.fnc', 'description' => 'Frogans Player'],
	['mime-type' => 'application/vnd.frogans.ltf', 'extension' => '.ltf', 'description' => 'Frogans Player'],
	[
		'mime-type'   => 'application/vnd.fsc.weblaunch',
		'extension'   => '.fsc',
		'description' => 'Friendly Software Corporation',
	],
	['mime-type' => 'application/vnd.fujitsu.oasys', 'extension' => '.oas', 'description' => 'Fujitsu Oasys'],
	['mime-type' => 'application/vnd.fujitsu.oasys2', 'extension' => '.oa2', 'description' => 'Fujitsu Oasys'],
	['mime-type' => 'application/vnd.fujitsu.oasys3', 'extension' => '.oa3', 'description' => 'Fujitsu Oasys'],
	['mime-type' => 'application/vnd.fujitsu.oasysgp', 'extension' => '.fg5', 'description' => 'Fujitsu Oasys'],
	['mime-type' => 'application/vnd.fujitsu.oasysprs', 'extension' => '.bh2', 'description' => 'Fujitsu Oasys'],
	[
		'mime-type'   => 'application/vnd.fujixerox.ddd',
		'extension'   => '.ddd',
		'description' => 'Fujitsu - Xerox 2D CAD Data',
	],
	[
		'mime-type'   => 'application/vnd.fujixerox.docuworks',
		'extension'   => '.xdw',
		'description' => 'Fujitsu - Xerox DocuWorks',
	],
	[
		'mime-type'   => 'application/vnd.fujixerox.docuworks.binder',
		'extension'   => '.xbd',
		'description' => 'Fujitsu - Xerox DocuWorks Binder',
	],
	['mime-type' => 'application/vnd.fuzzysheet', 'extension' => '.fzs', 'description' => 'FuzzySheet'],
	[
		'mime-type'   => 'application/vnd.genomatix.tuxedo',
		'extension'   => '.txd',
		'description' => 'Genomatix Tuxedo Framework',
	],
	['mime-type' => 'application/vnd.geogebra.file', 'extension' => '.ggb', 'description' => 'GeoGebra'],
	['mime-type' => 'application/vnd.geogebra.tool', 'extension' => '.ggt', 'description' => 'GeoGebra'],
	[
		'mime-type'   => 'application/vnd.geometry-explorer',
		'extension'   => '.gex',
		'description' => 'GeoMetry Explorer',
	],
	['mime-type' => 'application/vnd.geonext', 'extension' => '.gxt', 'description' => 'GEONExT and JSXGraph'],
	['mime-type' => 'application/vnd.geoplan', 'extension' => '.g2w', 'description' => 'GeoplanW'],
	['mime-type' => 'application/vnd.geospace', 'extension' => '.g3w', 'description' => 'GeospacW'],
	['mime-type' => 'application/vnd.gmx', 'extension' => '.gmx', 'description' => 'GameMaker ActiveX'],
	[
		'mime-type'   => 'application/vnd.google-earth.kml+xml',
		'extension'   => '.kml',
		'description' => 'Google Earth - KML',
	],
	[
		'mime-type'   => 'application/vnd.google-earth.kmz',
		'extension'   => '.kmz',
		'description' => 'Google Earth - Zipped KML',
	],
	['mime-type' => 'application/vnd.grafeq', 'extension' => '.gqf', 'description' => 'GrafEq'],
	['mime-type' => 'application/vnd.groove-account', 'extension' => '.gac', 'description' => 'Groove - Account'],
	['mime-type' => 'application/vnd.groove-help', 'extension' => '.ghf', 'description' => 'Groove - Help'],
	[
		'mime-type'   => 'application/vnd.groove-identity-message',
		'extension'   => '.gim',
		'description' => 'Groove - Identity Message',
	],
	[
		'mime-type'   => 'application/vnd.groove-injector',
		'extension'   => '.grv',
		'description' => 'Groove - Injector',
	],
	[
		'mime-type'   => 'application/vnd.groove-tool-message',
		'extension'   => '.gtm',
		'description' => 'Groove - Tool Message',
	],
	[
		'mime-type'   => 'application/vnd.groove-tool-template',
		'extension'   => '.tpl',
		'description' => 'Groove - Tool Template',
	],
	['mime-type' => 'application/vnd.groove-vcard', 'extension' => '.vcg', 'description' => 'Groove - Vcard'],
	[
		'mime-type'   => 'application/vnd.hal+xml',
		'extension'   => '.hal',
		'description' => 'Hypertext Application Language',
	],
	[
		'mime-type'   => 'application/vnd.handheld-entertainment+xml',
		'extension'   => '.zmm',
		'description' => 'ZVUE Media Manager',
	],
	[
		'mime-type'   => 'application/vnd.hbci',
		'extension'   => '.hbci',
		'description' => 'Homebanking Computer Interface (HBCI)',
	],
	[
		'mime-type'   => 'application/vnd.hhe.lesson-player',
		'extension'   => '.les',
		'description' => 'Archipelago Lesson Player',
	],
	['mime-type' => 'application/vnd.hp-hpgl', 'extension' => '.hpgl', 'description' => 'HP-GL/2 and HP RTL'],
	[
		'mime-type'   => 'application/vnd.hp-hpid',
		'extension'   => '.hpid',
		'description' => 'Hewlett Packard Instant Delivery',
	],
	[
		'mime-type'   => 'application/vnd.hp-hps',
		'extension'   => '.hps',
		'description' => 'Hewlett-Packard\'s WebPrintSmart',
	],
	[
		'mime-type'   => 'application/vnd.hp-jlyt',
		'extension'   => '.jlt',
		'description' => 'HP Indigo Digital Press - Job Layout Languate',
	],
	[
		'mime-type'   => 'application/vnd.hp-pcl',
		'extension'   => '.pcl',
		'description' => 'HP Printer Command Language',
	],
	[
		'mime-type'   => 'application/vnd.hp-pclxl',
		'extension'   => '.pclxl',
		'description' => 'PCL 6 Enhanced (Formely PCL XL)',
	],
	[
		'mime-type'   => 'application/vnd.hydrostatix.sof-data',
		'extension'   => '.sfd-hdstx',
		'description' => 'Hydrostatix Master Suite',
	],
	[
		'mime-type'   => 'application/vnd.hzn-3d-crossword',
		'extension'   => '.x3d',
		'description' => '3D Crossword Plugin',
	],
	['mime-type' => 'application/vnd.ibm.minipay', 'extension' => '.mpy', 'description' => 'MiniPay'],
	['mime-type' => 'application/vnd.ibm.modcap', 'extension' => '.afp', 'description' => 'MO:DCA-P'],
	[
		'mime-type'   => 'application/vnd.ibm.rights-management',
		'extension'   => '.irm',
		'description' => 'IBM DB2 Rights Manager',
	],
	[
		'mime-type'   => 'application/vnd.ibm.secure-container',
		'extension'   => '.sc',
		'description' => 'IBM Electronic Media Management System - Secure Container',
	],
	['mime-type' => 'application/vnd.iccprofile', 'extension' => '.icc', 'description' => 'ICC profile'],
	['mime-type' => 'application/vnd.igloader', 'extension' => '.igl', 'description' => 'igLoader'],
	[
		'mime-type'   => 'application/vnd.immervision-ivp',
		'extension'   => '.ivp',
		'description' => 'ImmerVision PURE Players',
	],
	[
		'mime-type'   => 'application/vnd.immervision-ivu',
		'extension'   => '.ivu',
		'description' => 'ImmerVision PURE Players',
	],
	['mime-type' => 'application/vnd.insors.igm', 'extension' => '.igm', 'description' => 'IOCOM Visimeet'],
	[
		'mime-type'   => 'application/vnd.intercon.formnet',
		'extension'   => '.xpw',
		'description' => 'Intercon FormNet',
	],
	[
		'mime-type'   => 'application/vnd.intergeo',
		'extension'   => '.i2g',
		'description' => 'Interactive Geometry Software',
	],
	['mime-type' => 'application/vnd.intu.qbo', 'extension' => '.qbo', 'description' => 'Open Financial Exchange'],
	['mime-type' => 'application/vnd.intu.qfx', 'extension' => '.qfx', 'description' => 'Quicken'],
	[
		'mime-type'   => 'application/vnd.ipunplugged.rcprofile',
		'extension'   => '.rcprofile',
		'description' => 'IP Unplugged Roaming Client',
	],
	[
		'mime-type'   => 'application/vnd.irepository.package+xml',
		'extension'   => '.irp',
		'description' => 'iRepository / Lucidoc Editor',
	],
	['mime-type' => 'application/vnd.is-xpr', 'extension' => '.xpr', 'description' => 'Express by Infoseek'],
	[
		'mime-type'   => 'application/vnd.isac.fcs',
		'extension'   => '.fcs',
		'description' => 'International Society for Advancement of Cytometry',
	],
	['mime-type' => 'application/vnd.jam', 'extension' => '.jam', 'description' => 'Lightspeed Audio Lab'],
	[
		'mime-type'   => 'application/vnd.jcp.javame.midlet-rms',
		'extension'   => '.rms',
		'description' => 'Mobile Information Device Profile',
	],
	['mime-type' => 'application/vnd.jisp', 'extension' => '.jisp', 'description' => 'RhymBox'],
	['mime-type' => 'application/vnd.joost.joda-archive', 'extension' => '.joda', 'description' => 'Joda Archive'],
	['mime-type' => 'application/vnd.kahootz', 'extension' => '.ktz', 'description' => 'Kahootz'],
	[
		'mime-type'   => 'application/vnd.kde.karbon',
		'extension'   => '.karbon',
		'description' => 'KDE KOffice Office Suite - Karbon',
	],
	[
		'mime-type'   => 'application/vnd.kde.kchart',
		'extension'   => '.chrt',
		'description' => 'KDE KOffice Office Suite - KChart',
	],
	[
		'mime-type'   => 'application/vnd.kde.kformula',
		'extension'   => '.kfo',
		'description' => 'KDE KOffice Office Suite - Kformula',
	],
	[
		'mime-type'   => 'application/vnd.kde.kivio',
		'extension'   => '.flw',
		'description' => 'KDE KOffice Office Suite - Kivio',
	],
	[
		'mime-type'   => 'application/vnd.kde.kontour',
		'extension'   => '.kon',
		'description' => 'KDE KOffice Office Suite - Kontour',
	],
	[
		'mime-type'   => 'application/vnd.kde.kpresenter',
		'extension'   => '.kpr',
		'description' => 'KDE KOffice Office Suite - Kpresenter',
	],
	[
		'mime-type'   => 'application/vnd.kde.kspread',
		'extension'   => '.ksp',
		'description' => 'KDE KOffice Office Suite - Kspread',
	],
	[
		'mime-type'   => 'application/vnd.kde.kword',
		'extension'   => '.kwd',
		'description' => 'KDE KOffice Office Suite - Kword',
	],
	['mime-type' => 'application/vnd.kenameaapp', 'extension' => '.htke', 'description' => 'Kenamea App'],
	['mime-type' => 'application/vnd.kidspiration', 'extension' => '.kia', 'description' => 'Kidspiration'],
	['mime-type' => 'application/vnd.kinar', 'extension' => '.kne', 'description' => 'Kinar Applications'],
	['mime-type' => 'application/vnd.koan', 'extension' => '.skp', 'description' => 'SSEYO Koan Play File'],
	[
		'mime-type'   => 'application/vnd.kodak-descriptor',
		'extension'   => '.sse',
		'description' => 'Kodak Storyshare',
	],
	[
		'mime-type'   => 'application/vnd.las.las+xml',
		'extension'   => '.lasxml',
		'description' => 'Laser App Enterprise',
	],
	[
		'mime-type'   => 'application/vnd.llamagraphics.life-balance.desktop',
		'extension'   => '.lbd',
		'description' => 'Life Balance - Desktop Edition',
	],
	[
		'mime-type'   => 'application/vnd.llamagraphics.life-balance.exchange+xml',
		'extension'   => '.lbe',
		'description' => 'Life Balance - Exchange Format',
	],
	['mime-type' => 'application/vnd.lotus-1-2-3', 'extension' => '0.123', 'description' => 'Lotus 1-2-3'],
	['mime-type' => 'application/vnd.lotus-approach', 'extension' => '.apr', 'description' => 'Lotus Approach'],
	['mime-type' => 'application/vnd.lotus-freelance', 'extension' => '.pre', 'description' => 'Lotus Freelance'],
	['mime-type' => 'application/vnd.lotus-notes', 'extension' => '.nsf', 'description' => 'Lotus Notes'],
	['mime-type' => 'application/vnd.lotus-organizer', 'extension' => '.org', 'description' => 'Lotus Organizer'],
	['mime-type' => 'application/vnd.lotus-screencam', 'extension' => '.scm', 'description' => 'Lotus Screencam'],
	['mime-type' => 'application/vnd.lotus-wordpro', 'extension' => '.lwp', 'description' => 'Lotus Wordpro'],
	[
		'mime-type'   => 'application/vnd.macports.portpkg',
		'extension'   => '.portpkg',
		'description' => 'MacPorts Port System',
	],
	['mime-type' => 'application/vnd.mcd', 'extension' => '.mcd', 'description' => 'Micro CADAM Helix D&D'],
	['mime-type' => 'application/vnd.medcalcdata', 'extension' => '.mc1', 'description' => 'MedCalc'],
	['mime-type' => 'application/vnd.mediastation.cdkey', 'extension' => '.cdkey', 'description' => 'MediaRemote'],
	[
		'mime-type'   => 'application/vnd.mfer',
		'extension'   => '.mwf',
		'description' => 'Medical Waveform Encoding Format',
	],
	[
		'mime-type'   => 'application/vnd.mfmp',
		'extension'   => '.mfm',
		'description' => 'Melody Format for Mobile Platform',
	],
	['mime-type' => 'application/vnd.micrografx.flo', 'extension' => '.flo', 'description' => 'Micrografx'],
	[
		'mime-type'   => 'application/vnd.micrografx.igx',
		'extension'   => '.igx',
		'description' => 'Micrografx iGrafx Professional',
	],
	[
		'mime-type'   => 'application/vnd.mif',
		'extension'   => '.mif',
		'description' => 'FrameMaker Interchange Format',
	],
	[
		'mime-type'   => 'application/vnd.mobius.daf',
		'extension'   => '.daf',
		'description' => 'Mobius Management Systems - UniversalArchive',
	],
	[
		'mime-type'   => 'application/vnd.mobius.dis',
		'extension'   => '.dis',
		'description' => 'Mobius Management Systems - Distribution Database',
	],
	[
		'mime-type'   => 'application/vnd.mobius.mbk',
		'extension'   => '.mbk',
		'description' => 'Mobius Management Systems - Basket file',
	],
	[
		'mime-type'   => 'application/vnd.mobius.mqy',
		'extension'   => '.mqy',
		'description' => 'Mobius Management Systems - Query File',
	],
	[
		'mime-type'   => 'application/vnd.mobius.msl',
		'extension'   => '.msl',
		'description' => 'Mobius Management Systems - Script Language',
	],
	[
		'mime-type'   => 'application/vnd.mobius.plc',
		'extension'   => '.plc',
		'description' => 'Mobius Management Systems - Policy Definition Language File',
	],
	[
		'mime-type'   => 'application/vnd.mobius.txf',
		'extension'   => '.txf',
		'description' => 'Mobius Management Systems - Topic Index File',
	],
	['mime-type' => 'application/vnd.mophun.application', 'extension' => '.mpn', 'description' => 'Mophun VM'],
	[
		'mime-type'   => 'application/vnd.mophun.certificate',
		'extension'   => '.mpc',
		'description' => 'Mophun Certificate',
	],
	[
		'mime-type'   => 'application/vnd.mozilla.xul+xml',
		'extension'   => '.xul',
		'description' => 'XUL - XML User Interface Language',
	],
	['mime-type' => 'application/vnd.ms-artgalry', 'extension' => '.cil', 'description' => 'Microsoft Artgalry'],
	[
		'mime-type'   => 'application/vnd.ms-cab-compressed',
		'extension'   => '.cab',
		'description' => 'Microsoft Cabinet File',
	],
	['mime-type' => 'application/vnd.ms-excel', 'extension' => '.xls', 'description' => 'Microsoft Excel'],
	[
		'mime-type'   => 'application/vnd.ms-excel.addin.macroenabled.12',
		'extension'   => '.xlam',
		'description' => 'Microsoft Excel - Add-In File',
	],
	[
		'mime-type'   => 'application/vnd.ms-excel.sheet.binary.macroenabled.12',
		'extension'   => '.xlsb',
		'description' => 'Microsoft Excel - Binary Workbook',
	],
	[
		'mime-type'   => 'application/vnd.ms-excel.sheet.macroenabled.12',
		'extension'   => '.xlsm',
		'description' => 'Microsoft Excel - Macro-Enabled Workbook',
	],
	[
		'mime-type'   => 'application/vnd.ms-excel.template.macroenabled.12',
		'extension'   => '.xltm',
		'description' => 'Microsoft Excel - Macro-Enabled Template File',
	],
	[
		'mime-type'   => 'application/vnd.ms-fontobject',
		'extension'   => '.eot',
		'description' => 'Microsoft Embedded OpenType',
	],
	[
		'mime-type'   => 'application/vnd.ms-htmlhelp',
		'extension'   => '.chm',
		'description' => 'Microsoft Html Help File',
	],
	['mime-type' => 'application/vnd.ms-ims', 'extension' => '.ims', 'description' => 'Microsoft Class Server'],
	[
		'mime-type'   => 'application/vnd.ms-lrm',
		'extension'   => '.lrm',
		'description' => 'Microsoft Learning Resource Module',
	],
	[
		'mime-type'   => 'application/vnd.ms-officetheme',
		'extension'   => '.thmx',
		'description' => 'Microsoft Office System Release Theme',
	],
	[
		'mime-type'   => 'application/vnd.ms-pki.seccat',
		'extension'   => '.cat',
		'description' => 'Microsoft Trust UI Provider - Security Catalog',
	],
	[
		'mime-type'   => 'application/vnd.ms-pki.stl',
		'extension'   => '.stl',
		'description' => 'Microsoft Trust UI Provider - Certificate Trust Link',
	],
	[
		'mime-type'   => 'application/vnd.ms-powerpoint',
		'extension'   => '.ppt',
		'description' => 'Microsoft PowerPoint',
	],
	[
		'mime-type'   => 'application/vnd.ms-powerpoint.addin.macroenabled.12',
		'extension'   => '.ppam',
		'description' => 'Microsoft PowerPoint - Add-in file',
	],
	[
		'mime-type'   => 'application/vnd.ms-powerpoint.presentation.macroenabled.12',
		'extension'   => '.pptm',
		'description' => 'Microsoft PowerPoint - Macro-Enabled Presentation File',
	],
	[
		'mime-type'   => 'application/vnd.ms-powerpoint.slide.macroenabled.12',
		'extension'   => '.sldm',
		'description' => 'Microsoft PowerPoint - Macro-Enabled Open XML Slide',
	],
	[
		'mime-type'   => 'application/vnd.ms-powerpoint.slideshow.macroenabled.12',
		'extension'   => '.ppsm',
		'description' => 'Microsoft PowerPoint - Macro-Enabled Slide Show File',
	],
	[
		'mime-type'   => 'application/vnd.ms-powerpoint.template.macroenabled.12',
		'extension'   => '.potm',
		'description' => 'Microsoft PowerPoint - Macro-Enabled Template File',
	],
	['mime-type' => 'application/vnd.ms-project', 'extension' => '.mpp', 'description' => 'Microsoft Project'],
	[
		'mime-type'   => 'application/vnd.ms-word.document.macroenabled.12',
		'extension'   => '.docm',
		'description' => 'Microsoft Word - Macro-Enabled Document',
	],
	[
		'mime-type'   => 'application/vnd.ms-word.template.macroenabled.12',
		'extension'   => '.dotm',
		'description' => 'Microsoft Word - Macro-Enabled Template',
	],
	['mime-type' => 'application/vnd.ms-works', 'extension' => '.wps', 'description' => 'Microsoft Works'],
	[
		'mime-type'   => 'application/vnd.ms-wpl',
		'extension'   => '.wpl',
		'description' => 'Microsoft Windows Media Player Playlist',
	],
	[
		'mime-type'   => 'application/vnd.ms-xpsdocument',
		'extension'   => '.xps',
		'description' => 'Microsoft XML Paper Specification',
	],
	['mime-type' => 'application/vnd.mseq', 'extension' => '.mseq', 'description' => '3GPP MSEQ File'],
	[
		'mime-type'   => 'application/vnd.musician',
		'extension'   => '.mus',
		'description' => 'MUsical Score Interpreted Code Invented  for the ASCII designation of Notation',
	],
	[
		'mime-type'   => 'application/vnd.muvee.style',
		'extension'   => '.msty',
		'description' => 'Muvee Automatic Video Editing',
	],
	['mime-type' => 'application/vnd.neurolanguage.nlu', 'extension' => '.nlu', 'description' => 'neuroLanguage'],
	[
		'mime-type'   => 'application/vnd.noblenet-directory',
		'extension'   => '.nnd',
		'description' => 'NobleNet Directory',
	],
	['mime-type' => 'application/vnd.noblenet-sealer', 'extension' => '.nns', 'description' => 'NobleNet Sealer'],
	['mime-type' => 'application/vnd.noblenet-web', 'extension' => '.nnw', 'description' => 'NobleNet Web'],
	[
		'mime-type'   => 'application/vnd.nokia.n-gage.data',
		'extension'   => '.ngdat',
		'description' => 'N-Gage Game Data',
	],
	[
		'mime-type'   => 'application/vnd.nokia.n-gage.symbian.install',
		'extension'   => '.n-gage',
		'description' => 'N-Gage Game Installer',
	],
	[
		'mime-type'   => 'application/vnd.nokia.radio-preset',
		'extension'   => '.rpst',
		'description' => 'Nokia Radio Application - Preset',
	],
	[
		'mime-type'   => 'application/vnd.nokia.radio-presets',
		'extension'   => '.rpss',
		'description' => 'Nokia Radio Application - Preset',
	],
	[
		'mime-type'   => 'application/vnd.novadigm.edm',
		'extension'   => '.edm',
		'description' => 'Novadigm\'s RADIA and EDM products',
	],
	[
		'mime-type'   => 'application/vnd.novadigm.edx',
		'extension'   => '.edx',
		'description' => 'Novadigm\'s RADIA and EDM products',
	],
	[
		'mime-type'   => 'application/vnd.novadigm.ext',
		'extension'   => '.ext',
		'description' => 'Novadigm\'s RADIA and EDM products',
	],
	[
		'mime-type'   => 'application/vnd.oasis.opendocument.chart',
		'extension'   => '.odc',
		'description' => 'OpenDocument Chart',
	],
	[
		'mime-type'   => 'application/vnd.oasis.opendocument.chart-template',
		'extension'   => '.otc',
		'description' => 'OpenDocument Chart Template',
	],
	[
		'mime-type'   => 'application/vnd.oasis.opendocument.database',
		'extension'   => '.odb',
		'description' => 'OpenDocument Database',
	],
	[
		'mime-type'   => 'application/vnd.oasis.opendocument.formula',
		'extension'   => '.odf',
		'description' => 'OpenDocument Formula',
	],
	[
		'mime-type'   => 'application/vnd.oasis.opendocument.formula-template',
		'extension'   => '.odft',
		'description' => 'OpenDocument Formula Template',
	],
	[
		'mime-type'   => 'application/vnd.oasis.opendocument.graphics',
		'extension'   => '.odg',
		'description' => 'OpenDocument Graphics',
	],
	[
		'mime-type'   => 'application/vnd.oasis.opendocument.graphics-template',
		'extension'   => '.otg',
		'description' => 'OpenDocument Graphics Template',
	],
	[
		'mime-type'   => 'application/vnd.oasis.opendocument.image',
		'extension'   => '.odi',
		'description' => 'OpenDocument Image',
	],
	[
		'mime-type'   => 'application/vnd.oasis.opendocument.image-template',
		'extension'   => '.oti',
		'description' => 'OpenDocument Image Template',
	],
	[
		'mime-type'   => 'application/vnd.oasis.opendocument.presentation',
		'extension'   => '.odp',
		'description' => 'OpenDocument Presentation',
	],
	[
		'mime-type'   => 'application/vnd.oasis.opendocument.presentation-template',
		'extension'   => '.otp',
		'description' => 'OpenDocument Presentation Template',
	],
	[
		'mime-type'   => 'application/vnd.oasis.opendocument.spreadsheet',
		'extension'   => '.ods',
		'description' => 'OpenDocument Spreadsheet',
	],
	[
		'mime-type'   => 'application/vnd.oasis.opendocument.spreadsheet-template',
		'extension'   => '.ots',
		'description' => 'OpenDocument Spreadsheet Template',
	],
	[
		'mime-type'   => 'application/vnd.oasis.opendocument.text',
		'extension'   => '.odt',
		'description' => 'OpenDocument Text',
	],
	[
		'mime-type'   => 'application/vnd.oasis.opendocument.text-master',
		'extension'   => '.odm',
		'description' => 'OpenDocument Text Master',
	],
	[
		'mime-type'   => 'application/vnd.oasis.opendocument.text-template',
		'extension'   => '.ott',
		'description' => 'OpenDocument Text Template',
	],
	[
		'mime-type'   => 'application/vnd.oasis.opendocument.text-web',
		'extension'   => '.oth',
		'description' => 'Open Document Text Web',
	],
	[
		'mime-type'   => 'application/vnd.olpc-sugar',
		'extension'   => '.xo',
		'description' => 'Sugar Linux Application Bundle',
	],
	['mime-type' => 'application/vnd.oma.dd2+xml', 'extension' => '.dd2', 'description' => 'OMA Download Agents'],
	[
		'mime-type'   => 'application/vnd.openofficeorg.extension',
		'extension'   => '.oxt',
		'description' => 'Open Office Extension',
	],
	[
		'mime-type'   => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
		'extension'   => '.pptx',
		'description' => 'Microsoft Office - OOXML - Presentation',
	],
	[
		'mime-type'   => 'application/vnd.openxmlformats-officedocument.presentationml.slide',
		'extension'   => '.sldx',
		'description' => 'Microsoft Office - OOXML - Presentation (Slide)',
	],
	[
		'mime-type'   => 'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
		'extension'   => '.ppsx',
		'description' => 'Microsoft Office - OOXML - Presentation (Slideshow)',
	],
	[
		'mime-type'   => 'application/vnd.openxmlformats-officedocument.presentationml.template',
		'extension'   => '.potx',
		'description' => 'Microsoft Office - OOXML - Presentation Template',
	],
	[
		'mime-type'   => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
		'extension'   => '.xlsx',
		'description' => 'Microsoft Office - OOXML - Spreadsheet',
	],
	[
		'mime-type'   => 'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
		'extension'   => '.xltx',
		'description' => 'Microsoft Office - OOXML - Spreadsheet Template',
	],
	[
		'mime-type'   => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
		'extension'   => '.docx',
		'description' => 'Microsoft Office - OOXML - Word Document',
	],
	[
		'mime-type'   => 'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
		'extension'   => '.dotx',
		'description' => 'Microsoft Office - OOXML - Word Document Template',
	],
	[
		'mime-type'   => 'application/vnd.osgeo.mapguide.package',
		'extension'   => '.mgp',
		'description' => 'MapGuide DBXML',
	],
	['mime-type' => 'application/vnd.osgi.dp', 'extension' => '.dp', 'description' => 'OSGi Deployment Package'],
	['mime-type' => 'application/vnd.palm', 'extension' => '.pdb', 'description' => 'PalmOS Data'],
	['mime-type' => 'application/vnd.pawaafile', 'extension' => '.paw', 'description' => 'PawaaFILE'],
	[
		'mime-type'   => 'application/vnd.pg.format',
		'extension'   => '.str',
		'description' => 'Proprietary P&G Standard Reporting System',
	],
	[
		'mime-type'   => 'application/vnd.pg.osasli',
		'extension'   => '.ei6',
		'description' => 'Proprietary P&G Standard Reporting System',
	],
	['mime-type' => 'application/vnd.picsel', 'extension' => '.efif', 'description' => 'Pcsel eFIF File'],
	[
		'mime-type'   => 'application/vnd.pmi.widget',
		'extension'   => '.wg',
		'description' => 'Qualcomm\'s Plaza Mobile Internet',
	],
	['mime-type' => 'application/vnd.pocketlearn', 'extension' => '.plf', 'description' => 'PocketLearn Viewers'],
	['mime-type' => 'application/vnd.powerbuilder6', 'extension' => '.pbd', 'description' => 'PowerBuilder'],
	[
		'mime-type'   => 'application/vnd.previewsystems.box',
		'extension'   => '.box',
		'description' => 'Preview Systems ZipLock/VBox',
	],
	['mime-type' => 'application/vnd.proteus.magazine', 'extension' => '.mgz', 'description' => 'EFI Proteus'],
	[
		'mime-type'   => 'application/vnd.publishare-delta-tree',
		'extension'   => '.qps',
		'description' => 'PubliShare Objects',
	],
	['mime-type' => 'application/vnd.pvi.ptid1', 'extension' => '.ptid', 'description' => 'Princeton Video Image'],
	['mime-type' => 'application/vnd.quark.quarkxpress', 'extension' => '.qxd', 'description' => 'QuarkXpress'],
	['mime-type' => 'application/vnd.realvnc.bed', 'extension' => '.bed', 'description' => 'RealVNC'],
	[
		'mime-type'   => 'application/vnd.recordare.musicxml',
		'extension'   => '.mxl',
		'description' => 'Recordare Applications',
	],
	[
		'mime-type'   => 'application/vnd.recordare.musicxml+xml',
		'extension'   => '.musicxml',
		'description' => 'Recordare Applications',
	],
	['mime-type' => 'application/vnd.rig.cryptonote', 'extension' => '.cryptonote', 'description' => 'CryptoNote'],
	['mime-type' => 'application/vnd.rim.cod', 'extension' => '.cod', 'description' => 'Blackberry COD File'],
	['mime-type' => 'application/vnd.rn-realmedia', 'extension' => '.rm', 'description' => 'RealMedia'],
	[
		'mime-type'   => 'application/vnd.route66.link66+xml',
		'extension'   => '.link66',
		'description' => 'ROUTE 66 Location Based Services',
	],
	[
		'mime-type'   => 'application/vnd.sailingtracker.track',
		'extension'   => '.st',
		'description' => 'SailingTracker',
	],
	['mime-type' => 'application/vnd.seemail', 'extension' => '.see', 'description' => 'SeeMail'],
	['mime-type' => 'application/vnd.sema', 'extension' => '.sema', 'description' => 'Secured eMail'],
	['mime-type' => 'application/vnd.semd', 'extension' => '.semd', 'description' => 'Secured eMail'],
	['mime-type' => 'application/vnd.semf', 'extension' => '.semf', 'description' => 'Secured eMail'],
	[
		'mime-type'   => 'application/vnd.shana.informed.formdata',
		'extension'   => '.ifm',
		'description' => 'Shana Informed Filler',
	],
	[
		'mime-type'   => 'application/vnd.shana.informed.formtemplate',
		'extension'   => '.itp',
		'description' => 'Shana Informed Filler',
	],
	[
		'mime-type'   => 'application/vnd.shana.informed.interchange',
		'extension'   => '.iif',
		'description' => 'Shana Informed Filler',
	],
	[
		'mime-type'   => 'application/vnd.shana.informed.package',
		'extension'   => '.ipk',
		'description' => 'Shana Informed Filler',
	],
	[
		'mime-type'   => 'application/vnd.simtech-mindmapper',
		'extension'   => '.twd',
		'description' => 'SimTech MindMapper',
	],
	['mime-type' => 'application/vnd.smaf', 'extension' => '.mmf', 'description' => 'SMAF File'],
	[
		'mime-type'   => 'application/vnd.smart.teacher',
		'extension'   => '.teacher',
		'description' => 'SMART Technologies Apps',
	],
	['mime-type' => 'application/vnd.solent.sdkm+xml', 'extension' => '.sdkm', 'description' => 'SudokuMagic'],
	['mime-type' => 'application/vnd.spotfire.dxp', 'extension' => '.dxp', 'description' => 'TIBCO Spotfire'],
	['mime-type' => 'application/vnd.spotfire.sfs', 'extension' => '.sfs', 'description' => 'TIBCO Spotfire'],
	[
		'mime-type'   => 'application/vnd.stardivision.calc',
		'extension'   => '.sdc',
		'description' => 'StarOffice - Calc',
	],
	[
		'mime-type'   => 'application/vnd.stardivision.draw',
		'extension'   => '.sda',
		'description' => 'StarOffice - Draw',
	],
	[
		'mime-type'   => 'application/vnd.stardivision.impress',
		'extension'   => '.sdd',
		'description' => 'StarOffice - Impress',
	],
	[
		'mime-type'   => 'application/vnd.stardivision.math',
		'extension'   => '.smf',
		'description' => 'StarOffice - Math',
	],
	[
		'mime-type'   => 'application/vnd.stardivision.writer',
		'extension'   => '.sdw',
		'description' => 'StarOffice - Writer',
	],
	[
		'mime-type'   => 'application/vnd.stardivision.writer-global',
		'extension'   => '.sgl',
		'description' => 'StarOffice - Writer  (Global)',
	],
	['mime-type' => 'application/vnd.stepmania.stepchart', 'extension' => '.sm', 'description' => 'StepMania'],
	[
		'mime-type'   => 'application/vnd.sun.xml.calc',
		'extension'   => '.sxc',
		'description' => 'OpenOffice - Calc (Spreadsheet)',
	],
	[
		'mime-type'   => 'application/vnd.sun.xml.calc.template',
		'extension'   => '.stc',
		'description' => 'OpenOffice - Calc Template (Spreadsheet)',
	],
	[
		'mime-type'   => 'application/vnd.sun.xml.draw',
		'extension'   => '.sxd',
		'description' => 'OpenOffice - Draw (Graphics)',
	],
	[
		'mime-type'   => 'application/vnd.sun.xml.draw.template',
		'extension'   => '.std',
		'description' => 'OpenOffice - Draw Template (Graphics)',
	],
	[
		'mime-type'   => 'application/vnd.sun.xml.impress',
		'extension'   => '.sxi',
		'description' => 'OpenOffice - Impress (Presentation)',
	],
	[
		'mime-type'   => 'application/vnd.sun.xml.impress.template',
		'extension'   => '.sti',
		'description' => 'OpenOffice - Impress Template (Presentation)',
	],
	[
		'mime-type'   => 'application/vnd.sun.xml.math',
		'extension'   => '.sxm',
		'description' => 'OpenOffice - Math (Formula)',
	],
	[
		'mime-type'   => 'application/vnd.sun.xml.writer',
		'extension'   => '.sxw',
		'description' => 'OpenOffice - Writer (Text - HTML)',
	],
	[
		'mime-type'   => 'application/vnd.sun.xml.writer.global',
		'extension'   => '.sxg',
		'description' => 'OpenOffice - Writer (Text - HTML)',
	],
	[
		'mime-type'   => 'application/vnd.sun.xml.writer.template',
		'extension'   => '.stw',
		'description' => 'OpenOffice - Writer Template (Text - HTML)',
	],
	['mime-type' => 'application/vnd.sus-calendar', 'extension' => '.sus', 'description' => 'ScheduleUs'],
	['mime-type' => 'application/vnd.svd', 'extension' => '.svd', 'description' => 'SourceView Document'],
	[
		'mime-type'   => 'application/vnd.symbian.install',
		'extension'   => '.sis',
		'description' => 'Symbian Install Package',
	],
	[
		'mime-type'   => 'application/vnd.syncml.dm+wbxml',
		'extension'   => '.bdm',
		'description' => 'SyncML - Device Management',
	],
	[
		'mime-type'   => 'application/vnd.syncml.dm+xml',
		'extension'   => '.xdm',
		'description' => 'SyncML - Device Management',
	],
	['mime-type' => 'application/vnd.syncml+xml', 'extension' => '.xsm', 'description' => 'SyncML'],
	[
		'mime-type'   => 'application/vnd.tao.intent-module-archive',
		'extension'   => '.tao',
		'description' => 'Tao Intent',
	],
	['mime-type' => 'application/vnd.tmobile-livetv', 'extension' => '.tmo', 'description' => 'MobileTV'],
	['mime-type' => 'application/vnd.trid.tpt', 'extension' => '.tpt', 'description' => 'TRI Systems Config'],
	[
		'mime-type'   => 'application/vnd.triscape.mxs',
		'extension'   => '.mxs',
		'description' => 'Triscape Map Explorer',
	],
	['mime-type' => 'application/vnd.trueapp', 'extension' => '.tra', 'description' => 'True BASIC'],
	[
		'mime-type'   => 'application/vnd.ufdl',
		'extension'   => '.ufd',
		'description' => 'Universal Forms Description Language',
	],
	[
		'mime-type'   => 'application/vnd.uiq.theme',
		'extension'   => '.utz',
		'description' => 'User Interface Quartz - Theme (Symbian)',
	],
	['mime-type' => 'application/vnd.umajin', 'extension' => '.umj', 'description' => 'UMAJIN'],
	['mime-type' => 'application/vnd.unity', 'extension' => '.unityweb', 'description' => 'Unity 3d'],
	[
		'mime-type'   => 'application/vnd.uoml+xml',
		'extension'   => '.uoml',
		'description' => 'Unique Object Markup Language',
	],
	['mime-type' => 'application/vnd.vcx', 'extension' => '.vcx', 'description' => 'VirtualCatalog'],
	['mime-type' => 'application/vnd.visio', 'extension' => '.vsd', 'description' => 'Microsoft Visio'],
	['mime-type' => 'application/vnd.visio2013', 'extension' => '.vsdx', 'description' => 'Microsoft Visio 2013'],
	['mime-type' => 'application/vnd.visionary', 'extension' => '.vis', 'description' => 'Visionary'],
	['mime-type' => 'application/vnd.vsf', 'extension' => '.vsf', 'description' => 'Viewport+'],
	[
		'mime-type'   => 'application/vnd.wap.wbxml',
		'extension'   => '.wbxml',
		'description' => 'WAP Binary XML (WBXML)',
	],
	[
		'mime-type'   => 'application/vnd.wap.wmlc',
		'extension'   => '.wmlc',
		'description' => 'Compiled Wireless Markup Language (WMLC)',
	],
	['mime-type' => 'application/vnd.wap.wmlscriptc', 'extension' => '.wmlsc', 'description' => 'WMLScript'],
	['mime-type' => 'application/vnd.webturbo', 'extension' => '.wtb', 'description' => 'WebTurbo'],
	[
		'mime-type'   => 'application/vnd.wolfram.player',
		'extension'   => '.nbp',
		'description' => 'Mathematica Notebook Player',
	],
	['mime-type' => 'application/vnd.wordperfect', 'extension' => '.wpd', 'description' => 'Wordperfect'],
	['mime-type' => 'application/vnd.wqd', 'extension' => '.wqd', 'description' => 'SundaHus WQ'],
	['mime-type' => 'application/vnd.wt.stf', 'extension' => '.stf', 'description' => 'Worldtalk'],
	['mime-type' => 'application/vnd.xara', 'extension' => '.xar', 'description' => 'CorelXARA'],
	[
		'mime-type'   => 'application/vnd.xfdl',
		'extension'   => '.xfdl',
		'description' => 'Extensible Forms Description Language',
	],
	[
		'mime-type'   => 'application/vnd.yamaha.hv-dic',
		'extension'   => '.hvd',
		'description' => 'HV Voice Dictionary',
	],
	['mime-type' => 'application/vnd.yamaha.hv-script', 'extension' => '.hvs', 'description' => 'HV Script'],
	[
		'mime-type'   => 'application/vnd.yamaha.hv-voice',
		'extension'   => '.hvp',
		'description' => 'HV Voice Parameter',
	],
	[
		'mime-type'   => 'application/vnd.yamaha.openscoreformat',
		'extension'   => '.osf',
		'description' => 'Open Score Format',
	],
	[
		'mime-type'   => 'application/vnd.yamaha.openscoreformat.osfpvg+xml',
		'extension'   => '.osfpvg',
		'description' => 'OSFPVG',
	],
	['mime-type' => 'application/vnd.yamaha.smaf-audio', 'extension' => '.saf', 'description' => 'SMAF Audio'],
	['mime-type' => 'application/vnd.yamaha.smaf-phrase', 'extension' => '.spf', 'description' => 'SMAF Phrase'],
	[
		'mime-type'   => 'application/vnd.yellowriver-custom-menu',
		'extension'   => '.cmp',
		'description' => 'CustomMenu',
	],
	['mime-type' => 'application/vnd.zul', 'extension' => '.zir', 'description' => 'Z.U.L. Geometry'],
	['mime-type' => 'application/vnd.zzazz.deck+xml', 'extension' => '.zaz', 'description' => 'Zzazz Deck'],
	['mime-type' => 'application/voicexml+xml', 'extension' => '.vxml', 'description' => 'VoiceXML'],
	[
		'mime-type'   => 'application/widget',
		'extension'   => '.wgt',
		'description' => 'Widget Packaging and XML Configuration',
	],
	['mime-type' => 'application/winhlp', 'extension' => '.hlp', 'description' => 'WinHelp'],
	[
		'mime-type'   => 'application/wsdl+xml',
		'extension'   => '.wsdl',
		'description' => 'WSDL - Web Services Description Language',
	],
	[
		'mime-type'   => 'application/wspolicy+xml',
		'extension'   => '.wspolicy',
		'description' => 'Web Services Policy',
	],
	['mime-type' => 'application/x-7z-compressed', 'extension' => '.7z', 'description' => '7-Zip'],
	['mime-type' => 'application/x-abiword', 'extension' => '.abw', 'description' => 'AbiWord'],
	['mime-type' => 'application/x-ace-compressed', 'extension' => '.ace', 'description' => 'Ace Archive'],
	['mime-type' => 'application/x-apple-diskimage', 'extension' => '.dmg', 'description' => 'Apple Disk Image'],
	[
		'mime-type'   => 'application/x-authorware-bin',
		'extension'   => '.aab',
		'description' => 'Adobe (Macropedia) Authorware - Binary File',
	],
	[
		'mime-type'   => 'application/x-authorware-map',
		'extension'   => '.aam',
		'description' => 'Adobe (Macropedia) Authorware - Map',
	],
	[
		'mime-type'   => 'application/x-authorware-seg',
		'extension'   => '.aas',
		'description' => 'Adobe (Macropedia) Authorware - Segment File',
	],
	['mime-type' => 'application/x-bcpio', 'extension' => '.bcpio', 'description' => 'Binary CPIO Archive'],
	['mime-type' => 'application/x-bittorrent', 'extension' => '.torrent', 'description' => 'BitTorrent'],
	['mime-type' => 'application/x-bzip', 'extension' => '.bz', 'description' => 'Bzip Archive'],
	['mime-type' => 'application/x-bzip2', 'extension' => '.bz2', 'description' => 'Bzip2 Archive'],
	['mime-type' => 'application/x-cdlink', 'extension' => '.vcd', 'description' => 'Video CD'],
	['mime-type' => 'application/x-chat', 'extension' => '.chat', 'description' => 'pIRCh'],
	[
		'mime-type'   => 'application/x-chess-pgn',
		'extension'   => '.pgn',
		'description' => 'Portable Game Notation (Chess Games)',
	],
	['mime-type' => 'application/x-cpio', 'extension' => '.cpio', 'description' => 'CPIO Archive'],
	['mime-type' => 'application/x-csh', 'extension' => '.csh', 'description' => 'C Shell Script'],
	['mime-type' => 'application/x-debian-package', 'extension' => '.deb', 'description' => 'Debian Package'],
	['mime-type' => 'application/x-director', 'extension' => '.dir', 'description' => 'Adobe Shockwave Player'],
	['mime-type' => 'application/x-doom', 'extension' => '.wad', 'description' => 'Doom Video Game'],
	[
		'mime-type'   => 'application/x-dtbncx+xml',
		'extension'   => '.ncx',
		'description' => 'Navigation Control file for XML (for ePub)',
	],
	['mime-type' => 'application/x-dtbook+xml', 'extension' => '.dtb', 'description' => 'Digital Talking Book'],
	[
		'mime-type'   => 'application/x-dtbresource+xml',
		'extension'   => '.res',
		'description' => 'Digital Talking Book - Resource File',
	],
	[
		'mime-type'   => 'application/x-dvi',
		'extension'   => '.dvi',
		'description' => 'Device Independent File Format (DVI)',
	],
	[
		'mime-type'   => 'application/x-font-bdf',
		'extension'   => '.bdf',
		'description' => 'Glyph Bitmap Distribution Format',
	],
	['mime-type' => 'application/x-font-ghostscript', 'extension' => '.gsf', 'description' => 'Ghostscript Font'],
	['mime-type' => 'application/x-font-linux-psf', 'extension' => '.psf', 'description' => 'PSF Fonts'],
	['mime-type' => 'application/x-font-otf', 'extension' => '.otf', 'description' => 'OpenType Font File'],
	['mime-type' => 'application/x-font-pcf', 'extension' => '.pcf', 'description' => 'Portable Compiled Format'],
	['mime-type' => 'application/x-font-snf', 'extension' => '.snf', 'description' => 'Server Normal Format'],
	['mime-type' => 'application/x-font-ttf', 'extension' => '.ttf', 'description' => 'TrueType Font'],
	['mime-type' => 'application/x-font-type1', 'extension' => '.pfa', 'description' => 'PostScript Fonts'],
	['mime-type' => 'application/x-font-woff', 'extension' => '.woff', 'description' => 'Web Open Font Format'],
	['mime-type' => 'application/x-futuresplash', 'extension' => '.spl', 'description' => 'FutureSplash Animator'],
	['mime-type' => 'application/x-gnumeric', 'extension' => '.gnumeric', 'description' => 'Gnumeric'],
	['mime-type' => 'application/x-gtar', 'extension' => '.gtar', 'description' => 'GNU Tar Files'],
	['mime-type' => 'application/x-hdf', 'extension' => '.hdf', 'description' => 'Hierarchical Data Format'],
	[
		'mime-type'   => 'application/x-java-jnlp-file',
		'extension'   => '.jnlp',
		'description' => 'Java Network Launching Protocol',
	],
	['mime-type' => 'application/x-latex', 'extension' => '.latex', 'description' => 'LaTeX'],
	['mime-type' => 'application/x-mobipocket-ebook', 'extension' => '.prc', 'description' => 'Mobipocket'],
	[
		'mime-type'   => 'application/x-ms-application',
		'extension'   => '.application',
		'description' => 'Microsoft ClickOnce',
	],
	[
		'mime-type'   => 'application/x-ms-wmd',
		'extension'   => '.wmd',
		'description' => 'Microsoft Windows Media Player Download Package',
	],
	[
		'mime-type'   => 'application/x-ms-wmz',
		'extension'   => '.wmz',
		'description' => 'Microsoft Windows Media Player Skin Package',
	],
	[
		'mime-type'   => 'application/x-ms-xbap',
		'extension'   => '.xbap',
		'description' => 'Microsoft XAML Browser Application',
	],
	['mime-type' => 'application/x-msaccess', 'extension' => '.mdb', 'description' => 'Microsoft Access'],
	['mime-type' => 'application/x-msbinder', 'extension' => '.obd', 'description' => 'Microsoft Office Binder'],
	[
		'mime-type'   => 'application/x-mscardfile',
		'extension'   => '.crd',
		'description' => 'Microsoft Information Card',
	],
	['mime-type' => 'application/x-msclip', 'extension' => '.clp', 'description' => 'Microsoft Clipboard Clip'],
	['mime-type' => 'application/x-msdownload', 'extension' => '.exe', 'description' => 'Microsoft Application'],
	['mime-type' => 'application/x-msmediaview', 'extension' => '.mvb', 'description' => 'Microsoft MediaView'],
	[
		'mime-type'   => 'application/x-msmetafile',
		'extension'   => '.wmf',
		'description' => 'Microsoft Windows Metafile',
	],
	['mime-type' => 'application/x-msmoney', 'extension' => '.mny', 'description' => 'Microsoft Money'],
	['mime-type' => 'application/x-mspublisher', 'extension' => '.pub', 'description' => 'Microsoft Publisher'],
	['mime-type' => 'application/x-msschedule', 'extension' => '.scd', 'description' => 'Microsoft Schedule+'],
	[
		'mime-type'   => 'application/x-msterminal',
		'extension'   => '.trm',
		'description' => 'Microsoft Windows Terminal Services',
	],
	['mime-type' => 'application/x-mswrite', 'extension' => '.wri', 'description' => 'Microsoft Wordpad'],
	[
		'mime-type'   => 'application/x-netcdf',
		'extension'   => '.nc',
		'description' => 'Network Common Data Form (NetCDF)',
	],
	[
		'mime-type'   => 'application/x-pkcs12',
		'extension'   => '.p12',
		'description' => 'PKCS #12 - Personal Information Exchange Syntax Standard',
	],
	[
		'mime-type'   => 'application/x-pkcs7-certificates',
		'extension'   => '.p7b',
		'description' => 'PKCS #7 - Cryptographic Message Syntax Standard (Certificates)',
	],
	[
		'mime-type'   => 'application/x-pkcs7-certreqresp',
		'extension'   => '.p7r',
		'description' => 'PKCS #7 - Cryptographic Message Syntax Standard (Certificate Request Response)',
	],
	['mime-type' => 'application/x-rar-compressed', 'extension' => '.rar', 'description' => 'RAR Archive'],
	['mime-type' => 'application/x-sh', 'extension' => '.sh', 'description' => 'Bourne Shell Script'],
	['mime-type' => 'application/x-shar', 'extension' => '.shar', 'description' => 'Shell Archive'],
	['mime-type' => 'application/x-shockwave-flash', 'extension' => '.swf', 'description' => 'Adobe Flash'],
	[
		'mime-type'   => 'application/x-silverlight-app',
		'extension'   => '.xap',
		'description' => 'Microsoft Silverlight',
	],
	['mime-type' => 'application/x-stuffit', 'extension' => '.sit', 'description' => 'Stuffit Archive'],
	['mime-type' => 'application/x-stuffitx', 'extension' => '.sitx', 'description' => 'Stuffit Archive'],
	[
		'mime-type'   => 'application/x-sv4cpio',
		'extension'   => '.sv4cpio',
		'description' => 'System V Release 4 CPIO Archive',
	],
	[
		'mime-type'   => 'application/x-sv4crc',
		'extension'   => '.sv4crc',
		'description' => 'System V Release 4 CPIO Checksum Data',
	],
	['mime-type' => 'application/x-tar', 'extension' => '.tar', 'description' => 'Tar File (Tape Archive)'],
	['mime-type' => 'application/x-tcl', 'extension' => '.tcl', 'description' => 'Tcl Script'],
	['mime-type' => 'application/x-tex', 'extension' => '.tex', 'description' => 'TeX'],
	['mime-type' => 'application/x-tex-tfm', 'extension' => '.tfm', 'description' => 'TeX Font Metric'],
	['mime-type' => 'application/x-texinfo', 'extension' => '.texinfo', 'description' => 'GNU Texinfo Document'],
	[
		'mime-type'   => 'application/x-ustar',
		'extension'   => '.ustar',
		'description' => 'Ustar (Uniform Standard Tape Archive)',
	],
	['mime-type' => 'application/x-wais-source', 'extension' => '.src', 'description' => 'WAIS Source'],
	['mime-type' => 'application/x-x509-ca-cert', 'extension' => '.der', 'description' => 'X.509 Certificate'],
	['mime-type' => 'application/x-xfig', 'extension' => '.fig', 'description' => 'Xfig'],
	['mime-type' => 'application/x-xpinstall', 'extension' => '.xpi', 'description' => 'XPInstall - Mozilla'],
	[
		'mime-type'   => 'application/xcap-diff+xml',
		'extension'   => '.xdf',
		'description' => 'XML Configuration Access Protocol - XCAP Diff',
	],
	[
		'mime-type'   => 'application/xenc+xml',
		'extension'   => '.xenc',
		'description' => 'XML Encryption Syntax and Processing',
	],
	[
		'mime-type'   => 'application/xhtml+xml',
		'extension'   => '.xhtml',
		'description' => 'XHTML - The Extensible HyperText Markup Language',
	],
	['mime-type' => 'application/xml', 'extension' => '.xml', 'description' => 'XML - Extensible Markup Language'],
	['mime-type' => 'application/xml-dtd', 'extension' => '.dtd', 'description' => 'Document Type Definition'],
	[
		'mime-type'   => 'application/xop+xml',
		'extension'   => '.xop',
		'description' => 'XML-Binary Optimized Packaging',
	],
	['mime-type' => 'application/xslt+xml', 'extension' => '.xslt', 'description' => 'XML Transformations'],
	[
		'mime-type'   => 'application/xspf+xml',
		'extension'   => '.xspf',
		'description' => 'XSPF - XML Shareable Playlist Format',
	],
	['mime-type' => 'application/xv+xml', 'extension' => '.mxml', 'description' => 'MXML'],
	['mime-type' => 'application/yang', 'extension' => '.yang', 'description' => 'YANG Data Modeling Language'],
	['mime-type' => 'application/yin+xml', 'extension' => '.yin', 'description' => 'YIN (YANG - XML)'],
	['mime-type' => 'application/zip', 'extension' => '.zip', 'description' => 'Zip Archive'],
	[
		'mime-type'   => 'audio/adpcm',
		'extension'   => '.adp',
		'description' => 'Adaptive differential pulse-code modulation',
	],
	['mime-type' => 'audio/basic', 'extension' => '.au', 'description' => 'Sun Audio - Au file format'],
	[
		'mime-type'   => 'audio/midi',
		'extension'   => '.mid',
		'description' => 'MIDI - Musical Instrument Digital Interface',
	],
	['mime-type' => 'audio/mp4', 'extension' => '.mp4a', 'description' => 'MPEG-4 Audio'],
	['mime-type' => 'audio/mpeg', 'extension' => '.mpga', 'description' => 'MPEG Audio'],
	['mime-type' => 'audio/ogg', 'extension' => '.oga', 'description' => 'Ogg Audio'],
	['mime-type' => 'audio/vnd.dece.audio', 'extension' => '.uva', 'description' => 'DECE Audio'],
	['mime-type' => 'audio/vnd.digital-winds', 'extension' => '.eol', 'description' => 'Digital Winds Music'],
	['mime-type' => 'audio/vnd.dra', 'extension' => '.dra', 'description' => 'DRA Audio'],
	['mime-type' => 'audio/vnd.dts', 'extension' => '.dts', 'description' => 'DTS Audio'],
	['mime-type' => 'audio/vnd.dts.hd', 'extension' => '.dtshd', 'description' => 'DTS High Definition Audio'],
	['mime-type' => 'audio/vnd.lucent.voice', 'extension' => '.lvp', 'description' => 'Lucent Voice'],
	[
		'mime-type'   => 'audio/vnd.ms-playready.media.pya',
		'extension'   => '.pya',
		'description' => 'Microsoft PlayReady Ecosystem',
	],
	['mime-type' => 'audio/vnd.nuera.ecelp4800', 'extension' => '.ecelp4800', 'description' => 'Nuera ECELP 4800'],
	['mime-type' => 'audio/vnd.nuera.ecelp7470', 'extension' => '.ecelp7470', 'description' => 'Nuera ECELP 7470'],
	['mime-type' => 'audio/vnd.nuera.ecelp9600', 'extension' => '.ecelp9600', 'description' => 'Nuera ECELP 9600'],
	['mime-type' => 'audio/vnd.rip', 'extension' => '.rip', 'description' => 'Hit\'n\'Mix'],
	['mime-type' => 'audio/webm', 'extension' => '.weba', 'description' => 'Open Web Media Project - Audio'],
	['mime-type' => 'audio/x-aac', 'extension' => '.aac', 'description' => 'Advanced Audio Coding (AAC)'],
	['mime-type' => 'audio/x-aiff', 'extension' => '.aif', 'description' => 'Audio Interchange File Format'],
	['mime-type' => 'audio/x-mpegurl', 'extension' => '.m3u', 'description' => 'M3U (Multimedia Playlist)'],
	[
		'mime-type'   => 'audio/x-ms-wax',
		'extension'   => '.wax',
		'description' => 'Microsoft Windows Media Audio Redirector',
	],
	['mime-type' => 'audio/x-ms-wma', 'extension' => '.wma', 'description' => 'Microsoft Windows Media Audio'],
	['mime-type' => 'audio/x-pn-realaudio', 'extension' => '.ram', 'description' => 'Real Audio Sound'],
	['mime-type' => 'audio/x-pn-realaudio-plugin', 'extension' => '.rmp', 'description' => 'Real Audio Sound'],
	['mime-type' => 'audio/x-wav', 'extension' => '.wav', 'description' => 'Waveform Audio File Format (WAV)'],
	['mime-type' => 'chemical/x-cdx', 'extension' => '.cdx', 'description' => 'ChemDraw eXchange file'],
	[
		'mime-type'   => 'chemical/x-cif',
		'extension'   => '.cif',
		'description' => 'Crystallographic Interchange Format',
	],
	['mime-type' => 'chemical/x-cmdf', 'extension' => '.cmdf', 'description' => 'CrystalMaker Data Format'],
	['mime-type' => 'chemical/x-cml', 'extension' => '.cml', 'description' => 'Chemical Markup Language'],
	['mime-type' => 'chemical/x-csml', 'extension' => '.csml', 'description' => 'Chemical Style Markup Language'],
	['mime-type' => 'chemical/x-xyz', 'extension' => '.xyz', 'description' => 'XYZ File Format'],
	['mime-type' => 'image/bmp', 'extension' => '.bmp', 'description' => 'Bitmap Image File'],
	['mime-type' => 'image/cgm', 'extension' => '.cgm', 'description' => 'Computer Graphics Metafile'],
	['mime-type' => 'image/g3fax', 'extension' => '.g3', 'description' => 'G3 Fax Image'],
	['mime-type' => 'image/gif', 'extension' => '.gif', 'description' => 'Graphics Interchange Format'],
	['mime-type' => 'image/ief', 'extension' => '.ief', 'description' => 'Image Exchange Format'],
	['mime-type' => 'image/jpeg', 'extension' => '.jpg', 'description' => 'JPEG Image'],
	['mime-type' => 'image/ktx', 'extension' => '.ktx', 'description' => 'OpenGL Textures (KTX)'],
	['mime-type' => 'image/pjpeg', 'extension' => '.pjpeg', 'description' => 'JPEG Image (Progressive)'],
	['mime-type' => 'image/png', 'extension' => '.png', 'description' => 'Portable Network Graphics (PNG)'],
	['mime-type' => 'image/prs.btif', 'extension' => '.btif', 'description' => 'BTIF'],
	['mime-type' => 'image/svg+xml', 'extension' => '.svg', 'description' => 'Scalable Vector Graphics (SVG)'],
	['mime-type' => 'image/tiff', 'extension' => '.tiff', 'description' => 'Tagged Image File Format'],
	['mime-type' => 'image/vnd.adobe.photoshop', 'extension' => '.psd', 'description' => 'Photoshop Document'],
	['mime-type' => 'image/vnd.dece.graphic', 'extension' => '.uvi', 'description' => 'DECE Graphic'],
	['mime-type' => 'image/vnd.djvu', 'extension' => '.djvu', 'description' => 'DjVu'],
	[
		'mime-type'   => 'image/vnd.dvb.subtitle',
		'extension'   => '.sub',
		'description' => 'Close Captioning - Subtitle',
	],
	['mime-type' => 'image/vnd.dwg', 'extension' => '.dwg', 'description' => 'DWG Drawing'],
	['mime-type' => 'image/vnd.dxf', 'extension' => '.dxf', 'description' => 'AutoCAD DXF'],
	['mime-type' => 'image/vnd.fastbidsheet', 'extension' => '.fbs', 'description' => 'FastBid Sheet'],
	['mime-type' => 'image/vnd.fpx', 'extension' => '.fpx', 'description' => 'FlashPix'],
	['mime-type' => 'image/vnd.fst', 'extension' => '.fst', 'description' => 'FAST Search & Transfer ASA'],
	['mime-type' => 'image/vnd.fujixerox.edmics-mmr', 'extension' => '.mmr', 'description' => 'EDMICS 2000'],
	['mime-type' => 'image/vnd.fujixerox.edmics-rlc', 'extension' => '.rlc', 'description' => 'EDMICS 2000'],
	[
		'mime-type'   => 'image/vnd.ms-modi',
		'extension'   => '.mdi',
		'description' => 'Microsoft Document Imaging Format',
	],
	['mime-type' => 'image/vnd.net-fpx', 'extension' => '.npx', 'description' => 'FlashPix'],
	['mime-type' => 'image/vnd.wap.wbmp', 'extension' => '.wbmp', 'description' => 'WAP Bitamp (WBMP)'],
	['mime-type' => 'image/vnd.xiff', 'extension' => '.xif', 'description' => 'eXtended Image File Format (XIFF)'],
	['mime-type' => 'image/webp', 'extension' => '.webp', 'description' => 'WebP Image'],
	['mime-type' => 'image/x-citrix-jpeg', 'extension' => '.jpg', 'description' => 'JPEG Image (Citrix client)'],
	[
		'mime-type'   => 'image/x-citrix-png',
		'extension'   => '.png',
		'description' => 'Portable Network Graphics (PNG) (Citrix client)',
	],
	['mime-type' => 'image/x-cmu-raster', 'extension' => '.ras', 'description' => 'CMU Image'],
	['mime-type' => 'image/x-cmx', 'extension' => '.cmx', 'description' => 'Corel Metafile Exchange (CMX)'],
	['mime-type' => 'image/x-freehand', 'extension' => '.fh', 'description' => 'FreeHand MX'],
	['mime-type' => 'image/x-icon', 'extension' => '.ico', 'description' => 'Icon Image'],
	['mime-type' => 'image/x-pcx', 'extension' => '.pcx', 'description' => 'PCX Image'],
	['mime-type' => 'image/x-pict', 'extension' => '.pic', 'description' => 'PICT Image'],
	[
		'mime-type'   => 'image/x-png',
		'extension'   => '.png',
		'description' => 'Portable Network Graphics (PNG) (x-token)',
	],
	['mime-type' => 'image/x-portable-anymap', 'extension' => '.pnm', 'description' => 'Portable Anymap Image'],
	['mime-type' => 'image/x-portable-bitmap', 'extension' => '.pbm', 'description' => 'Portable Bitmap Format'],
	['mime-type' => 'image/x-portable-graymap', 'extension' => '.pgm', 'description' => 'Portable Graymap Format'],
	['mime-type' => 'image/x-portable-pixmap', 'extension' => '.ppm', 'description' => 'Portable Pixmap Format'],
	['mime-type' => 'image/x-rgb', 'extension' => '.rgb', 'description' => 'Silicon Graphics RGB Bitmap'],
	['mime-type' => 'image/x-xbitmap', 'extension' => '.xbm', 'description' => 'X BitMap'],
	['mime-type' => 'image/x-xpixmap', 'extension' => '.xpm', 'description' => 'X PixMap'],
	['mime-type' => 'image/x-xwindowdump', 'extension' => '.xwd', 'description' => 'X Window Dump'],
	['mime-type' => 'message/rfc822', 'extension' => '.eml', 'description' => 'Email Message'],
	[
		'mime-type'   => 'model/iges',
		'extension'   => '.igs',
		'description' => 'Initial Graphics Exchange Specification (IGES)',
	],
	['mime-type' => 'model/mesh', 'extension' => '.msh', 'description' => 'Mesh Data Type'],
	['mime-type' => 'model/vnd.collada+xml', 'extension' => '.dae', 'description' => 'COLLADA'],
	['mime-type' => 'model/vnd.dwf', 'extension' => '.dwf', 'description' => 'Autodesk Design Web Format (DWF)'],
	[
		'mime-type'   => 'model/vnd.gdl',
		'extension'   => '.gdl',
		'description' => 'Geometric Description Language (GDL)',
	],
	['mime-type' => 'model/vnd.gtw', 'extension' => '.gtw', 'description' => 'Gen-Trix Studio'],
	['mime-type' => 'model/vnd.mts', 'extension' => '.mts', 'description' => 'Virtue MTS'],
	['mime-type' => 'model/vnd.vtu', 'extension' => '.vtu', 'description' => 'Virtue VTU'],
	['mime-type' => 'model/vrml', 'extension' => '.wrl', 'description' => 'Virtual Reality Modeling Language'],
	['mime-type' => 'text/calendar', 'extension' => '.ics', 'description' => 'iCalendar'],
	['mime-type' => 'text/css', 'extension' => '.css', 'description' => 'Cascading Style Sheets (CSS)'],
	['mime-type' => 'text/csv', 'extension' => '.csv', 'description' => 'Comma-Seperated Values'],
	['mime-type' => 'text/html', 'extension' => '.html', 'description' => 'HyperText Markup Language (HTML)'],
	['mime-type' => 'text/n3', 'extension' => '.n3', 'description' => 'Notation3'],
	['mime-type' => 'text/plain', 'extension' => '.txt', 'description' => 'Text File'],
	['mime-type' => 'text/plain-bas', 'extension' => '.par', 'description' => 'BAS Partitur Format'],
	['mime-type' => 'text/prs.lines.tag', 'extension' => '.dsc', 'description' => 'PRS Lines Tag'],
	['mime-type' => 'text/richtext', 'extension' => '.rtx', 'description' => 'Rich Text Format (RTF)'],
	[
		'mime-type'   => 'text/sgml',
		'extension'   => '.sgml',
		'description' => 'Standard Generalized Markup Language (SGML)',
	],
	['mime-type' => 'text/tab-separated-values', 'extension' => '.tsv', 'description' => 'Tab Seperated Values'],
	['mime-type' => 'text/troff', 'extension' => '.t', 'description' => 'troff'],
	['mime-type' => 'text/turtle', 'extension' => '.ttl', 'description' => 'Turtle (Terse RDF Triple Language)'],
	['mime-type' => 'text/uri-list', 'extension' => '.uri', 'description' => 'URI Resolution Services'],
	['mime-type' => 'text/vnd.curl', 'extension' => '.curl', 'description' => 'Curl - Applet'],
	['mime-type' => 'text/vnd.curl.dcurl', 'extension' => '.dcurl', 'description' => 'Curl - Detached Applet'],
	['mime-type' => 'text/vnd.curl.mcurl', 'extension' => '.mcurl', 'description' => 'Curl - Manifest File'],
	['mime-type' => 'text/vnd.curl.scurl', 'extension' => '.scurl', 'description' => 'Curl - Source Code'],
	['mime-type' => 'text/vnd.fly', 'extension' => '.fly', 'description' => 'mod_fly / fly.cgi'],
	['mime-type' => 'text/vnd.fmi.flexstor', 'extension' => '.flx', 'description' => 'FLEXSTOR'],
	['mime-type' => 'text/vnd.graphviz', 'extension' => '.gv', 'description' => 'Graphviz'],
	['mime-type' => 'text/vnd.in3d.3dml', 'extension' => '.3dml', 'description' => 'In3D - 3DML'],
	['mime-type' => 'text/vnd.in3d.spot', 'extension' => '.spot', 'description' => 'In3D - 3DML'],
	[
		'mime-type'   => 'text/vnd.sun.j2me.app-descriptor',
		'extension'   => '.jad',
		'description' => 'J2ME App Descriptor',
	],
	['mime-type' => 'text/vnd.wap.wml', 'extension' => '.wml', 'description' => 'Wireless Markup Language (WML)'],
	[
		'mime-type'   => 'text/vnd.wap.wmlscript',
		'extension'   => '.wmls',
		'description' => 'Wireless Markup Language Script (WMLScript)',
	],
	['mime-type' => 'text/x-asm', 'extension' => '.s', 'description' => 'Assembler Source File'],
	['mime-type' => 'text/x-c', 'extension' => '.c', 'description' => 'C Source File'],
	['mime-type' => 'text/x-fortran', 'extension' => '.f', 'description' => 'Fortran Source File'],
	['mime-type' => 'text/x-java-source,java', 'extension' => '.java', 'description' => 'Java Source File'],
	['mime-type' => 'text/x-pascal', 'extension' => '.p', 'description' => 'Pascal Source File'],
	['mime-type' => 'text/x-setext', 'extension' => '.etx', 'description' => 'Setext'],
	['mime-type' => 'text/x-uuencode', 'extension' => '.uu', 'description' => 'UUEncode'],
	['mime-type' => 'text/x-vcalendar', 'extension' => '.vcs', 'description' => 'vCalendar'],
	['mime-type' => 'text/x-vcard', 'extension' => '.vcf', 'description' => 'vCard'],
	[
		'mime-type'   => 'text/yaml',
		'extension'   => '.yaml',
		'description' => 'YAML Ain\'t Markup Language / Yet Another Markup Language',
	],
	['mime-type' => 'video/3gpp', 'extension' => '.3gp', 'description' => '3GP'],
	['mime-type' => 'video/3gpp2', 'extension' => '.3g2', 'description' => '3GP2'],
	['mime-type' => 'video/h261', 'extension' => '.h261', 'description' => 'H.261'],
	['mime-type' => 'video/h263', 'extension' => '.h263', 'description' => 'H.263'],
	['mime-type' => 'video/h264', 'extension' => '.h264', 'description' => 'H.264'],
	['mime-type' => 'video/jpeg', 'extension' => '.jpgv', 'description' => 'JPGVideo'],
	['mime-type' => 'video/jpm', 'extension' => '.jpm', 'description' => 'JPEG 2000 Compound Image File Format'],
	['mime-type' => 'video/mj2', 'extension' => '.mj2', 'description' => 'Motion JPEG 2000'],
	['mime-type' => 'video/mp4', 'extension' => '.mp4', 'description' => 'MPEG-4 Video'],
	['mime-type' => 'video/mpeg', 'extension' => '.mpeg', 'description' => 'MPEG Video'],
	['mime-type' => 'video/ogg', 'extension' => '.ogv', 'description' => 'Ogg Video'],
	['mime-type' => 'video/quicktime', 'extension' => '.qt', 'description' => 'Quicktime Video'],
	['mime-type' => 'video/vnd.dece.hd', 'extension' => '.uvh', 'description' => 'DECE High Definition Video'],
	['mime-type' => 'video/vnd.dece.mobile', 'extension' => '.uvm', 'description' => 'DECE Mobile Video'],
	['mime-type' => 'video/vnd.dece.pd', 'extension' => '.uvp', 'description' => 'DECE PD Video'],
	['mime-type' => 'video/vnd.dece.sd', 'extension' => '.uvs', 'description' => 'DECE SD Video'],
	['mime-type' => 'video/vnd.dece.video', 'extension' => '.uvv', 'description' => 'DECE Video'],
	['mime-type' => 'video/vnd.fvt', 'extension' => '.fvt', 'description' => 'FAST Search & Transfer ASA'],
	['mime-type' => 'video/vnd.mpegurl', 'extension' => '.mxu', 'description' => 'MPEG Url'],
	[
		'mime-type'   => 'video/vnd.ms-playready.media.pyv',
		'extension'   => '.pyv',
		'description' => 'Microsoft PlayReady Ecosystem Video',
	],
	['mime-type' => 'video/vnd.uvvu.mp4', 'extension' => '.uvu', 'description' => 'DECE MP4'],
	['mime-type' => 'video/vnd.vivo', 'extension' => '.viv', 'description' => 'Vivo'],
	['mime-type' => 'video/webm', 'extension' => '.webm', 'description' => 'Open Web Media Project - Video'],
	['mime-type' => 'video/x-f4v', 'extension' => '.f4v', 'description' => 'Flash Video'],
	['mime-type' => 'video/x-fli', 'extension' => '.fli', 'description' => 'FLI/FLC Animation Format'],
	['mime-type' => 'video/x-flv', 'extension' => '.flv', 'description' => 'Flash Video'],
	['mime-type' => 'video/x-m4v', 'extension' => '.m4v', 'description' => 'M4v'],
	[
		'mime-type'   => 'video/x-ms-asf',
		'extension'   => '.asf',
		'description' => 'Microsoft Advanced Systems Format (ASF)',
	],
	['mime-type' => 'video/x-ms-wm', 'extension' => '.wm', 'description' => 'Microsoft Windows Media'],
	['mime-type' => 'video/x-ms-wmv', 'extension' => '.wmv', 'description' => 'Microsoft Windows Media Video'],
	[
		'mime-type'   => 'video/x-ms-wmx',
		'extension'   => '.wmx',
		'description' => 'Microsoft Windows Media Audio/Video Playlist',
	],
	[
		'mime-type'   => 'video/x-ms-wvx',
		'extension'   => '.wvx',
		'description' => 'Microsoft Windows Media Video Playlist',
	],
	['mime-type' => 'video/x-msvideo', 'extension' => '.avi', 'description' => 'Audio Video Interleave (AVI)'],
	['mime-type' => 'video/x-sgi-movie', 'extension' => '.movie', 'description' => 'SGI Movie'],
	['mime-type' => 'x-conference/x-cooltalk', 'extension' => '.ice', 'description' => 'CoolTalk'],
]);
